115 front task 커뮤니티 랜딩페이지 퍼블리싱
Selody-project/Frontend pull request #116
Opened 2023-08-19 13:03 UTC by sikkzz

# 설명

- [https://github.com/Selody-project/Frontend/issues/115](https://github.com/Selody-project/Frontend/issues/115)

#### 피드 랜딩페이지 현재 피그마 시안 기준으로 퍼블리싱
#### 현재 하드코딩으로 다 넣어놓은 상태, 추후 디자인 픽스되고 api 연결해서 재구성 예정
- #### 피드 랜딩페이지 테스트코드 작성
- #### 테스트 코드 작성 시 샘플 이미지로 넣어놓은 jpeg error 발생으로 인해 jest.config.cjs에서 transform에 jpeg 추가
- #### 기존에 존재하던 FeedMain 컴포넌트는 우선 주석 처리

# 테스트

-

# Demo

2023-08-21 08:12 UTC, 2Junsu requested changes

2023-08-21 08:12 UTC, 2Junsu commented on src/components/Feed/FeedLanding/FeedLanding.jsx
> +						<h3>그룹 추가</h3>
개인적으로 위에 '내 그룹 텍스트'가 h3인데, 아래 '그룹 추가', '디자인 스터디' 등의 텍스트도 동일하게 h3으로 설정하는 것이 좀 부적절하다는 생각이 드네요..! span이나 h3 아래의 h태그를 사용하는 건 어떨까요?

2023-08-21 08:12 UTC, 2Junsu commented on src/components/Feed/FeedLanding/FeedLanding.styles.js
> +export const TabDiv = styled.div`
div보다 ul과 li로 탭을 구성하면 접근성이 향상되어 좋을 것 같습니다!
관련 링크: https://meanbymin.tistory.com/41

2023-08-21 08:12 UTC, 2Junsu commented on src/components/Feed/FeedLanding/FeedLanding.styles.js
> +	}
부모 컴포넌트(현재 TabDiv)에 gap: 24px;을 부여하면, margin에 있는 24px과 first-of-type 자체를 지울 수 있을 것 같아요

2023-08-21 08:12 UTC, 2Junsu commented on src/components/Feed/FeedLanding/FeedLanding.styles.js
> +	}
여기도 gap을 사용하면 아래 Tab 컴포넌트처럼 수정할 수 있겠네요!

2023-08-21 08:12 UTC, 2Junsu commented on src/components/Feed/FeedLanding/FeedLanding.jsx
> +						type="button"
type은 빼도 문제 없어보이는데 특별히 넣으신 이유가 있을까요?

2023-08-21 08:12 UTC, 2Junsu commented on src/components/Feed/GroupFeed/GroupFeed.jsx
> +			</FeedDiv>
추후에 컴포넌트로 분리하면 좋을 것 같네요!

2023-08-21 08:12 UTC, 2Junsu commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +	width: 1276px;
width: 100%로 수정하는 게 더 깔끔할 것 같아요!

2023-08-21 08:12 UTC, 2Junsu commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +	}
이거 대신 ContainerDiv를 flexbox로 설정하고 gap을 주는 방식은 어떨까요?

2023-08-21 08:12 UTC, 2Junsu commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +	margin: 24px 0 0 18px;
아예 FeedDiv에 padding을 주면, ProfileDiv 뿐만 아니라 다른 내부 요소들에도 필요 없는 margin을 지울 수 있을 것 같아요

2023-08-21 08:12 UTC, 2Junsu commented on src/components/Feed/GroupSearch/GroupSearch.styles.js
> +`;
div를 아예 없애도 되지 않을까요? img 태그에 css를 합쳐버리면 더 간결해질 것 같아서요

2023-08-21 08:12 UTC, 2Junsu commented on src/components/Feed/GroupSearch/GroupSearch.styles.js
> +	width: 406px;
GroupDiv의 width를 없애고 ContainerDiv를 grid로 설정해서 사용하면 어떨까요?
```css
display: grid;
grid-template-columns: repeat(3, 1fr);
gap: 20px 26px;
```

2023-08-21 09:33 UTC, sikkzz commented on src/components/Feed/FeedLanding/FeedLanding.jsx
> +						<h3>그룹 추가</h3>
h4태그로 수정했습니다

2023-08-21 10:02 UTC, sikkzz commented on src/components/Feed/FeedLanding/FeedLanding.jsx
> +						type="button"
eslint에서 type 명시 안해주면 warning이 뜨길래 추가했습니다!

2023-08-21 10:03 UTC, sikkzz commented on src/components/Feed/FeedLanding/FeedLanding.styles.js
> +	}
수정했습니다.

2023-08-21 10:03 UTC, sikkzz commented on src/components/Feed/FeedLanding/FeedLanding.styles.js
> +	}
수정했습니다.

2023-08-21 10:04 UTC, sikkzz commented on src/components/Feed/FeedLanding/FeedLanding.styles.js
> +export const TabDiv = styled.div`
수정했습니다.

2023-08-21 10:28 UTC, sikkzz commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +	width: 1276px;
수정했습니다.

2023-08-21 10:29 UTC, sikkzz commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +	}
수정했습니다.

2023-08-21 10:34 UTC, sikkzz commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +	margin: 24px 0 0 18px;
profilediv와 textdiv가 div시작점이 달라서 textdiv는 margin-top값이 들어갈 수 밖에 없는데 다른 방법이 있을까요?

2023-08-21 10:36 UTC, sikkzz commented on src/components/Feed/GroupSearch/GroupSearch.styles.js
> +`;
수정했습니다.

2023-08-21 10:38 UTC, sikkzz commented on src/components/Feed/GroupSearch/GroupSearch.styles.js
> +	width: 406px;
수정했습니다.

2023-08-21 11:00 UTC, sikkzz commented on src/components/Feed/GroupFeed/GroupFeed.jsx
> +			</FeedDiv>
네 추후에 다른 레이아웃들이랑 연결 완료하면 다른 부분들도 세부적으로 나눠볼 예정입니다.

2023-08-21 13:44 UTC, 2Junsu commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +	margin: 24px 0 0 18px;
margin을 주기보단 프로필 사진, 작성자, 작성 시간을 하나로 묶어서 row flex, align-items: center로 가운데 정렬하면 되지 않을까요?
위랑 본문이랑 margin으로 간격을 주고요
FeedDiv는 [프로필 사진, 작성자, 작성 시간], [본문]의 묶음으로 구성되도록이요!

2023-08-22 02:11 UTC, kimyoungyin requested changes
감사합니다! 어떤 색상을 theme에 넣을 것인지도 고민해보면 좋을 것 같아요

2023-08-22 02:11 UTC, kimyoungyin commented on src/components/Feed/FeedLanding/FeedLanding.styles.js
> +		color: #000;
기본 색상이 black인데 여기 `color` 속성을 명시한 이유가 있을까요?

2023-08-22 02:11 UTC, kimyoungyin commented on src/components/Feed/GroupFeed/GroupFeed.jsx
컴포넌트 명을 `MyGroupFeed`로 변경하는게 어떠세요? 나중에 그룹 하나의 피드를 보여주는 페이지도 나올 텐데,
이와 혼동될 것 같습니다.

2023-08-22 02:11 UTC, kimyoungyin commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +`;
부모가 flex box라 브라우저 너비가 줄어들면 원이 쭈그러들 위험이 있습니다.
실제로 테스트 해보니 너비 `1150px` 이하부터 타원으로 바뀝니다.
<img width="561" alt="스크린샷 2023-08-22 오전 10 23 57" src="https://github.com/Selody-project/Frontend/assets/78777345/dd51f39e-b775-4e4a-b718-a3478bf4f916">
`min-width` 속성을 `width` 속성값 대신 넣어주면 해결됩니다.
`width`는 지워도 될 거에요

2023-08-22 02:11 UTC, kimyoungyin commented on src/components/Feed/FeedLanding/FeedLanding.styles.js
> +	height: 62px;
여기는 당장은 괜찮은데, 내가 속한 그룹이 많아지면서 x축 스크롤이 필요해진다면, 원이 쭈그러들지 않기 위해 `min-width`를 주는 것이 좋아보입니다. 

_나중에 스크롤할 때 부모 태그에 100% 너비를 줘야되긴 할 겁니다._

2023-08-22 02:11 UTC, kimyoungyin commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +	padding: 24px 0 0 18px;
padding은 좌상단만 주셨는데 나중에 text가 넘칠 것 까지 고려해서 

최소 오른쪽까지는 padding을 왼쪽과 동일하게 주는 게 좋을 것 같습니다.

아래쪽은 TextDiv에서 margin을 주는 것으로 대신 처리하셨는데 의도하신 걸까요?
<img width="561" alt="스크린샷 2023-08-22 오전 10 39 13" src="https://github.com/Selody-project/Frontend/assets/78777345/c63b8e4e-909f-42ff-801d-a722cf6551b0">

2023-08-22 02:11 UTC, kimyoungyin commented on src/components/Feed/GroupSearch/GroupSearch.styles.js
> +	align-items: center;
padding을 적절히 주는 것이 좋아보이는데 어떠세요?

2023-08-22 02:11 UTC, kimyoungyin commented on src/components/Feed/GroupSearch/GroupSearch.styles.js
> +		height: 58px;
여기는 `min-height`를 주는게 좋아보이네요
<img width="561" alt="스크린샷 2023-08-22 오전 10 42 47" src="https://github.com/Selody-project/Frontend/assets/78777345/fb3cbdab-92a6-4897-a432-bc74dfe6560c">

2023-08-22 10:21 UTC, sikkzz commented on src/components/Feed/FeedLanding/FeedLanding.styles.js
> +		color: #000;
삭제했습니다.

2023-08-22 10:23 UTC, sikkzz commented on src/components/Feed/GroupFeed/GroupFeed.jsx
네 그게 좋을 거 같네요 수정했습니다

2023-08-22 10:24 UTC, sikkzz commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +`;
수정했습니다

2023-08-22 10:26 UTC, sikkzz commented on src/components/Feed/FeedLanding/FeedLanding.styles.js
> +	height: 62px;
추후 carousel로 수정하는게 좋을 거 같습니다

2023-08-22 10:27 UTC, sikkzz commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +	padding: 24px 0 0 18px;
이부분 좋아요랑 댓글때문에 디자인 수정이 들어갈 예정으로 알고있습니다. 그래서 그냥 여백상으로 두고 추후 퍼블리싱 추가 예정입니다

2023-08-22 10:29 UTC, sikkzz commented on src/components/Feed/GroupSearch/GroupSearch.styles.js
> +	align-items: center;
반응형 디자인이 나온다면 디스플레이 사이즈별 조절할 일이 생길 거 같습니다. 추후 수정하겠습니다

2023-08-22 10:31 UTC, sikkzz commented on src/components/Feed/GroupSearch/GroupSearch.styles.js
> +		height: 58px;
박스 사이즈가 이미지처럼 줄어드는 사이즈면 디자인이 달라지지 않을까 싶습니다. 추후에 수정하겠습니다

2023-08-23 01:47 UTC, kimyoungyin commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +	padding: 24px 0 0 18px;
넵 알겠습니다

2023-08-23 01:49 UTC, kimyoungyin commented on src/components/Feed/GroupSearch/GroupSearch.styles.js
> +		height: 58px;
저 레이아웃은 그대로 유지되지 않을까요? 한 열에 보여주는 그룹 수가 달라질 수는 있겠지만요

2023-08-23 01:51 UTC, kimyoungyin requested changes
import 문만 수정하면 좋겠네요!

2023-08-23 01:51 UTC, kimyoungyin commented on src/components/Feed/FeedLanding/FeedLanding.jsx
> +import GroupFeed from "../MyGroupFeed/MyGroupFeed";
감사합니다

import 시에도 동일한 컴포넌트명으로 가져오는 게 나을 것 같은데요?

2023-08-23 01:52 UTC, kimyoungyin commented on src/components/Feed/FeedLanding/FeedLanding.styles.js
> +	height: 62px;
넵 좋습니다

2023-08-23 07:03 UTC, 2Junsu commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +	margin: 24px 0 0 18px;
이 부분도 검토해주시면 감사하겠습니다~!

2023-08-23 17:12 UTC, sikkzz commented on src/components/Feed/GroupFeed/GroupFeed.styles.js
> +	margin: 24px 0 0 18px;
말씀하신대로 수정했을때 프로필 사진과 작성자, 작성 시간은 따른 div로 구성해야해서 div컴포넌트가 더 늘어나게 됩니다. 또한 우측에 댓글이나 좋아요 관련 컴포넌트가 추가될걸 고려하면 프로필과 작성자, 작성 시간, 본문 그리고 우측 좋아요, 댓글 관련 컴포넌트 3개를 row로 배치하는게 더 낫지 않나 생각합니다.

2023-08-23 17:14 UTC, sikkzz commented on src/components/Feed/GroupSearch/GroupSearch.styles.js
> +		height: 58px;
height값이 현재 값보다 작아질 수치까지 조정되는 디스플레이라면 디자인이나 수치들이 수정될 수 밖에 없다고 생각합니다. 그래서 추후에 반응형이나 사이즈별 조정이 필요하게 되면 그때 맞춰서 수정하려 합니다.

2023-08-23 17:15 UTC, sikkzz commented on src/components/Feed/FeedLanding/FeedLanding.jsx
> +import GroupFeed from "../MyGroupFeed/MyGroupFeed";
맞네요 수정했습니다.

2023-08-28 00:24 UTC, kimyoungyin submitted a review, later dismissed

2023-08-28 08:36 UTC, 2Junsu commented on src/components/Feed/MyGroupFeed/MyGroupFeed.jsx
> +							</span>
margin-left를 주려고 span을 넣으신 걸까요?? 그런 거라면 그냥 span을 지우고 & > svg에 margin-left를 줘도 될 것 같아요!

2023-08-28 09:57 UTC, sikkzz commented on src/components/Feed/MyGroupFeed/MyGroupFeed.jsx
> +							</span>
수정했습니다!

2023-08-28 09:59 UTC, 2Junsu approved these changes, later dismissed

2023-08-29 09:42 UTC, sikkzz commented
merge하다가 충돌 부분 해결한다고 커밋이 겹치고 늘었는데 특별히 추가되거나 달라진 코드는 없습니다. 확인 한번 부탁드립니다.

2023-08-29 09:50 UTC, 2Junsu commented on src/pages/FeedPage.jsx
> +			{/* <FeedMain /> */}
이 둘은 이제 필요 없는 것 같은데 지우는 게 낫지 않을까요?

2023-08-29 09:53 UTC, sikkzz commented on src/pages/FeedPage.jsx
> +			{/* <FeedMain /> */}
네! 삭제 완료했습니다

2023-08-29 09:58 UTC, 2Junsu requested changes

2023-08-29 09:58 UTC, 2Junsu commented on src/pages/FeedPage.jsx
> +	return <FeedLanding />;
한 줄 짜리니까 {return}말고 ()로 써주시면 됩니다!

2023-08-29 10:24 UTC, 2Junsu approved these changes, later dismissed

2023-08-30 07:27 UTC, kimyoungyin reviewed
그룹 검색 input이 구현이 안되어 있는데 맞을까요? 딱 '내 그룹 피드'까지만 하신 걸까요?

2023-08-30 07:27 UTC, kimyoungyin commented
> 그룹 검색 input이 구현이 안되어 있는데 맞을까요? 딱 '내 그룹 피드'까지만 하신 걸까요?

댓글 개수나 좋아요 이런 건 디자인 완성되면 추가하면 되겠죠?

2023-08-30 07:50 UTC, sikkzz commented
네 검색창 ui도 확정이 안났고 api기능도 아직 없어서 우선 냅뒀습니다. 댓글 개수, 좋아요 디자인은 요청드려놨습니다!

2023-08-30 07:56 UTC, kimyoungyin requested changes

2023-08-30 07:56 UTC, kimyoungyin commented on src/pages/CommunityPage.jsx
이렇게 해놓으면 CommunityPage와 CommunityLanding을 분리할 이유가 없지 않나요?

2023-08-30 07:56 UTC, kimyoungyin commented on src/components/Community/CommunityLanding/CommunityLanding.styles.js
> +	margin: 0 82px;
여기 상단의 margin 같은 걸로 좀 더 Header랑 거리를 두는 게 좋아보입니다.
- figma
<img width="565" alt="스크린샷 2023-08-30 오후 4 35 07" src="https://github.com/Selody-project/Frontend/assets/78777345/bb1c8895-4ffb-433b-b27b-ae9f12cad96a">

- 브라우저
<img width="565" alt="스크린샷 2023-08-30 오후 4 35 20" src="https://github.com/Selody-project/Frontend/assets/78777345/589ba41d-bb01-46d2-969b-3734f2c2a5d6">

2023-08-30 07:56 UTC, kimyoungyin commented on src/components/Community/MyGroup/MyGroup.styles.js
> +export const ItemDiv = styled.div`
`cursor: pointer` 필요할 것 같습니다
나중에 링크로 사용될 예정이니까요!

2023-08-30 07:56 UTC, kimyoungyin commented on src/components/Community/MyGroup/MyGroup.styles.js
> +		margin-top: 8px;
ItemDiv에 gap 8px을 주면 h4 margin 8px는 필요 없어보입니다

2023-08-30 07:56 UTC, kimyoungyin commented on src/components/Community/MyGroupFeed/MyGroupFeed.styles.js
> +`;
`cursor: pointer`가 필요할 것 같습니다.

2023-08-30 07:56 UTC, kimyoungyin commented on src/components/Community/MyGroupFeed/MyGroupFeed.styles.js
> +		color: #2f2f2f;
이 색상코드도 자주 쓰신 것 같은데 theme에 추가해달라고 지수님한테 말씀드려야 될까요?

2023-08-30 08:49 UTC, sikkzz commented on src/pages/CommunityPage.jsx
그런거 같네요 수정했습니다! 그럼 component에서 community 폴더는 남는게 group search, mygroup, mygroupfeed 컴포넌트인데 나중에 group페이지에 있는 group 폴더로 옮기는게 좋을까요? 아니면 이대로 유지하는게 좋을까요?

2023-08-30 08:49 UTC, sikkzz commented on src/components/Community/CommunityLanding/CommunityLanding.styles.js
> +	margin: 0 82px;
수정했습니다.

2023-08-30 08:49 UTC, sikkzz commented on src/components/Community/MyGroup/MyGroup.styles.js
> +export const ItemDiv = styled.div`
수정했습니다.

2023-08-30 08:49 UTC, sikkzz commented on src/components/Community/MyGroup/MyGroup.styles.js
> +		margin-top: 8px;
수정했습니다.

2023-08-30 08:50 UTC, sikkzz commented on src/components/Community/MyGroupFeed/MyGroupFeed.styles.js
> +`;
수정했습니다. 추후 컴포넌트에서 요소마다 링크 다르게 이동할껀지 논의해보고 수정 필요하면 나눠서 pointer 지정하도록 하겠습니다.

2023-08-30 08:50 UTC, sikkzz commented on src/components/Community/MyGroupFeed/MyGroupFeed.styles.js
> +		color: #2f2f2f;
우선 현재는 3번정도 썼는데  더 늘어나면 한번 요청드리겠습니다!

2023-09-01 14:08 UTC, 2Junsu approved these changes, later dismissed

2023-09-05 10:14 UTC, 2Junsu approved these changes

2023-09-05 10:19 UTC, kimyoungyin commented on src/pages/CommunityPage.jsx
Pages 하위 디렉토리는 그냥 해당 라우트 최상단 페이지 jsx랑 스타일, 딱 이 두 개만 있으면 좋을 것 같아요!
그대로 components 하위에 위 컴포넌트들을 위치하는 게 좋을 것 같습니다

2023-09-05 10:23 UTC, kimyoungyin approved these changes

2023-09-05 10:37 UTC, merged