Feat/personal schedule page navigation
Selody-project/Frontend pull request #119
Opened 2023-08-21 05:20 UTC by kimyoungyin

# 설명
개인 일정과 그룹 일정 nav를 구현하였습니다.
figma 디자인에 따라 필요없는 버튼과 레이아웃은 제거하고 진행하였습니다.
- `theme.js`에 빠져있는 값 `lightTheme.colors.text_01`와 `lightTheme.typography.weight.semibold` 값을 추가하였습니다.
- 기존 디자인에서 변경하기로 했듯이 **개인 일정**을 우선 배치했습니다.

# Demo
<img width="561" alt="스크린샷 2023-08-21 오후 2 14 30" src="https://github.com/Selody-project/Frontend/assets/78777345/97442b96-507c-4191-a953-db22dc0ae22f">

2023-08-21 07:29 UTC, 2Junsu requested changes
리뷰하면서 갑자기 드는 생각이 이 부분은 제가 Header 작업하면서 같이 작업해야하는 부분이 아닌가 싶네요..!

2023-08-21 07:29 UTC, 2Junsu commented on src/components/Header/GroupHeader/GroupHeader.jsx
> +					<NavLink to="/" className={`${isPersonal ? "activated" : ""}`}>
NavLink의 className에는 자체적으로 isActive props가 있다고 하네요.
```js
className={({ isActive }) => (isActive ? "activated" : "")}
```
위처럼 사용하면 isPersonal가 굳이 필요 없을 것 같아요!

2023-08-21 07:29 UTC, 2Junsu commented on src/components/Header/GroupHeader/GroupHeader.styles.js
> +			font-weight: ${lightTheme.typography.weight.semibold};
lightTheme을 import하지 말고, 아래처럼 props로 theme을 받아와서 사용하면 좋을 것 같아요
```css
color: ${({ theme: { colors } }) => colors.primary};
```

2023-08-21 07:29 UTC, 2Junsu commented on src/components/Header/GroupHeader/GroupHeader.styles.js
> +	width: 227px;
전체 width를 227이라는 애매한 숫자로 설정하기 보다는 아래처럼 수정하는 건 어떨까요?
```css
width: fit-content;
gap: 48px;
```

2023-08-21 08:24 UTC, kimyoungyin commented on src/components/Header/GroupHeader/GroupHeader.styles.js
> +			font-weight: ${lightTheme.typography.weight.semibold};
아 맞네요 깜빡했습니다. 반영할게요

2023-08-21 08:46 UTC, kimyoungyin commented on src/components/Header/GroupHeader/GroupHeader.styles.js
> +			font-weight: ${lightTheme.typography.weight.semibold};
근데 javascript에서는 원래 theme 객체 자동완성이 지원 안되나요? 작성은 했는데 제대로 theme 객체를 추적하지 못하네요?
<img width="561" alt="스크린샷 2023-08-21 오후 5 40 17" src="https://github.com/Selody-project/Frontend/assets/78777345/4220fc80-302e-463e-80d5-0cb77cb55d32">

2023-08-21 08:51 UTC, kimyoungyin commented on src/components/Header/GroupHeader/GroupHeader.jsx
> +					<NavLink to="/" className={`${isPersonal ? "activated" : ""}`}>
반영 완료!

2023-08-21 08:53 UTC, kimyoungyin commented
> 리뷰하면서 갑자기 드는 생각이 이 부분은 제가 Header 작업하면서 같이 작업해야하는 부분이 아닌가 싶네요..!

저도 그렇게 생각했다가 Header 부분이랑 같이 있는 게 아니라, 그룹 일정/개인 일정 페이지에만 국한되어 있어서
제가 작업해도 괜찮다고 생각했어요.
Header 작업할 때 둘이 margin만 잘 남겨주세요 ㅎ

2023-08-21 08:55 UTC, kimyoungyin commented on src/components/Header/GroupHeader/GroupHeader.styles.js
> +	width: 227px;
이건 나중에 반응형으로 개발할 때 어떻게 될지 모르는 부분이라 일단 figma 고정 너비로 남겨두었습니다.
두 `li` 사이 `gap`만 고정되어 있고 너비가 변하도록 반응형 개발 디자인이 결정된다면 수정하는 게 나을 것 같은데 어떠신가요?

`GroupHeaderNav`의 `margin-left` 값도 마찬가지입니다.

2023-08-21 08:59 UTC, 2Junsu commented on src/components/Header/GroupHeader/GroupHeader.styles.js
> +	width: 227px;
네 나중에 수정하신다면 상관 없을 것 같습니다!

2023-08-21 08:59 UTC, 2Junsu commented on src/components/Header/GroupHeader/GroupHeader.styles.js
> +			font-weight: ${lightTheme.typography.weight.semibold};
네 아마 ts가 아니라 그런 것 같아요..저도 추적이 안 되더라고요

2023-08-21 09:07 UTC, 2Junsu submitted a review, later dismissed

2023-08-21 10:41 UTC, sikkzz approved these changes

2023-08-21 17:50 UTC, 2Junsu commented
헤더 작업해보니까 Header 내에서 다 관리해야 할 것 같아서 이쪽 코드가 필요 없을 것 같네요ㅜㅜ 
merge 안 하셔도 되고 제가 같이 작업할게요

2023-08-22 00:26 UTC, kimyoungyin commented
> 헤더 작업해보니까 Header 내에서 다 관리해야 할 것 같아서 이쪽 코드가 필요 없을 것 같네요ㅜㅜ merge 안 하셔도 되고 제가 같이 작업할게요

develop에 머지하고 이어 받아서 작업하셔도 될 것 같은데 어떠세요?

2023-08-23 04:57 UTC, closed without merging