121 front task header 구현
Selody-project/Frontend pull request #122
Opened 2023-08-22 10:54 UTC by 2Junsu

# 설명

- #121 
- Header 구현
  - 그룹 생성 모달, 프로필 및 알림 dropdown 구현
- 기존에는 sub header가 GroupHeader나 FeedHeader로 나뉘어져 있었지만, 하나로 통합
- MyPage를 SettingPage로 변경
- 컬러 시스템 최신화 후 수정 필요

# 테스트

-

# Demo
- 공유일정 페이지에서 스크롤바 때문에 헤더 위치가 달라지는데, 추후 공유일정 작업에서 우측 투두리스트 공간을 개인일정과 동일하게 맞추면 해결될 것으로 보입니다.

https://github.com/Selody-project/Frontend/assets/77619905/45aa9b5b-0cc2-47a1-a76b-90dd067aef20

2023-08-23 04:53 UTC, kimyoungyin requested changes

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Base/BaseModal/BaseModal.style.js
>  export const BackdropWrapper = styled.div`
헤더 부분은 아니지만 모달이 떴을 때 `backdrop`을 포함한 body가 스크롤되지 않도록 수정 가능할까요?

`useEffect` 사용해서 해결 가능한 것으로 알고 있습니다.

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/GroupCreateModal/GroupCreateModal.jsx
> +	// const [introduction, setIntroduction] = useState("");
이 부분은 의도적으로 남겨둔 주석일까요? 아니면 제거하는게 나을까요?

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/GroupCreateModal/GroupCreateModal.style.js
> +	all: unset;
`all: unset`
`input`이랑 `button` 태그에 해당 코드가 계속 들어가는데 global Style에서 해당 태그에 적용시키는 건 어떠세요?
> `textarea`도 필요할까요?

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/GroupCreateModal/GroupCreateModal.style.js
> +		color: ${({ theme: { colors } }) => colors.modal_disabled_text};
`input`, `textarea`의 `placeholder` `color`는 동일해아 합니다!

둘 다 `disabled_text`로 수정하면 디자인과 동일합니다!

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/GroupCreateModal/GroupCreateModal.jsx
> +					생성하기
`name.trim()`이 필요해보입니다.

2023-08-23 04:53 UTC, kimyoungyin commented on __test__/pagesTest/SettingPage.test.jsx
제가 테스트코드를 작성해본 적이 없어서..
공부하고 이 부분 확인해보겠습니다 ㅠ

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/Header/Header.jsx
> +	});
혹시 이 부분 설명 부탁드려도 괜찮을까요?

`useEffect` `deps`를 생략하고, `useEffect` 내부에서만 사용하는 함수(`closeDropdown`)를 밖에 위치 시키면서 어떤 방식으로 작동하게 되는 걸까요?

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/Header/Header.styles.js
> +	box-shadow: 0px 5px 50px 4px rgba(0, 0, 0, 0.1);
`ContainerHeader`에 `margin-bottom`을 좀 주어야 다른 페이지에서 사용하기 좋을 것 같아요

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/SubHeader/SubHeader.style.js
> +	display: none;
이 부분 굳이 숨길 필요가 있을까요?
현재 있는 `tab`의 `SubHeader`는 계속 보여주는 게 좋을 것 같은데요?
<img width="561" alt="스크린샷 2023-08-23 오후 1 14 23" src="https://github.com/Selody-project/Frontend/assets/78777345/ab126b6c-b4f1-4ff1-bdcd-f9ce72135bd1">

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/SubHeader/SubHeader.style.js
> +	}
유저가 클릭을 편하게 할 수 있도록 클릭 가능한 li 요소 범위를 꽉 채우는게 낫지 않을까요? 현재는 딱 text 너비까지만 hover를 걸어주었습니다.
<img width="277" alt="스크린샷 2023-08-23 오후 1 23 38" src="https://github.com/Selody-project/Frontend/assets/78777345/c25f0bfe-4f6f-468b-b2d9-04fbdf5fbb15">

ul 안에 각각 li, button 요소의 크기를 꽉 채우되 text만 중간 정렬하는게 어떨까요?

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/SubHeader/SubHeader.jsx
> +			  ];
`setState`를 쓰지도 않고, 하드코딩된 함수라 `tab`을 `parameter`로 받는 순수 함수로 만들고 컴포넌트 밖으로 빼도 좋을 것 같은데요?

밖으로 뺸 함수는 같은 파일 내 위쪽에 두거나, 같은 레벨의 디렉토리에 따로 함수를 만드는 것도 좋아보입니다.

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/SubHeader/SubHeader.jsx
> +const SubHeader = ({ tab }) => {
SubHeader를 제 의견대로 항상 display하게 둔다면 ref, useEffect를 동반한 로직도 필요없을 것 같습니다.

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/Header/Header.jsx
> +					<ProfileDropdown ref={dropdownRef} isOpen={isDropdownOpen} />
`isOpen`을 굳이 `prop`으로 줄 필요가 있을까요?
그냥 이 컴포넌트에서 다음과 같이 작성하면 되지 않을까요? 
```js
{isDropdownOpen && <ProfileDropdown ref={dropdownRef} isOpen={isDropdownOpen} />}
```

이렇게 하면 `ProfileDropdown`에서도 style에 `isOpen`을 전달할 필요도 없고 좋을 것 같습니다.

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/Header/Header.jsx
> +	});
아 물론 항상 display하게 둔다면 이 로직도 필요 없어지겠네요

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/ProfileDropdown/ProfileDropdown.style.js
> +	right: 0;
이 값은 임의로 설정하신 걸까요? 약간 프로필 이미지 위치에서 벗어난 것 같아서요
<img width="277" alt="스크린샷 2023-08-23 오후 1 36 15" src="https://github.com/Selody-project/Frontend/assets/78777345/44ed961c-3748-4c55-b91b-94a867946da7">

2023-08-23 04:53 UTC, kimyoungyin commented on src/components/Header/SubHeader/SubHeader.jsx
> +			<NotificationDropdown ref={dropdownRef} isOpen={isNotiTabOpen} />
여기서도 위처럼 굳이 `isOpen`을 `prop`으로 줘야 할까요?

2023-08-23 05:31 UTC, kimyoungyin commented
> # 설명
> * [[FRONT-TASK] Header 구현 #121](https://github.com/Selody-project/Frontend/issues/121)
> * Header 구현
>   
>   * 그룹 생성 모달, 프로필 및 알림 dropdown 구현
> * 기존에는 sub header가 GroupHeader나 FeedHeader로 나뉘어져 있었지만, 하나로 통합
> * MyPage를 SettingPage로 변경
> * 컬러 시스템 최신화 후 수정 필요
> 
> # 테스트
> 
> # Demo
> * 공유일정 페이지에서 스크롤바 때문에 헤더 위치가 달라지는데, 추후 공유일정 작업에서 우측 투두리스트 공간을 개인일정과 동일하게 맞추면 해결될 것으로 보입니다.
> 
>  121.demo.mov

`<Header />`를 필요한 컴포넌트마다 불러오지 말고 `<Outlet />`이 있는 `Root` 내에 두면 편하지 않을까요?
<img width="259" alt="스크린샷 2023-08-23 오후 2 30 49" src="https://github.com/Selody-project/Frontend/assets/78777345/c4b9a26e-b07a-4d09-973c-f84f1d41fa0c">

2023-08-23 08:48 UTC, 2Junsu commented on src/components/Header/GroupCreateModal/GroupCreateModal.jsx
> +	// const [introduction, setIntroduction] = useState("");
아직 쓰이는 곳이 없어서 빨간줄을 없애고자 주석 처리 해놨어요

2023-08-23 08:48 UTC, 2Junsu commented on src/components/Header/GroupCreateModal/GroupCreateModal.style.js
> +	all: unset;
button에만 적용해도 될 것 같네요!

2023-08-23 08:48 UTC, 2Junsu commented on src/components/Header/GroupCreateModal/GroupCreateModal.style.js
> +		color: ${({ theme: { colors } }) => colors.modal_disabled_text};
이전 피그마 시안대로 작업했는데, 다시 바뀐 디자인으로 수정해야겠네요

2023-08-23 08:49 UTC, 2Junsu commented on __test__/pagesTest/SettingPage.test.jsx
이쪽은 기존 작성돼있던 코드에서 에러 해결만 하고 제가 따로 작업하진 않았어요!

2023-08-23 08:49 UTC, 2Junsu commented on src/components/Header/SubHeader/SubHeader.style.js
> +	display: none;
지수님께 여쭤보고 답변 받은대로 구현했습니다! hover 시에 보이면 좋을 것 같다고 하셨어요

2023-08-23 08:50 UTC, 2Junsu commented on src/components/Header/Header/Header.styles.js
> +	box-shadow: 0px 5px 50px 4px rgba(0, 0, 0, 0.1);
페이지마다 margin이 달라서 각 페이지에서 margin-top을 주는 게 더 낫지 않을까요??

2023-08-23 08:52 UTC, 2Junsu commented on src/components/Header/ProfileDropdown/ProfileDropdown.style.js
> +	right: 0;
네 피그마 시안에 최대한 맞게 조절했어요..!

2023-08-23 09:05 UTC, 2Junsu commented on src/components/Header/Header/Header.jsx
> +	});
프로필 이미지 클릭으로만 드롭다운을 여닫아야 하는 게 불편해서, 프로필 이미지와 드롭다운을 제외한 모든 영역에서 클릭 이벤트가 발생했을 때 드롭다운을 닫는 로직이에요
매 렌더링마다 로직이 실행되도록 deps를 없앴어요

2023-08-23 09:51 UTC, 2Junsu commented on src/components/Header/SubHeader/SubHeader.style.js
> +	}
버튼 너비를 늘리게 되면 border-bottom이 너무 길어져서 결국 li의 너비만 늘려야합니다.

이렇게 하면 li 주변 공간에 호버했을 때도 서브 메뉴가 보이게 되어 좋을 수 있지만, 그 중 버튼 범위 내에서만 pointer cursor가 되고 그 외의 li에는 일반 cursor가 됩니다.
즉, 서브 메뉴가 보이는 동안 특정 범위에서는 포인터, 그 외에는 일반 커서로 변합니다.

이를 해결하기 위해 cursor: pointer;를 li에 걸어버리면 헤더와 서브 헤더 사이 여백에서도 pointer cursor가 되어버립니다.

차라리 버튼에 좌우 패딩 8px을 설정하여 호버 범위를 조금만 넓히는 게 어떨까요?

2023-08-23 12:04 UTC, 2Junsu commented on src/components/Header/SubHeader/SubHeader.jsx
> +			  ];
이 부분은 잘 이해가 가지 않는데 혹시 어떤 의도로 작성하셨는지 알 수 있을까요,,??

2023-08-23 16:58 UTC, sikkzz commented on src/components/Header/SubHeader/SubHeader.jsx
> +						<li key={idx}>
key값이 문제여서 eslint 주석 추가한거라면 idx 삭제하고 title로 사용하는건 안될까요?

2023-08-23 16:58 UTC, sikkzz commented on src/components/Notification/NotificationDropdown/NotificationDropdown.style.js
> +export const BackdropDiv = styled.div`
BackdropDiv ProfileDropDown이랑 동일한거 같은데 공통으로 만들어서 사용할 곳이 없을까요?

2023-08-23 16:58 UTC, sikkzz commented on src/components/Notification/NotificationItem/NotificationItem.style.js
> +	font-style: normal;
font-style: normal 삭제해도 괜찮을 거 같습니다.

2023-08-23 17:04 UTC, 2Junsu commented on src/components/Notification/NotificationDropdown/NotificationDropdown.style.js
> +export const BackdropDiv = styled.div`
지수님과 상의하여 dropdown Backdrop을 없애기로 해서 이 부분은 삭제했습니다!

2023-08-23 17:04 UTC, 2Junsu commented on src/components/Header/SubHeader/SubHeader.jsx
> +						<li key={idx}>
title이 고유한 값이니 그렇게 해도 되겠네요

2023-08-24 01:07 UTC, kimyoungyin commented on src/components/Header/SubHeader/SubHeader.jsx
> +			  ];
```js
const getListItems = ( tab ) =>
		tab === "schedule"
			? [
					{ path: "/", title: "개인일정" },
					{ path: "/share", title: "공유일정" },
			  ]
			: [
					{ path: "/community", title: "홈" },
					{ path: null, title: "알림" },
					{ path: "/mypage", title: "마이페이지" },
			  ];


const SubHeader = () => {
// ...
 return <div>getItems(tab)</div>
}
```
포맷임 많이 생략해서 안 예쁘긴 한데 대충 이런 느낌이요!

2023-08-24 09:43 UTC, 2Junsu commented on src/components/Header/SubHeader/SubHeader.jsx
> +			  ];
아하 아니면 함수 말고 그냥 아래처럼 사용하면 어떨까요?
```js
const listItems =
		tab === "schedule"
			? [
					{ path: "/", title: "개인일정" },
					{ path: "/share", title: "공유일정" },
			  ]
			: [
					{ path: "/community", title: "홈" },
					{ path: null, title: "알림" },
					{ path: "/mypage", title: "마이페이지" },
			  ];
```

2023-08-24 23:53 UTC, kimyoungyin commented on src/components/Header/SubHeader/SubHeader.jsx
> +			  ];
이렇게 사용하면 컴포넌트 안에 들어가서 리렌더링 시에 재선언되지 않을까요?

2023-08-25 00:16 UTC, kimyoungyin requested changes

2023-08-25 00:16 UTC, kimyoungyin commented on src/pages/SettingPage/SettingPage.jsx
> +	const { user } = useSelector((state) => state.user);
전반적인 인증에 관련된 slice인데 `userSlice` 말고 `authSlice`는 어떨까요? 
`user.user`하니까 어색한 것 같아요. 혼동되기도 하고

2023-08-25 00:16 UTC, kimyoungyin commented on src/pages/SettingPage/SettingPage.jsx
파일명이랑 경로만 변경한거고, material ui는 나중에 제거할 예정인가요?

2023-08-25 00:16 UTC, kimyoungyin commented on src/pages/FeedPage.jsx
>  };
컨벤션 상 return문 밖에 없으면 중괄호 생략하는 게 좋을 것 같아요

2023-08-25 00:16 UTC, kimyoungyin commented on src/components/Header/Header/Header.styles.js
> +		margin-right: 4px;
margin 말고 부모에 gap을 주는 건 어떠세요?

2023-08-25 00:25 UTC, kimyoungyin commented on src/components/Header/Header/Header.jsx
> +							<SubHeader tab="feed" />
SubHeader를 두 번 쓰신 이유가 있을까요? 좀더 상위에 한 번만 선언하기 힘들었나요?

2023-08-25 04:39 UTC, 2Junsu commented on src/components/Header/SubHeader/SubHeader.jsx
> +			  ];
Header는 어느 페이지에서든 항상 고정으로 보여지니까 SubHeader가 리렌더링 되는 때는 새로고침 할 때 말고 없다고 생각하는데, 혹시 제가 잘못 알고 있는 걸까요??

2023-08-25 04:43 UTC, 2Junsu commented on src/pages/SettingPage/SettingPage.jsx
네 내부 로직을 본 게 아니라 단순히 설정 페이지라는 명칭이 쓰여서 rename만 했어요!

2023-08-25 05:53 UTC, 2Junsu commented on src/components/Header/Header/Header.jsx
> +							<SubHeader tab="feed" />
보통 이렇게 li 내에 구현하는 것 같더라고요!
그리고 상위에 한 번만 선언하려면 tab을 state로 관리해서 각 TabButton에 onMouseEnter로 setState 해주는 방법이 생각나는데, 이것보다는 기존 방법이 좀 더 간편하다고 생각이 드네요

2023-08-25 11:00 UTC, sikkzz approved these changes

2023-08-26 10:40 UTC, sikkzz approved these changes, later dismissed

2023-08-28 00:23 UTC, kimyoungyin commented on src/components/Header/Header/Header.jsx
> +							<SubHeader tab="feed" />
넵 알겠습니다!

2023-08-28 00:23 UTC, kimyoungyin submitted a review, later dismissed

2023-08-28 08:40 UTC, kimyoungyin approved these changes
변경 감사합니다!

2023-08-28 12:38 UTC, sikkzz approved these changes

2023-08-28 15:05 UTC, merged