126 front task 로그인 및 회원가입 페이지 디자인 수정
Selody-project/Frontend pull request #127
Opened 2023-08-25 02:43 UTC by 2Junsu

# 설명

- #126 
- color, font-weight에 디자인 시스템 적용
- login form을 컴포넌트로 분리

# 테스트

-

# Demo
![스크린샷 2023-08-25 오전 11 40 45](https://github.com/Selody-project/Frontend/assets/77619905/0d17a567-1629-4ad4-a6b8-7cff75cca98b)

![스크린샷 2023-08-25 오전 11 41 07](https://github.com/Selody-project/Frontend/assets/77619905/3bd38548-4242-4d7d-ab88-13b198ffc86c)

2023-08-26 11:26 UTC, sikkzz approved these changes, later dismissed

2023-08-26 14:15 UTC, kimyoungyin approved these changes, later dismissed
감사합니다!

2023-08-28 08:56 UTC, kimyoungyin reviewed
혹시 회원가입이나 로그인 중 잘못된 Input을 발견하면 그 쪽으로 focus가 옮겨지게 하는 건 어떠세요?

2023-08-28 09:43 UTC, 2Junsu commented
> 혹시 회원가입이나 로그인 중 잘못된 Input을 발견하면 그 쪽으로 focus가 옮겨지게 하는 건 어떠세요?

우선 회원가입의 경우, 버튼이 활성화 됐을 때 잘못된 input이 나오는 케이스가
1. 비밀번호가 10자 미만일 때
2. 비밀번호와 비밀번호 확인란이 일치하지 않을 때

위 2가지인데, 이때는 처리할 수 있을 것 같고요

지금 로그인 api가 이메일, 비밀번호 중 뭐가 틀리든 Invalid User ID/Password라고 떠서, 이 부분은 백엔드 분들과 같이 의논해봐야 할 거 같아요

내일 회의 때 얘기해보고 정하시죠!

2023-08-28 12:37 UTC, sikkzz submitted a review, later dismissed

2023-08-31 11:46 UTC, sikkzz commented on src/components/Login/LoginForm/LoginForm.style.js
>  	font-size: 16px;
font-size 16px default 값이라 지워도 괜찮지 않을까요?

2023-08-31 11:46 UTC, sikkzz commented on src/components/SignUp/SignUpForm/SignUpForm.style.js
>  	font-size: 16px;
여기도 동일한거 같습니다!

2023-08-31 11:46 UTC, sikkzz commented
기능은 정상적으로 돌아가는거 확인 했습니다!

2023-09-01 10:50 UTC, sikkzz submitted a review, later dismissed

2023-09-06 13:12 UTC, kimyoungyin requested changes
감사합니다! 발견한 에러 관련 코멘트도 작성해두었어요

2023-09-06 13:12 UTC, kimyoungyin commented on src/pages/LoginPage/LoginPage.jsx
여기서 치명적인 에러가 있습니다. 변경된 히스토리에는 없는데,
user-slice의 extraReducer의 login.fulfilled 부분을 확인해보면, state.user는 객체 형태여야 하는데 nickname으로 처리해버립니다.

그래서 extraReducer를 포함한 코드 수정이 필요해 보입니다.

제가 발견한 건 2가지인데,
1. (이건 에러인지 모르겠지만) 로그인 된 상태면 랜딩 페이지 접근이 불가해야 하지 않나
2. 랜딩 페이지에서 로그인 버튼을 누르면, 로그인한 유저의 경우 
바로 redirect되는데, 이 과정에서는 state.user가 user 객체를 정상적으로 할당 받아서 toast에서 object.object님! 이렇게 뜹니다
<img width="1405" alt="스크린샷 2023-09-06 오후 9 36 43" src="https://github.com/Selody-project/Frontend/assets/78777345/e6876786-7126-4db2-a6b5-e9b0bbadd42b">

확인 한 번 부탁드려요

2023-09-06 13:12 UTC, kimyoungyin commented on src/components/Login/LoginForm/LoginForm.jsx
> +	const dispatchFn = useDispatch();
이거 보통 `dispatchFn`이라고 많이 선언하나요? 저는 그냥 `dispatch`로 진행하는 편인데 통일하는게 나아보이네요. 어떤 걸로 갈까요?

2023-09-06 13:12 UTC, kimyoungyin commented on src/components/Login/LoginForm/LoginForm.jsx
> +		}
이 부분처럼 어떨 때는 `thunk`의 결과에 따라 보여줄 `toast`를 컴포넌트 안에서 결정할 때도 있고, `extraReducer`에서 결정할 때도 있는 것 같은데, 두 선언 위치를 구분할 확실한 이유가 있다면 설명 부탁드려도 괜찮을까요?

그게 없다면, `extraReducer`로 위치를 통일시키는게 좋을 것 같습니다! 부득이한 경우에만 `unwrap()` 처리해서 컴포넌트 내부에서 처리하면 될 것 같아요

2023-09-06 13:12 UTC, kimyoungyin commented on src/components/Login/LoginForm/LoginForm.jsx
> +				/>
InputContainerDiv에 onChange 하나만 걸어주면 아래 두 번 적어줄 필요 없지 않을까요?

2023-09-06 13:12 UTC, kimyoungyin commented on src/components/Login/LoginForm/LoginForm.style.js
form이 틀렸을 때 input 색깔이 변경되도록 지수님하고 얘기 나눠보는 건 어떠세요?

2023-09-06 13:12 UTC, kimyoungyin commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
> +	const isEmailValid = () => {
함수니까 동사형으로 변경하는게 좋을 것 같습니다
`validateEmail`과 같이요

2023-09-06 13:12 UTC, kimyoungyin commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
>  			validateDuplication({ type, targetValue }),
저는 전역 `state`의 변경이 필요한, 즉 `extraReducer`나 다른 전역 `state`가 필요한 경우에만 `thunk`를 생성했었는데
이 경우에는 그렇게 쓰이지는 않음에도 `thunk`로 만든 후 `dispatch`되고 있네요?

보통 이렇게도 하는 편인가요? 그냥 순수한 비동기 로직인데 `thunk`와 `dispatch`로 진행할 필요가 있을까요?

2023-09-06 13:12 UTC, kimyoungyin commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
>  			validateDuplication({ type, targetValue }),
에러 처리는 어떻게 진행되나요? 현재는 그냥 rejectWithValue로 뱉어내긴 하는데 쓰이진 않네요?

2023-09-06 13:12 UTC, kimyoungyin commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
>  		}
비밀번호에 대한 validate로 국한되니까 `validatePassword`와 같이 조금더 구체적으로 명명하면 좋을 것 같아요!

2023-09-06 13:12 UTC, kimyoungyin commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
컴포넌트들이 겹치는 부분이 많은 것 같아서 객체 배열로 속성들을 모은 후 map 처리하는 건 어떨까 고민되네요..
이대로 가도 가독성은 나쁘지 않은데 어떠세요?

2023-09-06 13:12 UTC, kimyoungyin commented on src/pages/LoginPage/LoginPage.jsx
>  			toast.success(`안녕하세요! ${user}님`);
object.object님 안녕하세요!라 뜨는 경우 위에서 설명 참고!

2023-09-06 13:13 UTC, kimyoungyin commented on src/components/Login/LoginForm/LoginForm.jsx
> +	const dispatchFn = useDispatch();
이것도 컨벤션에 추가해볼까요?

2023-09-07 08:25 UTC, sikkzz commented on src/components/Login/LoginForm/LoginForm.jsx
> +	const dispatchFn = useDispatch();
저는 과거 코드들이 dispatchFn으로 적혀있어서 그렇게 작성은 되어있는데 평소에는 저도 dispatch로 썼었어요! 논의해보고 편한 방향으로 사용하면 될 거 같습니다

2023-09-07 17:01 UTC, 2Junsu commented on src/components/Login/LoginForm/LoginForm.jsx
> +	const dispatchFn = useDispatch();
저도 dispatch라고 썼었는데 여기에 dispatchFn으로 적혀있는 걸 간과했네요

2023-09-07 17:08 UTC, 2Junsu commented on src/components/Login/LoginForm/LoginForm.jsx
> +		}
extraReducer에서 처리하는 게 좋을 것 같네요!

2023-09-07 17:50 UTC, 2Junsu commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
>  			validateDuplication({ type, targetValue }),
api 통신 로직을 분리하려고 thunk를 사용했습니다!
thunk 사용해보는 게 처음이라 잘 몰라서.. thunk를 쓴다면 checkDuplication 내에 있는 toast 메시지 부분을 extraReducer로 옮겨서 에러 처리도 같이 할 생각인데요
만약 thunk를 쓰지 않는다면 이럴 경우에는 api 통신 로직을 어떻게 쓰나요? 훅을 만들어서 쓰나요?

2023-09-07 18:10 UTC, 2Junsu commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
아래처럼 해봤는데 괜찮으신가요? @sikkzz  @kimyoungyin 
```js
const inputObjList = [
	{
		key: "email",
		label: "아이디 (이메일)",
		testid: "email-input",
		type: "email",
		placeholder: "이메일을 입력해주세요.",
		hasButton: true,
	},
	{
		key: "nickname",
		label: "어떤 이름을 사용하시겠어요?",
		testid: "nickname-input",
		type: "text",
		placeholder: "닉네임을 설정해주세요.",
		hasButton: true,
	},
	{
		key: "password",
		label: "비밀번호",
		testid: "password-input",
		type: "password",
		placeholder: "비밀번호를 설정해주세요.",
		hasButton: false,
	},
	{
		key: "passwordCheck",
		label: "비밀번호 확인",
		testid: "password-check-input",
		type: "password",
		placeholder: "비밀번호를 다시 입력해주세요.",
		hasButton: false,
	},
];
```
```js
{
	inputObjList.map(
		({ key, label, testid, type, placeholder, hasButton }, idx) => (
			<InputContainerDiv key={key}>
				<label htmlFor={key}>{label}</label>
				<InputInnerDiv>
					<Input
						ref={(el) => (signUpRef.current[idx] = el)}
						data-testid={testid}
						type={type}
						id={key}
						name={key}
						value={formValue[key]}
						onChange={handleFormValue}
						placeholder={placeholder}
					/>
					{hasButton && (
						<DuplicateCheckButton
							data-testid={`${key}-duplicate-check-button`}
							type="button"
							disabled={key === "email" ? !validateEmail() : nickname === ""}
							isActive={key === "email" ? validateEmail() : nickname !== ""}
							onClick={() => checkDuplication(key)}
						>
							중복확인
						</DuplicateCheckButton>
					)}
				</InputInnerDiv>
			</InputContainerDiv>
		),
	);
}
```

2023-09-07 18:44 UTC, 2Junsu commented on src/pages/LoginPage/LoginPage.jsx
- 로그인 된 경우 랜딩, 로그인, 회원가입 페이지에 접근하지 못 하도록 PublicRoute를 추가했습니다.
- 로그아웃 시에 랜딩이 아닌 로그인 페이지로 이동하게 되는데, 이는 네이버 로그인 브랜치 작업내용과 합쳐지면 정상 작동합니다.
  - 네이버 로그인 브랜치에서 로그아웃 함수를 수정했습니다.
- 또한 로그인과 회원가입 시에 user에 email, nickname 등을 담는 객체를 할당받도록 수정했습니다.

2023-09-08 08:40 UTC, sikkzz commented on src/components/Login/LoginForm/LoginForm.jsx
> +	const dispatchFn = useDispatch();
확인했습니다 저도 코드 다 dispatch 수정할게요

2023-09-08 08:45 UTC, kimyoungyin commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
>  			validateDuplication({ type, targetValue }),
api 통신 로직을 분리하는 목적이라면 다른 파일에 분리하는 것까지는 OK인데, 
thunk로 사용하는 것은 비동기 작업에 의한 전역 state 변화를 extraReducer를 통해 편리하게 관리하기 위함으로 알고 있습니다.
분리하되 그냥 비동기 함수, 혹은 hook으로 분리해도 좋을 것 같아요!

2023-09-08 08:50 UTC, sikkzz commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
네 저는 가독성 훨씬 좋은 거 같아서 괜찮습니다!

2023-09-09 14:43 UTC, kimyoungyin commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
좋네요! 객체에 연결된 state도 없어서 컴포넌트 밖으로 빼도 되겠는데요?

2023-09-10 13:49 UTC, kimyoungyin commented on src/components/Login/LoginForm/LoginForm.jsx
> +		}
완료되면 말씀 한 번 부탁드릴게요 바로 확인해보겠습니다

2023-09-12 01:20 UTC, kimyoungyin requested changes

2023-09-12 01:20 UTC, kimyoungyin commented on src/pages/PublicRoute.jsx
> +		navigate("/");
아래 `<Navigate />`가 있는데 useNaviate까지 필요한 이유가 있을까요?

2023-09-12 01:20 UTC, kimyoungyin commented on src/components/Login/LoginForm/LoginForm.jsx
> +	const validate = () => {
`validateForm`은 어떠세요?

2023-09-12 01:20 UTC, kimyoungyin commented on src/components/Login/LoginForm/LoginForm.jsx
> +				</EmailSaveLabel>
이메일 저장 로직은 없는 것 같은데 구현을 어떻게 하실 생각인가요?

2023-09-12 01:20 UTC, kimyoungyin commented on src/features/auth/auth-slice.js
> +					state.user = { email, nickname, userId, provider, snsId };
혹시 모르니까
`singup` thunk에서 email, nickname, username, userId, provider, snsId가 있는지 체크하고 없는 게 있다면 `catch`문으로 보내는게 어떠세요?

2023-09-12 01:20 UTC, kimyoungyin commented on src/features/auth/auth-slice.js
> +					state.isLoading = false;
`login` thunk도 마찬가지..?

2023-09-12 01:20 UTC, kimyoungyin commented on src/hooks/useAxios.js
> +		baseURL: "/back",
`baserURL`을 "/back"으로 하신 이유가 있을까요?

2023-09-12 01:20 UTC, kimyoungyin commented on src/hooks/useAxios.js
> +	const customAxios = axios.create({
`customAxios`는 hook 밖으로 빼도 될 것 같습니다

2023-09-12 01:20 UTC, kimyoungyin commented on src/hooks/useAxios.js
`useAxios` hook을 만든 이유를 알 수 있을까요?
저는 customAxios만 만들어두고 거기에 interceptor를 달거나 하는 식으로 설정해놓은 뒤 재사용하는 선에서 그쳤는데, 이렇게 했을 때 얻는 장점이 뭔지 와닿지 않아서 설명 부탁드립니다!

2023-09-12 08:11 UTC, 2Junsu commented on src/features/auth/auth-slice.js
> +					state.user = { email, nickname, userId, provider, snsId };
그럴 경우가 발생 가능한 건지와 가능하다면 로그인이 성공했다고 넘어오는지 여쭤봐야 할 것 같네요

2023-09-12 08:11 UTC, 2Junsu commented on src/hooks/useAxios.js
> +		baseURL: "/back",
기존 BaseAxios를 그대로 가져왔습니다! vite.config.js에서 /back으로 설정해두었더라고요

2023-09-12 08:39 UTC, 2Junsu commented on src/hooks/useAxios.js
커스텀훅에 익숙치 않아서 생각이랑 구현이 좀 다르게 된 것 같네요.. interceptor를 사용해서 아래처럼 수정해봤습니다
커스텀훅 사용이 확정되면 BaseAxios에서 불러쓰던 customFetch를 useAxios의 customAxios로 대체하는 게 좋을 것 같아요
```js
import { useState } from "react";

import axios from "axios";

const customAxios = axios.create({
	baseURL: "/back",
	withCredentials: true,
});

const useAxios = () => {
	const [loading, setLoading] = useState(false);

	const requestHandler = (config) => {
		setLoading(true);
		return config;
	};

	const responseHandler = (response) => {
		setLoading(false);
		return response;
	};

	const errorHandler = (error) => {
		setLoading(false);
		return error;
	};

	customAxios.interceptors.request.use(
		(config) => requestHandler(config),
		(error) => errorHandler(error),
	);

	customAxios.interceptors.response.use(
		(response) => responseHandler(response),
		(error) => errorHandler(error),
	);

	return [customAxios, loading];
};

export default useAxios;
```

2023-09-12 08:40 UTC, 2Junsu commented on src/components/Login/LoginForm/LoginForm.jsx
> +				</EmailSaveLabel>
아 깜빡하고 있었네요,, react-cookie 라이브러리 써서 쿠키에 저장할 생각입니다!

2023-09-12 08:52 UTC, kimyoungyin commented on src/hooks/useAxios.js
> +		baseURL: "/back",
아 그렇네요 알겠습니다! 프록시로 "/"로 변경해주는 작업이 들어가나 보군요

2023-09-20 02:11 UTC, kimyoungyin requested changes

2023-09-20 02:11 UTC, kimyoungyin commented on src/hooks/useAxios.js
1. 위와 같이 변경했을 경우에는 `useAxios` 훅이 호출될 때마다 인터셉터가 수정되겠네요? 아마 인터셉터 안에 `loading` state를 넣으려고 하신 거 같네요
현재 상태에서는 `interceptor`를 수정하지 못하는데, 그래서 저는 아예 두 종류의 `axios`로 나눠 하는 방식으로 진행했었습니다. 그런데 기존 코드를 유지한다면,  다른 `interceptor` 기능을 추가할 수 있습니다. 제 경험으로는 대략 2가지가 있는데
    - 인증: 회원/비회원(우리가 체크 필요) 
    - 토큰 재발급(우린 아님)

    그러니 `useAxios`에서 추가해야 하는 기능은 다음과 같습니다. `loading` 처리를 내부에서 했듯이 아래처럼 하면 중복되는 코드를 제거하기 쉬울 거에요.
    - `auth-slice`에서 `user` 객체를 가져온다
    - parameter로 `isAuthRequired` 불리언 값(default value는 `false`)을 받아와서 해당 값이 `true`이면 `Request interceptor`에서 인증되었는지 확인 후 진행한다.

2. 변수명 수정
    - ~handler => handle
    - loading => isLoading

2023-09-20 02:11 UTC, kimyoungyin commented on src/components/Login/LoginForm/LoginForm.jsx
> +	const [isRemember, setIsRemember] = useState(!!getCookie("isRememberEmail"));
isRemberEmail이 더 정확하지 않을까요?

2023-09-20 02:11 UTC, kimyoungyin commented on src/components/Login/LoginForm/LoginForm.jsx
> +	}, [isRemember]);
이 부분을 굳이 `useEffect`를 쓰지말고, checkbox onChange 핸들러에서 작성하면 되지 않을까요?
'가능하다면' `useEffect` 사용을 최대한 지양하는 게 좋습니다! 이 코드 자체도 간단하니까요

2023-09-20 02:11 UTC, kimyoungyin commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
> +	const [customAxios] = useAxios();
여기서는 loading state를 사용하지 않는데 customFetch를 사용하면 되지 않을까요?

인터셉터 때문이면 어쩔 수 없지만요..

2023-09-20 02:11 UTC, kimyoungyin commented on src/features/auth/auth-service.js
여기도 이어서요, 굳이 비동기 작업이 확실하고 loading state를 커스텀 훅 내부에서 선언한 걸로 사용하지 않는데 굳이 customAxios가 필요할까 싶습니다. (물론 이것도 인터셉터 때문이면 어쩔 수 없긴 합니다..)

그런데 customFetch는 로그인 여부를 판단하지 않고 그냥 public 요청시에 사용하는 걸까요?

2023-09-20 02:11 UTC, kimyoungyin commented on src/features/auth/auth-slice.js
> +	userLoading: false,
- `userLoading`
  - 이 로딩과 isLoading과의 차이가 궁금합니다
  - 동사형의 다른 변수명이 필요하지 않을까요? `isUserLoading`? `isUserComing`? 과 같이요 
- 여기 `isLoading`과, `customAxios`의 `isLoading`의 용도는 어떻게 구분될까요? 여기 `isLoading`은 `auth-slice`에 속해있는 이유가 인증관련 비동기 작업과 연결된 것이라 그렇게 나눠 놓은 것으로 이해하긴 했습니다.
  - 전역으로 `loading` state를 빼면서 얻는 이점은 `thunk`와의 연결인가요?

2023-09-28 07:16 UTC, 2Junsu commented on src/features/auth/auth-slice.js
> +	userLoading: false,
- userLoading은 없애도 될 것 같아요
---
useAxios의 isLoading은 리덕스를 사용하지 않는 api(ex: 중복체크 api)를 위한 거고, 리덕스의 isLoading은 그 반대의 경우예요
사실 useAxios를 만든 이유는 이를 customFetch + α로 만들어서 기존 customFetch를 전부 useAxios로 대체하고 싶어서였어요.
그런데 useAxios 내에는 리액트 훅이 들어가기 때문에 createAsynkThunk 내에서는 사용 불가하고, 따라서 리덕스를 사용하지 않는 중복 체크 api와 같은 것들에만 사용할 수 있겠더라고요.

그래서 useAxios 훅을 만들어도 리덕스를 사용하지 않는 api에만 사용이 가능해서 사용할 곳이 많진 않아보이지만, 그래도 로직 분리를 위해 만들면 좋을 것 같다고 생각했어요(공부 차원에서도)

아래는 제가 다른 곳에서 사용 중인 useAxios 훅인데, 저기에서 토큰 관련 코드 없애고 사용하면 어떨까요?
axiosInstance는 customAxios로 이름 바꾼 후에 export 가능하게 해서 thunk 내에서 customFetch 대신 불러다 쓸 수 있게 하면 좋을 것 같아요(이름 통일성 면에서)
```js
const { response, error, isLoading, refetch } = useAxios({url: "", method: "POST"})
```
```js
import { useEffect, useState } from "react";

import axios, { AxiosRequestConfig, AxiosResponse, AxiosError } from "axios";

const axiosInstance = axios.create({
	baseURL: "",
	timeout: 3000,
	withCredentials: true,
});

const errorHandler = (e: AxiosError) => Promise.reject(e);

axiosInstance.interceptors.request.use(
	(config) => {
		const accessToken = "token";
		if (accessToken) {
			config.headers.Authorization = accessToken;
		}
		return config;
	},
	(error) => errorHandler(error),
);

axiosInstance.interceptors.response.use(
	(response) => response,
	(error) => errorHandler(error),
);

export const useAxios = (axiosParams: AxiosRequestConfig) => {
	const [response, setResponse] = useState<AxiosResponse>();
	const [error, setError] = useState<AxiosError | unknown>();
	const [isLoading, setIsLoading] = useState(false);
	const [trigger, setTrigger] = useState(0);

	const refetch = () => {
		setResponse(response);
		setError(error);
		setIsLoading(true);
		setTrigger(Date.now());
	};

	const axiosData = async (params: AxiosRequestConfig) => {
		try {
			setIsLoading(true);
			const result = await axiosInstance.request({ ...params });
			setResponse(result);
		} catch (error: AxiosError | unknown) {
			setError(error);
			setIsLoading(false);
		} finally {
			setIsLoading(false);
		}
	};

	useEffect(() => {
		axiosData(axiosParams);
	}, [trigger]);

	return {
		response,
		error,
		isLoading,
		refetch,
	};
};

```

2023-09-28 07:18 UTC, 2Junsu commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
> +	const [customAxios] = useAxios();
사실 api 중복 요청 방지를 위해 loading state를 전부 쓰긴 해야할 것 같네요..

2023-09-28 07:21 UTC, 2Junsu commented on src/features/auth/auth-service.js
서버에서 토큰 검증할 때 유효하지 않으면 로그인 만료라고 판단하여 에러 메시지를 반환해야하지 않을까요? 프론트에선 어떻게 검증하나요?

2023-10-17 01:12 UTC, kimyoungyin commented on src/features/auth/auth-slice.js
> +	userLoading: false,
좋은 것 같습니다! useAxios를 state와 관련 없는 비동기 작업에만 적용하는 것으로 분리하는 건 좋아보이네요.

수정 및 리팩토링 요청 사항은
- `userLoading` 삭제 요청
- `trigger`도 필요 없겠죠?, `refetch`제거
- catch문에서 `setIsLoading` 제거: 어차피 finally에서 호출됩니다
- `request({ ...params })`에서 `request(params)`로: spread 쓸 필요 없어보이네요
- `axiosData` -> 동사형으로 변경 부탁

2023-10-17 01:17 UTC, kimyoungyin commented on src/hooks/useAxios.js
이 부분은 밑에 준수님이 가져오신 useAxios에 제가 남긴 리뷰 기반으로 변경시켜서 적용하면 좋을 것 같아요! 굳이 Interceptor를 훅 안에서 쓸 이유는 없어보입니다

2023-10-17 01:20 UTC, kimyoungyin commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
> +	const [customAxios] = useAxios();
이 부분도 아래 작성해주신 customAxios를 반영해서 쓰면 좋겠네요. 이 훅 안에서 loading state를 쓰니까 true라면 input 작성과 submit 버튼을 비활성시켜주면 좋겠습니다.

2023-10-17 01:23 UTC, kimyoungyin commented on src/features/auth/auth-service.js
response interceptor에만 토큰 검증 코드 추가하면 좋을 것 같습니다. 어차피 로그아웃 처리할 거니까 미리 걸러주는 거죠!

2023-10-26 13:42 UTC, 2Junsu commented on src/features/auth/auth-slice.js
> +	userLoading: false,
refetch는 데이터를 다시 불러올 때 필요해서 있어야 할 것 같습니다!

2023-11-02 07:33 UTC, kimyoungyin commented on __test__/pagesTest/SignUpPage.test.jsx
testId보다 role로 불러오는 게 좋다고 합니다!

2023-11-02 07:47 UTC, kimyoungyin commented on src/hooks/useAxios.js
> +export const customAxios = axios.create({
customAxios는 굳이 useAxios에 둘 필요 없을 것 같지 않을까요?
customAxios랑 인터셉터 부분은 따로 파일 파서 두면 편할 것 같습니다.
export default 처리해서요!

2023-11-02 07:47 UTC, kimyoungyin commented on src/hooks/useAxios.js
> +	const refetchWithParams = (params) => {
`setAxiosParams(prev => ({...prev, ...params}))` 처리하는 건 어떠세요?

아무래도 `useAxios` 훅 하나의 response는 모두 관련된 request에서 올텐데 중복된 params를 또 적어줄 필요가 있을까 싶어서요

어떻게 생각하시나요?

2023-11-10 07:01 UTC, kimyoungyin requested changes

2023-11-10 07:01 UTC, kimyoungyin commented on src/features/auth/auth-service.js
> +			return thunkAPI.rejectWithValue(error);
commonThunk 처리 여기서도 부탁드립니다!

2023-11-10 07:01 UTC, kimyoungyin commented on __test__/pagesTest/SignUpPage.test.jsx
갑사합니다! 추가로 `fireEvent` -> `userEvent`로 변경 가능할까요?
기능적인 테스트라 `fireEvent`는 적절하지 않아 보입니다
[관련 링크](https://velog.io/@pds0309/react-testing-library-fireEvent-vs-userEvent)

2023-11-10 07:01 UTC, kimyoungyin commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
> +				setIsFirstAxiosCalled(true);
이 부분 혹시 간단히 설명 부탁드려도 괜찮을까요?
- (한 번 마운트 된 이후 또 다시 업데이트 되었을 때 && refetch 완료 시) 실행되는 로직같은데 맞나요?

2023-11-16 06:41 UTC, 2Junsu commented on src/features/auth/auth-service.js
> +			return thunkAPI.rejectWithValue(error);
#134 
위 브랜치에서 작업해놔서 나중에 합치겠습니다!

2023-11-16 06:41 UTC, 2Junsu commented on src/components/SignUp/SignUpForm/SignUpForm.jsx
> +				setIsFirstAxiosCalled(true);
네 맞아요! 처음 마운트 될 때 `지원하지 않는 형식의 데이터입니다` 라는 문구가 떠서 이걸 안 보이게 하려고 했습니다.
```js
const { response, isLoading, refetchWithParams } = useAxios({
		url: "/api/auth/join",
		method: "POST",
	});
```
커스텀훅이 호출될 때 body에 빈값을 보내서 이 페이지가 렌더링되면 처음에 위 문구가 뜨게 되더라고요
이를 없애기 위해서 `isMounted`, `isFirstAxiosCalled`를 사용했습니다.

2023-11-20 09:26 UTC, sikkzz requested changes

2023-11-20 09:26 UTC, sikkzz commented on src/components/SignUp/SignUpForm/SignUpForm.style.js
> +	}
LoginForm.styles.js의 Input 스타일이랑 disabled제외 아예 동일해보입니다. 다만 이 코드 제외 동일한게 없어서 따로 빼서 공통으로 사용하는게 좋은 방향일지는 잘 모르겠네요. 어떤거 같으세요?

2023-11-20 09:26 UTC, sikkzz commented on src/pages/LoginPage/LoginPage.styles.js
theme 코드가 형식이 다른 부분들이 있어요. 통일하는게 좋을 거 같네요

2023-11-20 09:26 UTC, sikkzz commented on src/pages/PublicRoute.jsx
Public Route와 Root를 하나로 합칠 방법은 없을까요? 없다면 두개의 파일 이름을 조금 더 직관적인 name으로 바꾸면 좋을 거 같아요. 제가 확인해보면 Header가 들어가냐 안들어가냐의 차이 같은데 맞을까요?

2023-11-20 09:26 UTC, sikkzz commented on src/pages/SignUpPage/SignUpPage.styles.js
ContainerDiv padding: 80px 80px 0으로 변경 가능할 거 같아요

2023-11-20 09:26 UTC, sikkzz commented on src/pages/SignUpPage/SignUpPage.styles.js
> +	font-weight: ${({ theme }) => theme.typography.weight.bold};
위에 리뷰에서도 달았었는데 혹시 이유가 있어서 colors와 형식을 다르게 사용하는 걸까요?

2023-11-20 09:26 UTC, sikkzz commented on src/pages/SignUpPage/SignUpPage.styles.js
> +		color: ${(props) => props.theme.colors.primary};
코드 형식 통일

2023-11-25 12:12 UTC, sikkzz approved these changes, later dismissed

2023-11-25 12:14 UTC, sikkzz approved these changes

2023-11-25 12:16 UTC, sikkzz approved these changes

2023-11-25 12:19 UTC, merged