124 front task 개인 일정 페이지 달력 보기 메뉴
Selody-project/Frontend pull request #128
Opened 2023-08-25 09:09 UTC by kimyoungyin

# 설명
- #124 
<img width="259" alt="스크린샷 2023-08-25 오후 6 06 56" src="https://github.com/Selody-project/Frontend/assets/78777345/eaa7a3d7-a37d-43a6-a04c-e263ffeaa55f">

> 기존 코드 수정 + FullCalendar 모듈 공부 + 년월일 계산 로직 등이 겹쳐 작업이 오래 걸렸습니다 죄송합니다.

- title 제거 및 커스텀 select로 타이틀 대체
- `currentWeek` state: 기존 년, 월 `state`에 `currentWeek`를 추가하여 리스트 보기 시 타이틀(`select`)에 "몇 주차" 인지 확인할 수 있게 하였으며, 선택할 때마다 캘린더와 select value가 동일시되도록 바인딩하였습니다.
    -  `getCurrentWeek`으로 현재 주차를 계산해 initialize합니다.
    - 캘린더가 변경된 이후 state도 뒤따라 변경합니다.

- `currentView` state: 현재 보기 모드가 monthly or weekly인지 판단하여 `select`와 `option` 포맷을 바꿔줍니다
- `TitleSelect` tag: monthly인 경우 ~월, weekly인 경우 각 월마다 몇 주차인지 계산 후 map 처리하여 "~주차"까지 보입니다. 
- `fullCalendar` 조작: `FullCalendar`가 보여주는 년/월/일 데이터는 현재 보이는 화면에 첫 번째 일자 기준이므로,  '년/월이 넘어가는 주에 경우'처럼 여러 경우에 혼동을 야기하여 이 부분을 api로 불러오던 코드 자체를 제거하였습니다
- 화살표 `svg`를 url로 전환 후 `select` background로 옮김

이 외에도 여러가지가 있는데, 더 궁금한 점 있으면 리뷰로 남겨주세요!

2023-08-28 17:21 UTC, 2Junsu requested changes

2023-08-28 17:21 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
>  	const [currentYear, setCurrentYear] = useState(new Date().getFullYear());
종류가 다른 훅들 사이에 공백 하나씩 넣으면 보기 편할 것 같아요!

2023-08-28 17:21 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
> +	const firstSundayOfMonth = firstDateOfWeek.getDay();
firstDateOfWeek는 이달의 첫날에 대한 정보가 나오는데 firstDateOfMonth가 적절하지 않나 생각하고, firstSundayOfMonth는 위 정보에서 요일만 빼오는 거니까 firstDayOfMonth가 적절하지 않나 생각합니다!

2023-08-28 17:21 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
> +	const DayOfWeek = today.getDay(); // 0~6;
날짜는 date라고 명명했으니까 요일도 day라고 수정하면 어떨까요?

2023-08-28 17:21 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
> +	const currentWeekNum = Math.ceil((weekStart - 1) / 7) + 1;
weekStart에서 1은 왜 빼는 건가요?

++ weekStart가 이번 주의 첫 날짜를 나타내는 것 같은데 firstDateOfWeek라고 하면 더 알아보기 쉬울 것 같아요

2023-08-28 17:21 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
> +const getFirstDayOfWeek = (year, month, week) => {
요일이 아닌 며칠인지를 반환하는 함수니까 getFirstDateOfWeek로 수정하는 게 좋을 것 같아요

2023-08-28 17:21 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
> +			const startDay = getFirstDayOfWeek(year, month, week);
여기도 startDate로 바꿔야 할 것 같네요

2023-08-28 17:21 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
>  	};
이 함수를 따로 분리하신 이유가 있나요? 아래 handleDateChange 함수에서 3가지 조건에 따라 로직이 짜여있는데 여기에 setCurrentWeek를 같이 넣는 게 더 낫지 않나 싶습니다. 그리고 month와 year를 set하는 부분은 updateDateState가 놓이는 부분에 배치하면 되지 않을까요? 따로 분리하면 if문 분기를 다시 해야해서 코드가 길어지는 것 같네요.

2023-08-28 17:21 UTC, 2Junsu commented on src/pages/GroupSchedulePage.jsx
> +			<GroupHeader />치
오타가 있네요!

2023-08-28 17:21 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +		return (
return 문 전에 공백 하나 띄어주시면 좋을 것 같아요

2023-08-28 17:21 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +					)}
이 부분 가독성이 너무 떨어져서 보기 편하게 리팩토링하면 좋을 것 같습니다!

2023-08-28 17:21 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.styles.js
> +	background-image: url("data:image/svg+xml,%3Csvg width='12' height='6' viewBox='0 0 14 8' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1L7 7L13 1' stroke='%23121127' stroke-width='
svg 대신 이렇게 하신 이유가 뭔가요??

2023-08-28 17:21 UTC, 2Junsu commented on src/constants/calendar/scheduleType.js
calendarColors와 scheduleType 파일을 각각 만드는 것보다 calendar.js라는 파일 내에 모아놓고, named export 하는 건 어떠신가요?

2023-08-28 17:21 UTC, 2Junsu commented on src/pages/PersonalSchedulePage/PersonalSchedulePage.styles.js
> +	gap: 13px;
GroupSchedulePage 말고 여기에만 gap이 있는데 통일하는 게 좋지 않을까요?

++ 생각해보니 merge하게 되면 개인일정과 공유일정 페이지를 하나로 합칠 수도 있을 것 같아요 차이점이 type 밖에 없네요

2023-08-29 00:33 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
> +	const currentWeekNum = Math.ceil((weekStart - 1) / 7) + 1;
weekStart가 주의 첫 번쨰 월요일이니, 몇 번째 주인지 계산하려면 저 첫 월요일까지 뺴주고 7로 나누면 1일부터 이전 주까지 몇 주인지 계산이 가능합니다!
거기에 +1 을 해야 알고자 했던 날짜의 주차를 얻을 수 있습니다
<img width="197" alt="스크린샷 2023-08-29 오전 9 30 02" src="https://github.com/Selody-project/Frontend/assets/78777345/933368ac-0dea-46d8-a574-0c732c31291d">

2023-08-29 00:43 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
>  	};
함수 하나가 너무 많은 일을 하지 않게 하는 게 중요하다 생각해서 저렇게 나눴습니다!
말씀해주신대로 함수 2개로 나눠지면서 코드가 길어지긴 합니다..
구현하면서 고민해봤던 부분이긴 한데,

함수 하나가 너무 많은 일을 하는 것 vs 코드 길이 길어짐 
중에 전 후자를 선택했는데, 준수님은 전자가 코드 길이도 줄어드니 더 낫다 생각하세요?

2023-08-29 00:45 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
> +	const currentWeekNum = Math.ceil((weekStart - 1) / 7) + 1;
내용 확인되셨으면 resolve해주시면 됩니다. 일단 열어둘게요

코드명은 수정하였습니다

2023-08-29 00:47 UTC, kimyoungyin commented on src/pages/PersonalSchedulePage/PersonalSchedulePage.styles.js
> +	gap: 13px;
groupSchedulePage를 진행할 때 통합할 부분 살펴보려 했습니다. 나중에 해도 괜찮지 않을까요?

2023-08-29 01:17 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.styles.js
> +	background-image: url("data:image/svg+xml,%3Csvg width='12' height='6' viewBox='0 0 14 8' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1L7 7L13 1' stroke='%23121127' stroke-width='
원래 컨테이너에 svg랑 title을 감싸고 svg를 title 바로 옆에 붙이고, svg를 클릭하면 ref로 TItleSelect를 포커스하도록 하려 했는데, 안되더라구요 ㅠㅠ
그래서 그냥 아예 select tag background로 포함시켜보았습니다.

혹시 왜 안되는지 아시거나 구현 가능하시면 말씀해주세요! 알려주시면 정말 감사하겠습니다

2023-08-29 01:34 UTC, kimyoungyin commented on src/constants/calendar/scheduleType.js
calendar.js로 하면 검색 시에 너무 혼동 될 것 같아서, src/constants/calendarConstants.js에 모았습니다. 
괜찮아보이시면 resolve 부탁드려요!

2023-08-29 01:47 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +					)}
이거 리팩토링 하는 김에, 어차피 일정 맞추는 목적이니까 오늘 날짜 기준 그 이후로 select option들을 구성해불까 하는데 어떠세요?

2023-08-29 06:18 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.styles.js
> +	background-image: url("data:image/svg+xml,%3Csvg width='12' height='6' viewBox='0 0 14 8' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1L7 7L13 1' stroke='%23121127' stroke-width='
그러네요.. select dropdown을 직접 제어할 수 없다고 하네요ㅠ dropdown 디자인 시안이 있으면 아예 select를 커스텀해서 쓰면 될 텐데, 시안이 없으니 기존 방법대로 하는 게 좋아보이네요
cursor: pointer만 추가하면 더 좋을 것 같아요

2023-08-29 06:18 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +					)}
이전 날짜는 못 보게 바꾸신다는 말씀이시죠?? 맞다면 기획적인 문제라 회의 때 같이 의논해보면 좋을 것 같아요!

2023-08-29 06:20 UTC, 2Junsu commented on src/pages/PersonalSchedulePage/PersonalSchedulePage.styles.js
> +	gap: 13px;
네 지금 당장은 아니고 나중에라도 합칠 수 있으면 합치는 게 좋을 것 같아요!
지금은 css 통일을 위해서 gap만 없으면 좋을 것 같네요

2023-08-29 06:38 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
>  	};
ㅋㅋㅋ설득당했어요 그럼 updateDateState 함수에 첫 번째 if문도 {}로 묶어주시면 될 것 같아요

2023-08-29 06:39 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +					)}
네 좋습니다!

2023-08-29 06:39 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.styles.js
> +	background-image: url("data:image/svg+xml,%3Csvg width='12' height='6' viewBox='0 0 14 8' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1L7 7L13 1' stroke='%23121127' stroke-width='
네 추가하겠습니다

2023-08-29 06:42 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
>  	};
어 혹시 굳이 중괄호가 필요한 이유가 있을까요? 일관성 떄문일까요?

2023-08-29 06:46 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
>  	};
![스크린샷 2023-08-29 오후 3 46 20](https://github.com/Selody-project/Frontend/assets/77619905/e246ec6e-3ca5-4e58-8951-02724e4695cf)

컨벤션으로 정해놔서요!

2023-08-29 06:47 UTC, kimyoungyin commented on src/pages/PersonalSchedulePage/PersonalSchedulePage.styles.js
> +	gap: 13px;
gap을 없애면 레이아웃이 달라져서 나중에 남겨놔야 될 것 같습니다. 어차피 저 부분 그대로 GroupSchedulePage에 가져다 쓸건데, 해당 브랜치랑 안 맞아서 변경하지 않고 놔둔 겁니다!
어차피 지금 Group쪽이랑 이쪽은 아예 다른 페이지가 되서 굳이 당장 통일할 필요는 없을 것 같은데요?

2023-08-29 06:47 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
>  	};
아 그렇네요 수정하겠습니다!

2023-08-29 06:53 UTC, 2Junsu commented on src/pages/PersonalSchedulePage/PersonalSchedulePage.styles.js
> +	gap: 13px;
아 그런가요? 피그마 시안에는 달력이랑 일정 컨테이너 사이 간격이 좁아서 여기에 gap이 필요 없다고 생각했는데, 레이아웃이 깨지나요?

2023-08-29 08:31 UTC, kimyoungyin commented on src/pages/PersonalSchedulePage/PersonalSchedulePage.styles.js
> +	gap: 13px;
#129
[#129 design: remove margin-right on CalendarContainer](https://github.com/Selody-project/Frontend/commit/796d768674a067ccd602347770f290a3ed95b773)
이 브랜치에서 하위 div의 `margin-right: 2rem`을 제거하는 커밋으로 해결한 상황이라 gap은 지울 필요 없을 것 같습니다.
13px이 딱 피그마 디자인이라서요!
오히려 margin이 예전 분이 하시던 거라 지워야 하는 거더라구요..

2023-08-30 01:59 UTC, kimyoungyin commented
> # 설명
> * [[FRONT-TASK] 개인 일정 페이지-달력 보기 메뉴 #124](https://github.com/Selody-project/Frontend/issues/124)
> 
> <img alt="스크린샷 2023-08-25 오후 6 06 56" width="259" src="https://user-images.githubusercontent.com/78777345/263223983-eaa7a3d7-a37d-43a6-a04c-e263ffeaa55f.png">
> > 기존 코드 수정 + FullCalendar 모듈 공부 + 년월일 계산 로직 등이 겹쳐 작업이 오래 걸렸습니다 죄송합니다.
> 
> * title 제거 및 커스텀 select로 타이틀 대체
> * `currentWeek` state: 기존 년, 월 `state`에 `currentWeek`를 추가하여 리스트 보기 시 타이틀(`select`)에 "몇 주차" 인지 확인할 수 있게 하였으며, 선택할 때마다 캘린더와 select value가 동일시되도록 바인딩하였습니다.
>   
>   * `getCurrentWeek`으로 현재 주차를 계산해 initialize합니다.
>   * 캘린더가 변경된 이후 state도 뒤따라 변경합니다.
> * `currentView` state: 현재 보기 모드가 monthly or weekly인지 판단하여 `select`와 `option` 포맷을 바꿔줍니다
> * `TitleSelect` tag: monthly인 경우 ~월, weekly인 경우 각 월마다 몇 주차인지 계산 후 map 처리하여 "~주차"까지 보입니다.
> * `fullCalendar` 조작: `FullCalendar`가 보여주는 년/월/일 데이터는 현재 보이는 화면에 첫 번째 일자 기준이므로,  '년/월이 넘어가는 주에 경우'처럼 여러 경우에 혼동을 야기하여 이 부분을 api로 불러오던 코드 자체를 제거하였습니다
> * 화살표 `svg`를 url로 전환 후 `select` background로 옮김
> 
> 이 외에도 여러가지가 있는데, 더 궁금한 점 있으면 리뷰로 남겨주세요!

+ select 시작 날짜를 현재 기준 3개월 이전으로 하였습니다.

2023-08-31 07:46 UTC, 2Junsu requested changes

2023-08-31 07:46 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +const getDateOptions = (currentView) => {
아래처럼 option 생성하는 걸 하나로 묶으면 좀 더 가독성이 좋을 것 같아요
```js
const getDateOptions = (currentView) => {
	const currentDate = new Date();
	const selectStartDate = new Date(
		currentDate.setMonth(currentDate.getMonth() - 6),
	);
	const yearRange = selectStartDate.getMonth() > currentDate.getMonth() ? 4 : 3;

	const getMonthRange = (year) =>
		year === selectStartDate.getFullYear()
			? 12 - selectStartDate.getMonth()
			: 12;

	const getOptions = (year, month, week) => {
		const [key, label] = week
			? [`${year}-${month}-${week}`, `${year}년 ${month}월 ${week}주차`]
			: [`${year}-${month}`, `${year}년 ${month}월`];

		return (
			<option key={key} value={key}>
				{label}
			</option>
		);
	};

	const generateOptions = (year, month) => {
		if (currentView === VIEW_TYPE.DAY_GRID_MONTH) {
			return getOptions(year, month);
		}

		return Array.from({ length: countWeek(year, month) }, (_, weekIdx) =>
			getOptions(year, month, weekIdx + 1),
		);
	};

	return Array.from(
		{ length: yearRange },
		(_, yearIdx) => selectStartDate.getFullYear() + yearIdx,
	).map((year) =>
		Array.from({ length: getMonthRange(year) }, (_, monthIdx) =>
			generateOptions(year, selectStartDate.getMonth() + monthIdx + 1),
		),
	);
};
```

2023-09-01 00:17 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +const getDateOptions = (currentView) => {
감사합니다 오늘 수정해서 푸시해놓을게요

2023-09-01 02:20 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +const getDateOptions = (currentView) => {
푸시했습니다 @2Junsu
- 인덱스는 굳이 축약 안하고 적어줬어요
- 어떤건 get, 어떤 건 generate이라 태그를 생성하는 함수는 generate로 통일했습니다
- 그리고 태그를 생성하는 함수임을 명시해주기 위해서 ~OptionTag와 같이 변경했습니다.
https://github.com/Selody-project/Frontend/pull/128/commits/27145bbd45314352acb48b4c8c6e6fee23b499a2

2023-09-01 07:27 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +		];
아래처럼 week를 한 번만 쓰는 게 더 좋아보여요
```js
const [key, label] = week
    ? [`${year}-${month}-${week}`, `${year}년 ${month}월 ${week}주차`]
    : [`${year}-${month}`, `${year}년 ${month}월`];

```

2023-09-01 07:27 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +			return generateOptionTag(year, month);
{}로 묶어주세요!

2023-09-01 07:27 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
>  	);
아래처럼 한 번 더 분해하면 좀 더 가독성이 좋을 것 같아요
```js
	const years = Array.from(
		{ length: yearRange },
		(_, yearIndex) => selectStartDate.getFullYear() + yearIndex,
	);

	const getMonths = (year) =>
		Array.from({ length: getMonthRange(year) }, (_, monthIndex) =>
			year === selectStartDate.getFullYear()
				? selectStartDate.getMonth() + 1 + monthIndex
				: monthIndex + 1,
		).map((month) => generateOptionTags(year, month));

	return years.map((year) => getMonths(year));
```

2023-09-06 10:11 UTC, sikkzz commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +	const used = firstOfMonth.getDay() + lastOfMonth.getDate();
변수명이 used인 이유가 있을까요?

2023-09-06 10:11 UTC, sikkzz commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.styles.js
> +				color: ${({
```jsx
color: ${({ theme: { colors } }) => colors.disabled_text};
```

이렇게 작성하는게 더 간결할 거 같은데 어떻게 생각하시나요

2023-09-06 11:12 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.styles.js
> +				color: ${({
카멜케이스 경고 떄문에 작성 저렇게 했었는데 바꿔도 큰 문제 없을 것 같네요! 변경하고 곧 푸시할게요

2023-09-06 11:28 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
>  	);
이 코드를 반영하긴 했지만, 이를 포함한 함수 자체가 `option` tag를 생성하는 함수여서 `getMonths`() 메서드로 `return`문을 구성하는 건 좋지 않다고 생각이 들었습니다.

그래서 다음과 같이 구현했습니다
1. `getMonths` 대신 `getMonthsForEachYear`로 변경하여 `years`와 같이 단순 `string` array를 만드는 것으로 통일성을 줌
2. `getMonthsForEachYear`에 모든 하위 map 코드를 넣지 않고 months를 얻는 범위까지만 작성
3. 감사는 함수인 `getDateOptions`의 역할과 매칭되도록 `return`문에 `generateOptionTags`가 노출되도록 함

2023-09-06 11:39 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +	const used = firstOfMonth.getDay() + lastOfMonth.getDate();
더 좋은 변수명이 있을 것 같긴 한데 일단,

주차 계산을 하는데에 사용되는 일수는 
> 해당 월의 일수 + 월의 1일 이전 일요일까지 저번 월의 일수

이렇게 계산하게 돼서 해당 월의 총 일수는 아니니, 총 주차 계산 시에 사용되는(used) 일수여서 저렇게 작성했습니다.
더 좋은 변수명으로 한 번 바꿔볼게요

2023-09-06 11:42 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +	const used = firstOfMonth.getDay() + lastOfMonth.getDate();
`datesForCountingWeekNum`로 일단 바꿔봤어요 어떠신가요?
@sikkzz

2023-09-06 11:57 UTC, sikkzz commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +	const used = firstOfMonth.getDay() + lastOfMonth.getDate();
네 괜찮긴한데 더 간단하게 적으려면 countingWeekNum이나 WeekNum등 축약해서 적어도 괜찮을 거 같아요! 이부분에서만 쓰이는 변수긴 하지만 used는 이해하기 어려운 변수명일거 같아서 말씀드렸습니다

2023-09-06 12:00 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +	const used = firstOfMonth.getDay() + lastOfMonth.getDate();
`countingWeekNum`이나 `WeekNum`은 마치 주차 수를 뜻하는 것처럼 보여서 좋지 않은 변수명인 것 같습니다.
날짜 수를 말하는 것이니 제가 수정한 사항 그대로 가는게 괜찮아보이는데 어떠세요?
전 개인적으로 변수명 축약보다 이해가 잘 되게 작성하는 게 맞다고 생각합니다.(그런 면에서 `used`도 잘못됐었네요)

2023-09-06 12:07 UTC, sikkzz commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +	const used = firstOfMonth.getDay() + lastOfMonth.getDate();
네 수정하신대로 사용하면 될 거 같습니다!

2023-09-07 08:24 UTC, sikkzz approved these changes

2023-09-07 20:45 UTC, 2Junsu approved these changes

2023-09-12 06:51 UTC, 2Junsu approved these changes

2023-09-12 08:00 UTC, sikkzz approved these changes

2023-09-12 08:00 UTC, merged