#131 front task User api 구현
Selody-project/Frontend pull request #132
Opened 2023-08-29 18:11 UTC by sikkzz

# 설명

- [https://github.com/Selody-project/Frontend/issues/131](https://github.com/Selody-project/Frontend/issues/131)

#115 이슈에서 페이지 구현 중에 유저 그룹 조회 api가 필요해서 구현했습니다. 
해당 이슈 브랜치에서 작업하려다가 우선은 따로 올립니다. 요청시 해당 브랜치에서 작업하겠습니다.
나머지 user api들은 추후 논의 후 구현하면 될 거 같습니다.

2023-08-31 08:14 UTC, kimyoungyin requested changes

2023-08-31 08:14 UTC, kimyoungyin commented on src/features/user/user-slice.js
여기 아마 준수님이 auth-slice로 변경하셨을 거에요 미리 바꿔두면 편할 것 같아요

2023-08-31 08:14 UTC, kimyoungyin commented on src/store/index.js
여기도 authSlice

2023-08-31 08:14 UTC, kimyoungyin commented on src/features/user/user-slice.js
> +	isLoading: false,
여기서 `isLoading`은 유저 그룹 조회할 때만 쓰이나요?
그게 아니라면 loading state를 분리하는 게 나아보입니다. 유저 그룹을 조회할 때 이 loading state를 쓰는 다른 컴포넌트들도 영향을 받으니까요.
예를 들면 `isUserGroupFetching`과 같이요!

2023-08-31 08:37 UTC, 2Junsu commented on src/features/user/user-slice.js
auth-slice에서 user 정보를 담고 있긴 한데, 유저가 속해있는 그룹 리스트는 auth라고 보기에는 힘들지 않을까요?
그래서 user 정보와 userGroupList를 지금처럼 분리해야할지, 아니면 user 정보에 닉네임, 이메일, 속해있는 그룹들을 한 번에 담는 게 나을지 고민이 되네요.
다들 의견이 어떠신가요?? @sikkzz @kimyoungyin

2023-08-31 11:57 UTC, sikkzz commented on src/features/user/user-slice.js
> +	isLoading: false,
user랑 auth 구분 어떻게 하는지 결과에 따라서 추후에 수정하도록 하겠습니다!

2023-09-01 00:15 UTC, kimyoungyin commented on src/features/user/user-slice.js
그냥 `groupSlice`에 `myGroups` 이런 식으로 하나 만들어서 쓰면 되지 않을까요? 어떻게 생각하세요?

2023-09-01 06:43 UTC, 2Junsu commented on src/features/user/user-slice.js
나중에 설정 페이지를 고려하면 아래와 비슷한 형식으로 나올 것 같아서 기존대로 user-slice로 가는 게 적합할 것 같기도 하네요
```js
const myGroupList = [
	{
		groupId: 1,
		groupName: "dd",
		isSharingEnabled: false, // 개인 일정 공유 여부
		hasNotification: false, // 일정 알림
	},
	{
		groupId: 2,
		groupName: "dd",
		isSharingEnabled: false,
		hasNotification: false,
	},
	{
		groupId: 3,
		groupName: "dd",
		isSharingEnabled: false,
		hasNotification: false,
	},
];
```

2023-09-01 06:50 UTC, kimyoungyin commented on src/features/user/user-slice.js
위 형식을 보고 어떻게 user-slice로 변경하는 게 낫다고 생각하는지 좀 더 자세히 설명해주실 수 있을까요?

제 생각은,
**내 그룹 목록**은 인증 용도보다 그저 전역 `state`로 저장하는 용도로 쓰일 것 같아요.
**내 그룹 목록**이 `authSlice`에 있는 `state` 변화와 밀접하게 관련이 없고, 오히려 `groupSlice`에 많이 관여될 것 같은데
예를 들면 유저가 그룹을 생성한 순간 `fulfilled` 되었을 때 `groupSlice`에 **내 그룹 목록** `state`에 추가해준다던가 하는 식으로요

2023-09-01 07:44 UTC, 2Junsu commented on src/features/user/user-slice.js
authSlice에 넣는 게 아니라 auth와 user를 분리하고, 내 그룹 목록은 설정 페이지에서 쓰이게 될 테니 user에 넣자는 말이었어요. 지금 준식님이 하신 것처럼요!
그룹을 생성했을 때 **내 그룹 목록**에 추가되는 건 백에서 처리할 거고, **설정 페이지**에서는 유저 그룹 조회 api로 정보를 받아오면 된다고 생각했어요

++ 작성하면서 궁금해진 게 있는데요. 물론 백에서 처리할 테지만, 유저가 그룹을 생성했을 때 내 그룹 목록 state에 추가하게 되면, 프론트에서도 자체적으로 state를 관리하는 거잖아요?
이렇게 될 경우 내 그룹 목록 GET api를 처음 한 번만 호출해도 되니 좋을까요?
아니면 굳이 불필요한 과정을 프론트에서 처리하는 거라 별로일까요?

2023-09-02 14:59 UTC, kimyoungyin commented on src/features/user/user-slice.js
그럼 user는 auth.로그인여부가 true이기 전에는 null 상태인 좀 종속적인 상태일 텐데 괜찮을까요?

+ 내 그룹 목록이 근데 한 번 state에 추가한 이후에도
그 이후에 신청해놓았던 그룹 신청 요청이 받아들여지면 db에 있는 내 그룹 목록이 달라지니까 또 받아오긴 해야 해서..
처음 한 번만 호출하는 건 아니어야 할겁니다!

2023-09-03 05:18 UTC, 2Junsu commented on src/features/user/user-slice.js
아 맞네요 그룹 가입이 수동적으로 되는 경우도 있었네요!
그럼 api 호출을 통해 내 그룹목록을 불러오고 user와 auth 기존대로 그냥 분리하는 게 나아보이네요

2023-09-03 05:19 UTC, kimyoungyin commented on src/features/user/user-slice.js
동의합니다 ㅎㅎ

2023-09-03 05:40 UTC, 2Junsu submitted a review, later dismissed

2023-09-03 13:47 UTC, kimyoungyin approved these changes, later dismissed

2023-09-04 10:25 UTC, kimyoungyin requested changes
테마 가져오기 확인 완료

2023-09-04 12:19 UTC, 2Junsu submitted a review, later dismissed

2023-10-17 01:31 UTC, kimyoungyin submitted a review, later dismissed
확인했습니다

2023-11-03 00:26 UTC, kimyoungyin submitted a review, later dismissed

2023-11-20 00:34 UTC, kimyoungyin approved these changes

2023-11-25 10:40 UTC, merged