issue #134 feat: Add naver login
Selody-project/Frontend pull request #135
Opened 2023-09-05 09:17 UTC by 2Junsu

# 설명
- #134 
- 네이버 로그인
  - 네이버 이메일, 랜덤 닉네임 반환  
- 이미 일반 회원가입으로 가입된 계정으로 네이버 로그인
  - 로컬 이메일, 로컬 닉네임 반환
- 일반 로그인
  - 로컬 이메일, 로컬 닉네임 반환
- 구글 로그인
# 테스트

-

# Demo

https://github.com/Selody-project/Frontend/assets/77619905/8ad3314d-3202-4896-8225-0a311d6a60d2

2023-09-06 10:22 UTC, sikkzz commented on src/features/auth/auth-slice.js
> -		logoutHandler: (state) => {
파일 맨 아래 export 문에서도 logoutHandler가 빠져야 할 거 같아요!

2023-09-20 02:24 UTC, kimyoungyin commented on src/features/auth/auth-service.js
> +		localStorage.removeItem("com.naver.nid.oauth.state_token");
기본적으로 네이버 로그인은 localStorage에 저장하나보네요? 위험하네..

2023-09-20 02:36 UTC, kimyoungyin requested changes
기존 회원이 네이버 로그인을 시도했을 때, 두 회원의 중복여부는 이메일로 이루어지나요?
전 다른 이메일이어서 그런지 그냥 새로운 계정이 만들어지네요

여기는 다른 브랜치여서 그렇긴 한데, 안녕하세요 undefined님이 보이긴 하네요 ㅋㅋ

2023-09-20 02:36 UTC, kimyoungyin commented on src/pages/LoginPage/LoginPage.jsx
> +			dispatchFn(naverLogin(naverAccessToken));
dispatchFn => dispatch

2023-09-20 02:36 UTC, kimyoungyin commented on src/pages/LoginPage/LoginPage.jsx
> +		"#access_token",
이 부분 설명 부탁드려도 될까요?

2023-09-26 10:50 UTC, 2Junsu commented on src/pages/LoginPage/LoginPage.jsx
> +		"#access_token",
아 이건 기존 커스텀훅으로 분리돼있던 걸 없애고 통합한 건데요
네이버 로그인을 하게 되면 ~~~#access_token={토큰값} 이런 식으로 토큰이 url에 붙어서 넘어오는데 여기서 토큰값을 가져오는 코드입니다

2023-09-26 10:52 UTC, 2Junsu commented
> 기존 회원이 네이버 로그인을 시도했을 때, 두 회원의 중복여부는 이메일로 이루어지나요? 전 다른 이메일이어서 그런지 그냥 새로운 계정이 만들어지네요
> 
> 여기는 다른 브랜치여서 그렇긴 한데, 안녕하세요 undefined님이 보이긴 하네요 ㅋㅋ

기존 회원이 네이버 로그인을 하면 소셜이랑 자동 연동됩니다! 회원 정보는 기존 로컬의 정보를 따르고요

2023-10-17 02:15 UTC, kimyoungyin commented on src/pages/LoginPage/LoginPage.jsx
> +		"#access_token",
그러면 `<Naver />`에서 `naverLogin`이 성공해서 `naverLogin.init()`을 하면 리다이렉트 됨과 동시에 `naverAccessToken`이 변경되서 `useEffect`에 의해 로그인 처리되는걸까요?

2023-10-17 02:15 UTC, kimyoungyin commented on src/pages/LoginPage/LoginPage.jsx
> +		"#access_token",
+ 기존 로컬 유저가 있는 경우 걸러주는 로직은 어떻게 작동되나요?
같은 이메일인 경우만 같은 유저로 판별하는 거죠?

2023-10-25 20:19 UTC, 2Junsu commented on src/pages/LoginPage/LoginPage.jsx
> +		"#access_token",
> 그러면 `<Naver />`에서 `naverLogin`이 성공해서 `naverLogin.init()`을 하면 리다이렉트 됨과 동시에 `naverAccessToken`이 변경되서 `useEffect`에 의해 로그인 처리되는걸까요?

네 맞아요

---

> * 기존 로컬 유저가 있는 경우 걸러주는 로직은 어떻게 작동되나요?
>   같은 이메일인 경우만 같은 유저로 판별하는 거죠?
이거는 백엔드에서 처리해서 프론트에선 자동으로 연동됩니다! 같은 이메일인 경우에 연동하는 거로 알고 있어요

2023-11-03 00:45 UTC, kimyoungyin requested changes

2023-11-03 00:45 UTC, kimyoungyin commented on src/components/sign/Google.jsx
>  import GoogleLogo from "@/assets/icon/ic-google-logo.svg";
iconConstants 파일로 옮긴 후, ~Icon으로 작성 부탁드립니다

2023-11-03 00:45 UTC, kimyoungyin commented on src/features/auth/auth-service.js
commonThunk로 공통 로직을 통일해주시면 좋을 것 같습니다

2023-11-03 00:45 UTC, kimyoungyin commented on src/features/auth/auth-slice.js
로컬 로그인 시 "안녕하세요 undefined님"으로 다시 변경되버렸는데 확인 부탁드립니다

2023-11-10 07:16 UTC, kimyoungyin requested changes

2023-11-10 07:16 UTC, kimyoungyin commented on src/features/commonThunk.js
> +export default commonThunk;
여기서도 준수님이 요청주신 대로 catch문도 수정해주시면 됩니다!

2023-11-17 07:32 UTC, sikkzz approved these changes, later dismissed

2023-11-22 02:04 UTC, kimyoungyin submitted a review, later dismissed

2023-11-25 11:29 UTC, sikkzz approved these changes, later dismissed

2023-11-25 11:36 UTC, sikkzz approved these changes

2023-11-25 11:36 UTC, merged