issue #117 front task 커뮤니티 그룹 페이지
Selody-project/Frontend pull request #137
Opened 2023-09-07 14:28 UTC by sikkzz

# 설명

- [https://github.com/Selody-project/Frontend/issues/117](https://github.com/Selody-project/Frontend/issues/117)
- 그룹 페이지 퍼블리싱 및 api 1차 연결
    - issue 131, 115 작업 내용들과 합쳐서 추가 작업 예정
- 주석 처리한 부분들과 컴포넌트 세분화 및 재사용 컴포넌트 작업도 합쳐서 작업 예정

# Demo
<img width="1345" alt="스크린샷 2023-09-07 오후 11 27 42" src="https://github.com/Selody-project/Frontend/assets/100590110/7cbc19e2-2115-4328-98cc-40f03770c131">

2023-09-07 14:29 UTC, sikkzz commented
여기도 115번과 동일하게 중간에 develop을 땡긴 적이 있어서 추후에 리뷰 작업 끝나면 rebase 다시 진행하도록 하겠습니다.

2023-09-11 15:59 UTC, 2Junsu requested changes
전체적으로 아래 요소들 확인 부탁드립니다!
- css-in-js와 styled-components를 혼용한 곳이 있다면, styled-components로 옮기는 게 좋을 것 같아요
- font-weight는 theme에서 가져다 쓰는 게 좋을 것 같아요
- font-family를 최상위 요소에서 한 번 선언해놓으면 중복 선언할 필요 없어서 좋을 것 같아요

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	const [open, setOpen] = useState(false);
isOpen으로 바꾸면 좋을 것 같아요

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	};
여러 게시글의 옵션을 열어둘 수 있는 것 같은데, 하나가 열리면 이전에 열려있던 옵션이 닫히는 게 좋지 않을까하는 생각이 드는데 어떠신가요??

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +			</FeedDiv>
여기도 나중에 컴포넌트로 분리하실 계획이시죠??

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/GroupFeed.styles.js
> +		font-family: Inter;
여기랑 아래 Button에 있는 font-family에 따로 쓰지 말고 TitleDiv에 직접 주면 좋을 것 같아요

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/GroupFeed.styles.js
> +	right: -30px;
Option이랑 OptionMenuDiv를 div로 묶고, 해당 div에 Option에 줬던 스타일을 준 후에, right는 없애면 어떨까요? 이렇게 하면 -30을 주지 않고도 자연스레 나란하게 정렬할 수 있어 좋은 것 같은데

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/GroupFeed.styles.js
> +		margin: 5px 0 0 0;
그냥 마진탑으로 줘도 될 것 같아요

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/GroupFeed.styles.js
> +		font-weight: 400;
theme파일에서 불러다 쓰면 좋겠네요

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/SecretFeed.styles.js
> +		font-family: Inter;
font-family를 위에서 한번에 주면 좋을 것 같아요

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/SecretFeed.styles.js
> +		font-weight: 400;
여기도 theme에서 불러와주세요!

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/SecretFeed.styles.js
> +	border: 1px solid #c9ccd7;
컬러시스템에 정의돼있습니다!

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/SecretFeed.jsx
> +	return (
return 빼도 될 것 같네요

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/UploadFeed.jsx
> +	return (
여기도 return 없애면 좋겠네요

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/UploadFeed.styles.js
> +	all: unset;
globalStyles에 버튼은 이미 unset으로 돼있어요!

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/UploadFeed.styles.js
> +		font-weight: 400;
theme

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupFeed/UploadFeed.styles.js
font-family 한번에 모아서 써주면 좋겠네요!

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupMember/GroupMember.jsx
> +				{groupRequestMemberList.length === 0 ? null : <MemberRequestList />}
```groupRequestMemberList.length && <MemberRequestList />```로 줄여쓰면 어떨까요?

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupMember/GroupMember.styles.js
> +export const MemberUl = styled.ul`
이것처럼 여러 파일에서 쓰이는 것들은 헷갈리지 않게 따로 파일을 만드는 게 좋을 것 같아요
shared.style.js 라든가 이름을 지어서요

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupMember/MemberList.jsx
> +								style={{ display: openArr[info.userId] ? "flex" : "none" }}
styled-components와 css-in-js를 혼용하는 건 별로 좋지 않아 보입니다..!

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupMember/MemberList.jsx
> +	};
위와 동일

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupMember/MemberList.jsx
> +	const [open, setOpen] = useState(false);
isOpen

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupMember/MemberRequestList.jsx
> +									<h5>수락</h5>
이정도는 h5 말고 span으로 써도 되지 않을까요?

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupProfile/GroupProfile.jsx
> +					<h3>{groupInfo?.information.member}</h3>
여기랑 아래 피드 수에 toLocaleString()을 추가하면 좋을 것 같네요

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupProfile/GroupProfile.jsx
> +				<h3>{groupInfo?.information.name}</h3>
텍스트가 길어질 때 화면 밖으로 빠져나가는데 이거 처리가 필요할 것 같아요
![스크린샷 2023-09-12 오전 12 38 45](https://github.com/Selody-project/Frontend/assets/77619905/25e69944-f9f8-4ef7-9ae8-af4c6e4690be)

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupProfile/GroupProfile.styles.js
> +	max-height: 546px;
max-height를 정하신 이유가 있나요?

2023-09-11 15:59 UTC, 2Junsu commented on src/components/Group/GroupProfile/GroupProfile.styles.js
> +	padding: 26px 48px;
위에서 사이즈를 딱 숫자로 정해놔서 이렇게 패딩으로 주신 것 같은데, 그냥 가운데 정렬 하는 게 낫지 않을까요?

2023-09-11 15:59 UTC, 2Junsu commented on src/features/group/group-service.js
뭔가 반복되는 게 굉장히 많은데 함수 하나로 빼내서 여러군데에서 불러 쓰도록 고치면 좋지 않을까..싶네요
여기 뿐만 아니라 다른 thunk 파일에서도요!

2023-09-11 15:59 UTC, 2Junsu commented on src/pages/GroupPage/GroupPage.styles.js
> +	padding: 18px 0 0 78px;
나중에 헤더랑 같이 배치하게 되면, 헤더보다 좌우 padding을 30px정도 더 주고 아래 middleDiv maxwidth를 없애는 게 낫지 않을까요??
현재 padding을 너무 억지로 주는 느낌이라..

2023-09-12 01:25 UTC, kimyoungyin commented on src/components/Group/GroupMember/MemberList.jsx
> +								style={{ display: openArr[info.userId] ? "flex" : "none" }}
styled-components가 css-in-js 중의 하나로 알고 있습니다!
여기선 인라인 스타일을 말씀하시는 것 같네요

2023-09-12 06:32 UTC, kimyoungyin requested changes

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +			<TitleDiv>
너무 다 div로 처리하지말고 시멘틱 태그로 가능한 부분은 대체하는 게 좋을 것 같아요

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	const [sort, setSort] = useState("latest");
1. `sort`에 들어갈 문자열은 `"latest"`/`"like"`로 제한되는데, 이 떄 직접 문자열로 작성하는 것보다 상수 형태로 값을 선언하고 쓰는 것이 이후 작업할 때 안전합니다. 사실 이것 때문에 타입스크립트를 쓰는 거긴 합니다.
제 구현 내용 중 일부인데, 디렉토리와 코드를 참고해서 수정 부탁드립니다
<img width="628" alt="스크린샷 2023-09-12 오후 1 08 02" src="https://github.com/Selody-project/Frontend/assets/78777345/1826852c-e7ec-4d52-af63-50c310f5df97">

2. 두 string의 의미가 동일하게 전달되어야 하니까, '좋아요 순'을 `"like"`말고 `"latest"`와 의믜가 맞는 용어로 변경 가능할까요?

3. `sort`보단 예를 들어 `sortOption`과 같이 구체적으로 선언하는 게 어떠세요?

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	};
저도 그렇게 생각합니다

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	const [openArr, setOpenArr] = useState([false]);
1. 처음 딱 봤을 떄 `open`이 뭘 여는 데에 사용되는 state인지 한 눈에 파악하기 힘들었습니다. 조금 더 구체적으로 state명을 작성해주세요(is~ 식으로요!). 일단 밑의 내용을 반영한다면 해당 state명을 사용할 일은 없을 거에요

2. 굳이 불필요하게 두 state가 존재하는 것 같습니다. 제 추천은 `optionMenuOpenedFeedIndex`와 같이 하나의 state로 통일하는 것입니다.
해당 state는 `null`이나 `number` 타입이며, initialValue는 `null`입니다. 각 피드 내부에서 해당 state가 배열의 index값과 일치할 경우 옵션메뉴를 열게 됩니다. 
```js
{ optionMenuOpenedFeedIndex === index && <OptionMenuDiv>...</OptionMenuDiv> }
```
3. 그리고 각 피드의 옵션 메뉴를 trigger하는 svg를 클릭 시에, prev state와 동일한 인덱스의 svg라면 null로 초기화, 그게 아니라 prev state와 다른 state라면 svg를 포함하는 인덱스 값으로 `setState` 시켜주면 됩니다.
```js
setOptionMenuOpenedFeedIndex(prev => prev === index ? null : index)

```

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	};
일단 이 코드 전체를 위의 제 제안에 따라 완전히 바꿔야겠지만, 일단 말씀드리는 부분을 알아두면 좋을 것 같습니다.

prev state를 `setState` 함수 내부가 아닌 외부에서 수정하고 이를 다시 `setState`에 할당(전달)하는 방식은 prev state가 무조건 최신 상태임을 확신할 수 없습니다. 무조건 `setState(prev => ...)`와 같이 작성해야 사용할 prev state가 가장 최신의 것이라고 단정지을 수 있어요. 

물론 이럴 경우 준식님 코드에 적용하면 `setState` 함수 내부에서 다른 `setState` 함수를 호출해야 하는데(`setOpen`과 `setOpenArr`) 이것도 불가능(?)하죠. 사실 이럴 일이 없어야 하는데, 어쩔 수 없는 경우라 생각이 들면 애초에 state 설계를 잘못하지 않았나 되짚어보아야 합니다. 아래 두 경우 중 하나일 것입니다.
- 이 두 state들을 하나의 state로 묶어야 했나(객체와 같은 방식)
- **state를 불필요하게 2개로 쪼개지 않았나? 하나면 충분했던 것일 수도 있지 않을까?**

저는 이 중 **후자**로 생각되며, 구현 방법은 위 코멘트에 남겨두었으니 확인해보시면 되겠습니다

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +							onClick={() => setSort("latest")}
이런 것들도 하나씩 constants 폴더에 넣어 선언한 값들을 불러오면 실수할 일이 없겠죠?

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +			</FeedDiv>
컴포넌트 매핑이 필요해보입니다. 더미데이터이니 더미데이터 객체 배열을 컴포넌트 외부로  빼서 선언하고 매핑하면 좋을 것 같아요!

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.styles.js
> +	color: ${(props) => (props.disabled ? "#121127" : "#9ca0ab")};
theme 사용 부탁드려요!

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +import Option from "@/assets/icon/ic-feed-option.svg";
Option이라 하면 와닿지 않으니 OptionThreeDots와 같이 작성하는게 좋을 것 같습니다.

svg는 ~Icon으로 통일할까요?

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.styles.js
너무 div만 사용하지 않았는지 고민해봅시다!

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupMember/GroupMember.jsx
> +		<ContainerDiv>
aside tag가 좋아보이네요

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupMember/GroupMember.jsx
> +				{groupRequestMemberList.length === 0 ? null : <MemberRequestList />}
저는 `groupRequestMemberList.length === 0 || <MemberRequestList />`이 나아보입니다.
길이라는 프로퍼티가 존재하는 것과 길이를 비교하는 것이랑은 다르니까요

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupMember/GroupMember.jsx
> +				<MemberList />
그냥 `<MemberList />` `<MemberRequestList />`에 유사한 로직도 많고, UI도 동일한 것을 많이 쓰는데, `<MemberList />`에 `isRequest` prop을 줘서 내부에서 구분하면 좋지 않을까요?

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupMember/GroupMember.styles.js
> +export const MemberUl = styled.ul`
전 `<MemberList />`와 `<MemberRequestList />`를 하나로 합친다면 따로 styles 파일을 만들 필요도 없을 것 같은데 어떠세요?

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupMember/MemberList.jsx
> +	};
제가 위에서 말씀드렸던 방식 참고해서 변경 부탁드려요

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupMember/MemberList.jsx
여기에 `isRequest`를 prop으로 받아와 `MemberRequestList`를 없애고 여기에 통일시키는 거 어떠세요?

2023-09-12 06:32 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfile.styles.js
> +	max-height: 546px;
그냥 height로 하면 되지 않나요?

2023-09-12 06:32 UTC, kimyoungyin commented on src/features/group/group-service.js
동의합니다

2023-09-12 06:32 UTC, kimyoungyin commented on src/features/group/group-service.js
> +export const rejectGroupRequest = createAsyncThunk(
그룹 가입 요청 관련 명명을 ~Request로 다 작성했는데, 이것보다 join을 쓰는 게 낫지 않을까요?
joinRequest 혹은 join으로 명명하는 게 좋아보입니다. 
request는 http request랑 혼동될 수도 있을 것 같아요!

2023-09-12 06:32 UTC, kimyoungyin commented on src/features/group/group-service.js
> +export const getGroupMemberList = createAsyncThunk(
예를 들어, 이것도 굳이 두 개로 나누지 말고 하나로 통일한 뒤에
`isJoinRequest`와 같은 boolean 값을 payload로 받아와 함께 처리하는 게 좋아보이네요

2023-09-12 06:32 UTC, kimyoungyin commented on src/features/group/group-slice.js
>  	extraReducers: (bulider) => {
너무 같은 로직이 반복되는 경우 extraReducer 내부에 함수를 선언하고 재사용하는 방법이 있습니다
해당 글을 찾아보였는데 [예시](https://github.com/reduxjs/redux-toolkit/issues/429#issuecomment-623888417)를 참고해보세요!

2023-09-12 06:32 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.styles.js
> +	padding: 18px 0 0 78px;
동의합니다

2023-09-13 07:30 UTC, sikkzz commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +			</FeedDiv>
네 issue 115에서 작업한 부분이랑 겹쳐서 추후 수정 예정입니다

2023-09-13 10:43 UTC, sikkzz commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	const [openArr, setOpenArr] = useState([false]);
좋은 방법인거 같습니다 조언 감사합니다! 다만 작성중에 handleOption 함수를 다음과 같이 작성해봤는데 이 코드는 어떤가요?

<img width="465" alt="스크린샷 2023-09-13 오후 7 43 00" src="https://github.com/Selody-project/Frontend/assets/100590110/f6b4c4f5-60d0-47c0-9a23-413b3a282f46">

2023-09-13 13:54 UTC, sikkzz commented on src/components/Group/GroupMember/GroupMember.jsx
> +				<MemberList />
MemberList는 항상 렌더링 되는 컴포넌트이고 MemberRequestList는 그룹 요청이 있을때만 렌더링되어야 하다 보니까 MemberList에 합쳐서 구분해도 코드가 더 간결해질 요소가 없다고 생각했고 그렇다면 오히려 비슷한 로직과 코드로 인해 혼란이 있을 거 같아서 파일을 나눠서 작성했습니다.

2023-09-13 13:56 UTC, sikkzz commented on src/components/Group/GroupMember/GroupMember.jsx
> +				<MemberList />
prop을 통해 구분해도 두개의 컴포넌트 작동이 사소한 부분들이 다르기에 파일을 합쳤을 때 간소화 방법이 보이지 않는데 괜찮은 방법이 있을까요?

2023-09-13 13:57 UTC, sikkzz commented on src/components/Group/GroupMember/GroupMember.jsx
> +				<MemberList />
GroupMember 파일까지 포함해서 특히 UI 코드들이 유사한건 저도 인지는 하고 있었는데 전에 준수님 리뷰에 있었던 거처럼 매핑으로 빼기에는 다른 부분들이 있어서 방법을 찾지 못해서 저는 파일을 나눠서 작성하긴 했습니다.

2023-09-13 14:06 UTC, sikkzz commented on src/components/Group/GroupMember/GroupMember.styles.js
> +export const MemberUl = styled.ul`
두 파일을 합칠 수 있다면 하나로 통일하고 아니면 share style로 변경하도록 하겠습니다

2023-09-13 14:43 UTC, sikkzz commented on src/components/Group/GroupProfile/GroupProfile.styles.js
> +	padding: 26px 48px;
뭔가 이상하게 작동해서 찾아봤는데 GroupPage에서 테스트용으로 height: 100vh가 들어가 있어서 height값을 안넣으면 작동을 안하는거였네요 가로는 가운데 정렬하고 각 div에 위아래 padding값만 적용시켜놓았습니다. 버튼이 2개인 경우의 수도 있어서 height 값 수치로 적용 안시켜놨는데 괜찮으신가요?

2023-09-13 14:45 UTC, sikkzz commented on src/components/Group/GroupProfile/GroupProfile.styles.js
> +	padding: 26px 48px;
버튼이 있는 bottom div 제외하고 top과 middle div는 변동이 없을 컴포넌트라 height 값 적용하고 세로 또한 가운데 정렬이 가능하긴 합니다.

2023-09-13 14:49 UTC, sikkzz commented on src/pages/GroupPage/GroupPage.styles.js
> +	padding: 18px 0 0 78px;
그럼 우선 두 수치 모두 삭제하고 추후 헤더 rebase시 배치 보고 다시 수정하도록 하겠습니다.

2023-09-13 15:03 UTC, sikkzz commented on src/components/Group/GroupProfile/GroupProfile.jsx
> +				<h3>{groupInfo?.information.name}</h3>
우선 overflow 처리는 해놓았습니다. 이외의 부분은 디자이너분한테도 말씀 드리고 회의때 한번 말씀 드리겠습니다.

2023-09-13 15:33 UTC, sikkzz commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	const [sort, setSort] = useState("latest");
수정했습니다. 최신순은 latest, 좋아요순은 best로 설정해놓았는데 더 좋은 용어가 있다면 말씀해주시면 감사하겠습니다.

2023-09-13 15:37 UTC, sikkzz commented on src/features/group/group-service.js
> +export const rejectGroupRequest = createAsyncThunk(
join으로 수정했습니다

2023-09-13 16:53 UTC, sikkzz commented on src/features/group/group-slice.js
>  	extraReducers: (bulider) => {
해당 코멘트는 과거 방식이라 사용이 불가능했습니다. 오류 뜨는 부분을 확인해봤지만 해결 또한 불가했습니다. 그 아래 코멘트에 업데이트 된 방식으로 실행해봤을때 addMatcher를 이용해 다음 사진같이 리팩토링은 가능했습니다. 다만 의도하신 방식이 맞는지 의문입니다.

2023-09-18 00:12 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	const [openArr, setOpenArr] = useState([false]);
이 방법도 나쁘지 않긴 하지만 최신 상태의 prev state일 가능성이, setState 함수 내부에서 다루는 것보다 높지 않습니다.
`setOptionMenuOpenedFeedIndex(prev => prev === index ? null : index)`
이게 좋아보입니다!

2023-09-18 00:12 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	const [sort, setSort] = useState("latest");
괜찮은 것 같습니다!

2023-09-18 00:25 UTC, kimyoungyin commented on src/features/group/group-slice.js
>  	extraReducers: (bulider) => {
이 방식 좋은 것 같습니다

2023-09-18 00:40 UTC, kimyoungyin commented on src/components/Group/GroupMember/GroupMember.jsx
> +				<MemberList />
```jsx
{groupinfoDetail?.information.memberInfo.length === 0 || (
	<MemberList
		members={groupinfoDetail?.information.memberInfo}
		isRequest={false}
	/>
)}
```
예를 들어 이렇게 해놓고 dispatch와 같은 함수나 UI는 prop으로 받아온 `isRequest`로 구분해서 내부에서 진행하는 거죠!

2023-09-18 09:06 UTC, sikkzz commented on src/components/Group/GroupMember/GroupMember.jsx
> +				<MemberList />
그룹원 신청이 없을시 사진에 있는 레이아웃이 hr포함해서 렌더링이 진행되지 않아야 하기에 한 파일에 작성하더라도 코드를 하나로 합쳐서 작성은 불가능해보입니다. 다음과 같이 MemberList가 작성됩니다. 내부 코드가 길어지는걸 고려하면 차라리 추가 작성되는 코드가 있더라도 파일을 구분해서 작성하는게 낫지 않을까요?

<img width="287" alt="스크린샷 2023-09-18 오후 6 02 51" src="https://github.com/Selody-project/Frontend/assets/100590110/e1f11ee8-ef6d-4cd0-8a79-591ab768b696">

```jsx
<MemberInnerDiv>
	{members && (
		<>
			<MemberH3>그룹원 신청</MemberH3>
			<MemberUl>
				{members.map((info) => (
					<li key={info.member.userId}>
						<img src={SampleImg} alt="sampleImg" />
						<h4>{info.member.nickname}</h4>
						<ButtonDiv>
							<ButtonInnerDiv
								onClick={() => {
									approveRequest(20, info.member.userId);
								}}
							>
								<button type="button">
									<RequestCheck />
								</button>
								<span>수락</span>
							</ButtonInnerDiv>
							<ButtonInnerDiv
								onClick={() => {
									rejectRequest(20, info.member.userId);
								}}
							>
								<button type="button">
									<RequestClose />
								</button>
								<span>거절</span>
							</ButtonInnerDiv>
						</ButtonDiv>
					</li>
				))}
			</MemberUl>

			<hr />
		</>
	)}

	<MemberH3>그룹원</MemberH3>
	<MemberUl>
		{groupInfoDetail?.information.memberInfo.map((info) => (
			<li key={info.userId}>
				<img src={SampleImg} alt="sampleImg" />
				<h4>{info.nickname}</h4>
				<button type="button">
					<Option
						onClick={() => {
							handleOption(info.userId);
						}}
					/>
					{optionMenuOpenedMemberIndex === info.userId && (
						<OptionMenuDiv
							onClick={() => {
								deleteMember(20, info.userId);
							}}
						>
							내보내기
						</OptionMenuDiv>
					)}
				</button>
			</li>
		))}
	</MemberUl>
</MemberInnerDiv>;
```

2023-09-22 02:57 UTC, sikkzz commented on src/features/group/group-service.js
로직이 겹치긴 하지만 각각의 action은 보통 유니크하게 작동하지 않나요? action name이랑 api end point를 같이 간소화 할 수 있는 방법이 따로 있는걸까요?

2023-09-25 00:38 UTC, kimyoungyin commented on src/components/Group/GroupMember/GroupMember.jsx
> +				<MemberList />
길어지게 되는게 불가피하다면 그대로 진행해도 괜찮을 것 같네요

2023-09-25 06:59 UTC, sikkzz commented on src/components/Group/GroupMember/GroupMember.jsx
> +				<MemberList />
파일 나눠서 작성하고 share style로 작성하는 방향으로 하겠습니다

2023-09-28 07:45 UTC, 2Junsu commented on src/features/group/group-service.js
아래 느낌으로 해보면..어떨까요..?

++ 보니까 ```const response = await customFetch.get(`/api/group/${groupId}/info`, {
				groupId,
			});```
여기서 request body는 빼도 될것 같아요 이미 path string으로 넘겨주고 있어서
```js
const customThunk = async (params, successCode, thunkAPI) => {
	try {
		const response = await customFetch.request({ ...params });
		if (response.status !== successCode) {
			throw response.data;
		}
		return response.data;
	} catch (error) {
		return thunkAPI.rejectWithValue(error.message);
	}
};

export const getGroupInfo = createAsyncThunk(
	"group/getGroupInfo",
	async (groupId, thunkAPI) => {
		await customThunk(
			{ method: "GET", url: `/api/group/${groupId}/info` },
			200,
			thunkAPI,
		);
	},
);
```

2023-10-02 13:43 UTC, sikkzz commented on src/features/group/group-service.js
위 방식 혹시 따로 테스트는 못해보셨을까요? 저는 service에서는 데이터가 확인이 되는데 slice에서 payload로 값이 안넘어와서요

2023-10-10 07:00 UTC, 2Junsu commented on src/features/group/group-service.js
customThunk를 response에 저장하고 그 값을 리턴해주면 되겠네요 !

2023-10-17 04:42 UTC, kimyoungyin commented on src/features/group/group-service.js
commonThunk로 선언해서 사용해봤는데 참고하시면 좋을 것 같습니다.
이 부분 머지되면 다른 thunk에서도 사용하면 좋을 것 같아요

```js
const commonThunk = async (params, successCode, thunkAPI) => {
	try {
		const response = await customFetch.request(params);
		if (response.status !== successCode) {
			throw response.data;
		}
		return response.data;
	} catch (error) {
		return thunkAPI.rejectWithValue(error.message);
	}
};

export const getGroupInfo = createAsyncThunk(
	"group/getGroupInfo",
	async (groupId, thunkAPI) => {
		const data = await commonThunk(
			{ method: "GET", url: `/api/group/${groupId}/info` },
			200,
			thunkAPI,
		);
		return data;
	},
);
```

2023-10-17 05:03 UTC, kimyoungyin requested changes
리뷰 간단히 해봤습니다!

2023-10-17 05:03 UTC, kimyoungyin commented on src/App.jsx
> +	{ path: "group", element: <GroupPage /> },
그룹 페이지도 Header가 필요할 것 같아 상단 children에 옮기는 게 좋아보입니다

2023-10-17 05:03 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfile.jsx
> +				</button>
그룹이 secret일 때도 생각해야 할 것 같아요. "그룹 나가기" 버튼 말고 다른 버튼을 보여줘야 할 것 같은데요?

2023-10-17 05:03 UTC, kimyoungyin commented on src/components/Group/GroupMember/MemberList.jsx
> +	const deleteMember = (groupId, userId) => {
`<MemberList />`는 어차피 한 그룹에 대한 정보를 보여주니 굳이 여기 parameter로 `groupId`를 넣을 필요는 없어보입니다. 전역으로 저장된 `groupId`를 가져오던가, 상위 컴포넌트에서 prop으로 받아올 수 있어보여요

2023-10-17 05:03 UTC, kimyoungyin commented on src/components/Group/GroupMember/MemberRequestList.jsx
> +	};
여기도 groupId가 필요 없어 보입니다.

2023-10-17 08:09 UTC, sikkzz commented on src/features/group/group-service.js
해당 방식 확인했습니다. 리팩토링 진행해볼게요!

2023-10-18 17:01 UTC, sikkzz commented on src/components/Group/GroupProfile/GroupProfile.jsx
> +				</button>
secret group 관련 처리는 우선 해놓았고 이외에 그룹 참여 요청 등 다른 버튼 컴포넌트는 추후 새로 생성하는 issue에서 권한 작업 하면서 같이 할게요

2023-10-24 01:58 UTC, kimyoungyin requested changes

2023-10-24 01:58 UTC, kimyoungyin commented on src/features/group/group-service.js
```js
const commonThunk = async (config, successCode, thunkAPI) => {
	try {
		const response = await customFetch.request(config);
		if (response.status !== successCode) {
			throw response.data;
		}
		return response.data;
	} catch (error) {
		return thunkAPI.rejectWithValue(error.message);
	}
};
```

이게 맞는 것 같습니다. 테스트 해보니 params와 method/url은 같은 깊이의 프로퍼티가 아니고, params 뿐만 아니라 POST 요청의 경우 body data도 필요한데 같이 넣어야 하니까요

2023-11-10 07:34 UTC, kimyoungyin requested changes

2023-11-10 07:34 UTC, kimyoungyin commented on src/features/commonThunk.js
이 부분 준수님이랑 회의해서 수정했는데 반영해주시면 됩니다
- getSuccessCode 제거 후 successCode를 param에 명시적으로 받을 것
- catch문
```js
} catch (error) {
		if (error.response) {
			return thunkAPI.rejectWithValue(error.response.data);
		}
		return thunkAPI.rejectWithValue(error.message);
	}
```

2023-11-10 07:34 UTC, kimyoungyin commented on src/features/group/group-service.js
commonThunk 수정 후 반영하면 됩니다!

2023-11-22 02:17 UTC, kimyoungyin approved these changes, later dismissed

2023-11-26 07:01 UTC, merged