issue #140 fix: Fix dropdown close error
Selody-project/Frontend pull request #141
Opened 2023-10-08 09:35 UTC by 2Junsu

# 설명

- #140 
- 프로필 클릭 시 드롭다운이 닫히지 않는 버그 수정
- 알림 탭은 추후 헤더로 옮길 예정이므로 작업 X

# 테스트

-

# Demo

https://github.com/Selody-project/Frontend/assets/77619905/f41b4db3-da46-40fa-b8e6-9cfb44f87f14

2023-10-09 09:05 UTC, sikkzz submitted a review, later dismissed

2023-10-17 05:08 UTC, kimyoungyin requested changes

2023-10-17 05:08 UTC, kimyoungyin commented on src/components/Header/Header/Header.jsx
> +			if (!dropdownRef.current.contains(e.target)) {
불필요한 중첩 조건문으로 보입니다.
```js
if (isDropdownOpen && !dropdownRef.current.contains(e.target)) {
  // ...
};
```

2023-10-28 11:51 UTC, sikkzz requested changes
```js
const handleDropdown = (e) => {
  if (!profileRef.current.contains(e.target)) {
    setIsDropdownOpen(!isDropdownOpen);
  }
}

useEffect(() => {
  window.addEventListener("click", handleDropdown);

  return () => {
    window.removeEventListener("click", handleDropdown);
  };
}, [isDropdownOpen]);

<ProfileImg
  {...}
  ref={profileRef}
  onClick={() => setIsDropdownOpen(!isDropdownOpen)}
/>
```

이 방식으로 리팩토링 해보는건 어떠세요? ProfileDropdown에 ref를 forwardRef 사용하면서까지 넘겨줘야 할 이유가 없을 거 같아서요. 혹시 의도하신 이유가 있다면 알려주세요!

2023-11-03 10:21 UTC, sikkzz commented
> ```js
> const handleDropdown = (e) => {
>   if (!profileRef.current.contains(e.target)) {
>     setIsDropdownOpen(!isDropdownOpen);
>   }
> }
> 
> useEffect(() => {
>   window.addEventListener("click", handleDropdown);
> 
>   return () => {
>     window.removeEventListener("click", handleDropdown);
>   };
> }, [isDropdownOpen]);
> 
> <ProfileImg
>   {...}
>   ref={profileRef}
>   onClick={() => setIsDropdownOpen(!isDropdownOpen)}
> />
> ```
> 
> 이 방식으로 리팩토링 해보는건 어떠세요? ProfileDropdown에 ref를 forwardRef 사용하면서까지 넘겨줘야 할 이유가 없을 거 같아서요. 혹시 의도하신 이유가 있다면 알려주세요!

관련 내용 136번, 144번 pr에 작성해놓았습니다

2023-11-06 17:50 UTC, 2Junsu commented
> ```js
> const handleDropdown = (e) => {
>   if (!profileRef.current.contains(e.target)) {
>     setIsDropdownOpen(!isDropdownOpen);
>   }
> }
> 
> useEffect(() => {
>   window.addEventListener("click", handleDropdown);
> 
>   return () => {
>     window.removeEventListener("click", handleDropdown);
>   };
> }, [isDropdownOpen]);
> 
> <ProfileImg
>   {...}
>   ref={profileRef}
>   onClick={() => setIsDropdownOpen(!isDropdownOpen)}
> />
> ```
> 
> 이 방식으로 리팩토링 해보는건 어떠세요? ProfileDropdown에 ref를 forwardRef 사용하면서까지 넘겨줘야 할 이유가 없을 거 같아서요. 혹시 의도하신 이유가 있다면 알려주세요!

작성해주신 방식을 적용하면 화면 어디를 클릭하든 드롭다운이 열렸다 닫혔다 하는 이슈가 있네요!

2023-11-10 08:18 UTC, kimyoungyin approved these changes

2023-11-17 07:32 UTC, sikkzz approved these changes

2023-11-25 11:19 UTC, merged