139 front task 개인 일정 페이지 오늘 일정
Selody-project/Frontend pull request #142
Opened 2023-10-17 00:46 UTC by kimyoungyin

# 설명

- [#139](개인 일정 페이지-오늘 일정)
- 이슈명은 오늘 일정이지만, 전반적인 schedule state 구조를 여기서 만들어두었다고 보시면 됩니다.
- 렌더링과 관련 없는 순수 함수들은 여러 곳에 사용될 경우 utils 폴더에, 그렇지 않을 경우 해당 컴포넌트 파일에 작성되었습니다.
- schedule의 큰 틀은 `calendarSchedules`, `todaySchedules`, `schedulesForTheWeek`로 구성되며, 각각 달력에 들어갈 요약 일정, 오늘 일정, 일주일 내 예정된 일정입니다.
- `calendarSchedules`는 직접적으로 달력 쪽에 연결되어 있으므로 해당 브랜치(#129)에서 작업할 에정

## 주요 기능1: POST, PUT할 form
일단 convertSchedules 내 유틸 함수들로 state <=> form value로 변경하도록 하였습니다.

### state들 간의 유기적 변화(onChange)
`event.target.value`가 setState시에 필요한 경우 핸들러 함수에서 변경하고, 그게 아니라면 `useEffect`에서 처리하였습니다.

### [validation 방식(노션 참고)](https://www.notion.so/2023-10-13-0d3e2c63708f4806a68607fe2f5f602b?pvs=4#a2880bc4cc6548c88f3506e6fbeda37d): onChange 시 먼저 validate(without toast) => 이후 onSubmit에서 validate(with toast)
- POST: 필요한 요소들이 채워진 경우 '저장하기' 활성화 -> 이후 유기적 로직을 validation
- PUT: useRef에 기존 state를 저장하고, 기존 요소들에서 변경점이 있는지(with [lodash](https://www.npmjs.com/package/lodash)) 확인 및 필요한 요소가 채워져 있으면 '저장하기' 활성화 -> 이후 유기적 로직을 validation

## 주요 기능2: HTTP request
  - GET: 첫 렌더링시 세 종류의 일정을 모두 가져옵니다. `calendarSchedules`의 경우는 달력 state가 변경될 때마다 재호출할 예정(#129)
  - POST: 새로운 일정을 생성하면 response로 전달받은 3개의 데이터를 각각 state에 반영합니다
  - PUT: 기존 일정을 수정하면, prev state에 현재 저장된 동일한 id의 배열 요소를 모두 제거하고, response로 어떤 state에 넣어야 할 지 전달받아 setState합니다
  - DELETE: 기존 일정을 삭제 시, prev state에 있던 동일한 id의 배열 요소를 모두 제거합니다.

# 테스트

- 미작성.. 공부하면서 넣어볼게요

# Demo

2023-10-23 11:57 UTC, sikkzz approved these changes

2023-10-23 11:57 UTC, sikkzz commented on src/components/Base/BaseModal/BaseModal.jsx
> +				<ModalContent title={title} bg={bg}>
bg prop background-color가 맞다면 더 직관적인 이름으로 바꾸는게 좋지 않을까요?

2023-10-23 11:57 UTC, sikkzz commented on src/components/Base/BaseModal/BaseModal.style.js
>  	line-height: normal;
위에 font-size, font-weight theme에서 가져다 써야할 거 같아요

2023-10-23 11:57 UTC, sikkzz commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
> +import React, { useEffect, useRef, useState } from "react";
조금 더 세분화 작업은 어려울까요? 코드가 전체적으로 많이 길다보니 가독성이 많이 떨어지는 거 같아서 기능이나 컴포넌트들 나눠보는게 가능하다면요!

2023-10-23 11:57 UTC, sikkzz commented on src/components/Base/BaseCard/BaseCard.styles.js
> +	border: 1px solid #6c55fe;
theme primary

2023-10-23 11:57 UTC, sikkzz commented on src/components/ScheduleItemList/ScheduleItem/ScheduleItem.styles.js
> +	background-color: ${(props) => props.bgColor};
```css
background-color: ${({ bgColor }) => bgColor};
```
이렇게도 사용 가능하지 않을까요?

2023-10-23 11:57 UTC, sikkzz commented on src/features/schedule/schedule-service.js
>  import { createAsyncThunk } from "@reduxjs/toolkit";
저한테 리뷰 주셨던 commonThunk 적용시킬 수 있는 부분은 시켜보는건 어떨까요

2023-10-23 12:01 UTC, sikkzz commented
코드 전체적으로 블록 구분을 하면 좀 좋을 거 같아요. 코드가 길다보니까 읽기 어려운 부분들이 있는 거 같아서요! 다른 구문끼리는 줄바꿈을 해주면 좋을 거 같고 코드 간소화도 시키면 좋을 거 같아서 한번 고민해보시면 괜찮을 거 같아요!

2023-10-24 00:38 UTC, kimyoungyin commented on src/components/Base/BaseModal/BaseModal.jsx
> +				<ModalContent title={title} bg={bg}>
동의합니다! 기존 코드라 웬만하면 변경하지 않으려 했는데, 살짝 건드려볼까요?

2023-10-24 00:41 UTC, kimyoungyin commented on src/components/ScheduleItemList/ScheduleItem/ScheduleItem.styles.js
> +	background-color: ${(props) => props.bgColor};
전반적으로 해당 프로퍼티를 가져오는 바로 위 객체에서 구조분해 할당을 멈춰 작성하였어서 통일성을 위해 다음과 같이 작성했습니다

2023-10-24 01:14 UTC, kimyoungyin commented on src/components/Base/BaseModal/BaseModal.jsx
> +				<ModalContent title={title} bg={bg}>
bgColor로 변경했습니다

2023-10-24 01:20 UTC, kimyoungyin commented on src/features/schedule/schedule-service.js
>  import { createAsyncThunk } from "@reduxjs/toolkit";
머지 전 미리 반영해둘까요? 혹시 commonThunk는 전체 thunk에서 공통으로 쓰일 것 같은데 어떤 디렉토리에 위치시켜야 할까요?

2023-10-24 01:59 UTC, kimyoungyin commented on src/features/schedule/schedule-service.js
>  import { createAsyncThunk } from "@reduxjs/toolkit";
@sikkzz 일단 준식님 쪽 thunk에 리뷰 남겨두었는데 commonThunk 수정사항 확인해주세요

2023-10-24 06:26 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
> +import React, { useEffect, useRef, useState } from "react";
일단 일차적으로 리팩토링 진행해보았습니다. 컴포넌트를 나누지는 않았고 다음과 같이 진행해보았어요. 그래도 컴포넌트를 분리하는 게 나아보이면 말씀해주세요!
- useEffect 로직 삭제
- 상수나 함수들을 재정렬
- 주석으로 설명

2023-10-24 08:56 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
> +import React, { useEffect, useRef, useState } from "react";
+ 컴포넌트도 3가지로 분리해봤습니다
- DateAndTime: 시작~종료 시간
- Repeat: 반복 여부 및 반복 종료 여부/시간
- Repeat: N 설정 및 interval 설정

2023-11-02 17:40 UTC, 2Junsu requested changes
추가적으로 아래 4가지 내용도 확인해주세요!
1. 피그마 시안 상 예정 탭에서는 일정 추가 버튼이 안 보이도록 해야할 것 같아요
2. 일정을 추가하면 undefined로 표시되네요
![스크린샷 2023-11-03 오전 2 35 35](https://github.com/Selody-project/Frontend/assets/77619905/5f7ab321-e448-4e2e-8cc9-c02c7eea8e4b)
3. 아래의 경우, 일정 추가가 안 됩니다

https://github.com/Selody-project/Frontend/assets/77619905/8930a542-4d23-410c-a39c-94a9e2cb9928

4. 페이지 새로고침 시 달력에 표시된 일정이 사라집니다

2023-11-02 17:40 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
> +	});
저는 보통 map 함수랑 return을 같이 안 쓰는 거로 알고 있는데 혹시 맞다면 아래처럼 바꿔도 좋을 것 같네요
```js
const fullCalendarEvents = calendarSchedules.map((schedule) =>
		schedule.recurrence
			? {
					id: schedule.id,
					userId: schedule.userId,
					daysOfWeek: schedule.byweekday,
					startTime: new Date(schedule.startDateTime),
					endDateTime: new Date(schedule.endDateTime),
					startRecur: new Date(schedule.startRecur),
					endRecur: new Date(schedule.until),
			  }
			: {
					id: schedule.id,
					userId: schedule.userId,
					title: schedule.title,
					start: new Date(schedule.startDateTime),
					end: new Date(schedule.endDateTime),
			  },
	);
```

추가로 새로고침 시에 fullCalendarEvents에 아무 값도 들어있지 않아서 달력에 표시가 안 되는 것 같아요
![스크린샷 2023-11-03 오전 12 30 53](https://github.com/Selody-project/Frontend/assets/77619905/5b264064-c725-463a-8678-fb85d57cc3ed)

2023-11-02 17:40 UTC, 2Junsu commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +					value={getSelectValue(currentView, year, month, week)}
리스트뷰일 때도 주차 표시가 안 되는 것 같아요
![스크린샷 2023-11-03 오전 1 14 24](https://github.com/Selody-project/Frontend/assets/77619905/e098debf-f5b1-4cc7-b749-36e13981f73b)

2023-11-02 17:40 UTC, 2Junsu commented on src/components/Common/ScheduleModal/CustomSelect/CustomSelect.styles.js
> +	padding: 0 8px;
피그마 시안대로 잘 구현하셨지만, 상하 패딩도 있으면 어떨까 싶기도 하네요..!

2023-11-02 17:40 UTC, 2Junsu commented on src/components/Common/ScheduleModal/RepeatDetail.jsx
> +				</ByweekdayPickerDiv>
중요한 것도 아니고 필수도 아닌 단순 의견인데, 보통 ENG, KR로 많이 표시하니까 EN -> ENG로 바꾸는 것도 알아보기 쉬워보이네요

2023-11-02 17:40 UTC, 2Junsu commented on src/components/Common/ScheduleModal/RepeatDetail.jsx
> +				</ByweekdayPickerDiv>
수, 금요일에 반복하도록 생성했는데 화, 목요일에 생성되네요!
![스크린샷 2023-11-03 오전 1 46 24](https://github.com/Selody-project/Frontend/assets/77619905/a34b9094-70a9-4eb1-a49b-6d4889e117d5)

2023-11-02 17:40 UTC, 2Junsu commented on src/features/ui/ui-slice.js
모달 별로 리듀서를 분리하신 이유가 궁금합니다

2023-11-02 17:40 UTC, 2Junsu commented on src/components/SharePage/ShareTodoList/ShareTodoList.jsx
> +import { UI_TYPE } from "@/constants/uiConstans.js";
uiConstants의 오타일까요?

2023-11-02 17:40 UTC, 2Junsu commented on src/components/SharePage/ShareTodoList/ShareTodoList.jsx
> +										<ScheduleItem key={Math.random().toString()} schedule={s} />
1. s 대신 schedule과 같은 이름으로 변경하면 좋겠네요!
2. {return ()} 대신 바로 ()로 사용하는 게 낫겠네요

2023-11-02 17:40 UTC, 2Junsu commented on src/features/schedule/schedule-service.js
> +					url: `/api/${!isGroup ? "user" : `group/${groupId}`}/calendar`,
summary api가 쓰여야 하는 것 아닌가요?? 잘못 이해했다면 설명 부탁드립니다!

2023-11-03 00:41 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/RepeatDetail.jsx
> +				</ByweekdayPickerDiv>
- 보통 2글자로 EN, KR 표시하지 않나요? ㅋㅋ
- 캘린더에 반영되는 건 고려하지 않으셔도 됩니다! 129번에서 추후 작업 예정입니다(궁금하실까봐 설명 드리면, UTC 시간 기준 요일이 밀릴 수 있어서 그렇습니다)

2023-11-03 00:43 UTC, kimyoungyin commented on src/components/SharePage/ShareTodoList/ShareTodoList.jsx
> +										<ScheduleItem key={Math.random().toString()} schedule={s} />
이 부분은 공유 일정에서 진행할 예정입니다!
변경 사항은 에러가 나지 않은 선에서만 수정한 거라고 보시면 됩니다

2023-11-03 01:01 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CalendarContainer.jsx
> +	});
- 왼쪽 달력은 신경 안쓰셔도 됩니다 머지 후 추후 #129 에서 구현 예정입니다

- return 키워드는 저희 frontend 컨벤션에 작성하기로 하지 않았나 싶었는데, 바로 수정할게요

2023-11-03 01:56 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +					value={getSelectValue(currentView, year, month, week)}
아 그렇네요 수정하였습니다

2023-11-03 01:58 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/CustomSelect/CustomSelect.styles.js
> +	padding: 0 8px;
저도 고민되긴 합니다.. 지수님과 같이 회의 떄 얘기해보죠!

2023-11-03 02:05 UTC, kimyoungyin commented on src/features/ui/ui-slice.js
모달의 종류가 많아질 텐데 각각을 하나의 reducer 내부에서 전부 처리하면 reducer 하나가 너무 복잡해질 것 같아 이렇게 구현해보았습니다. 

각 모달당 필요한 로직도 조금씩 다를 수 있기 때문이기도 합니다
+ action에 담아줄 parameter 수도 줄어들게 됩니다

2023-11-03 02:06 UTC, kimyoungyin commented on src/components/SharePage/ShareTodoList/ShareTodoList.jsx
> +import { UI_TYPE } from "@/constants/uiConstans.js";
아 수정했습니다

2023-11-03 02:15 UTC, kimyoungyin commented on src/features/schedule/schedule-service.js
> +					url: `/api/${!isGroup ? "user" : `group/${groupId}`}/calendar`,
이 부분은 형식만 구현해놓고 #129 에서 진행하려했는데 하는 김에 미리 변경해놓는게 낫겠네요. 
변경했습니다!

2023-11-03 02:17 UTC, kimyoungyin commented on src/features/schedule/schedule-service.js
> +					url: `/api/${!isGroup ? "user" : `group/${groupId}`}/calendar`,
근데 아직 이 thunk를 사용하는 곳은 없는 점 참고 부탁드려요

2023-11-03 02:23 UTC, kimyoungyin commented
> 추가적으로 아래 4가지 내용도 확인해주세요!
> 
> 1. 피그마 시안 상 예정 탭에서는 일정 추가 버튼이 안 보이도록 해야할 것 같아요
> 2. 일정을 추가하면 undefined로 표시되네요
>    ![스크린샷 2023-11-03 오전 2 35 35](https://user-images.githubusercontent.com/77619905/280079670-5f7ab321-e448-4e2e-8cc9-c02c7eea8e4b.png)
> 3. 아래의 경우, 일정 추가가 안 됩니다
> 
>  2023-11-03.2.37.03.mov 
> 4. 페이지 새로고침 시 달력에 표시된 일정이 사라집니다


1. 근데 우측 상단 '일정 추가' 버튼은 계속 있어야 하지 않을까요? 그게 없으면 굳이 '오늘' 탭으로 돌아와야 하는 번거로움이 있을 것 같은데 어떻게 생각하시나요?
2. 추후 #129 에서 구현 예정입니다!
3. 매주, N주 간격마다 반복되는 일정이 아닌 반복일정에 경우에도 byweekday가 채워지는 오류가 있었네요.. 수정했습니다.
4. 이건 가져오는 thunk 연결을 안해두어서 그렇습니다. #129 에서 진행할게요!

2023-11-03 14:11 UTC, sikkzz requested changes

2023-11-03 14:11 UTC, sikkzz commented on src/components/Common/ScheduleModal/DateAndTime.jsx
> +const TIME_PICKER_TYPE = {
constants로 빼는건 어떠세요?

2023-11-03 14:11 UTC, sikkzz commented on src/components/Common/ScheduleModal/ScheduleModal.styles.js
한 style 파일에 다 정의하신 이유가 있으실까요? 겹치는건 share로 작성하고 따로 구분하는건 어떤가 싶어서요!

2023-11-03 14:11 UTC, sikkzz commented on src/components/Common/ScheduleModal/Repeat.jsx
> +];
관련 데이터도 constants로 빼도 괜찮지 않을까요?

2023-11-03 14:11 UTC, sikkzz commented on src/components/Common/ScheduleModal/RepeatDetail.jsx
> +	return "년";
이런 부분도 필수적이지는 않지만 상수로 빼놓아도 괜찮을 거 같아요

2023-11-03 14:11 UTC, sikkzz commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
> +import React, { useEffect, useRef, useState } from "react";
컴포넌트를 더 분리시킨다고 가독성이 늘어날지 저도 확신이 들지는 않아서 필요성을 느끼시면 진행하고 아니면 유지해도 될 거 같아요

2023-11-03 14:11 UTC, sikkzz commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
> +import React, { useEffect, useRef, useState } from "react";
전체적으로 에러 메시지나 텍스트들 필요성 느끼는 부분은 constants 처리만 해주시면 좋을 거 같네요!

2023-11-03 14:11 UTC, sikkzz commented on src/components/Common/ScheduleModal/ScheduleModal.styles.js
컴포넌트 조금 분리하면서 사용되는 style들이 다른 부분들도 있는거 같아서요

2023-11-03 14:11 UTC, sikkzz commented on src/components/ScheduleItemList/ScheduleItem/ScheduleItem.jsx
> +				bgColor={isGroup ? colors.sunday : colors.disabled_text}
다른 부분에서까지 사용되는 컴포넌트가 아니다 보니까 인라인에서 조건부 보다는 style 파일에서 조건부 스타일링 진행하는게 어떤가요? 제가 사용하는 방식이라 말씀드리는거지만 뭐가 더 낫다의 느낌으로 말씀드리는건 아니라서 이유가 있으면 알려주시면 감사하겠습니다.

```jsx
<ColoredCircleDiv
  isGroup={isGroup}
/>
```

```css
background-color: ${({isGroup, theme: {colors} }) => isGroup ? colors.sunday : colors.disabled_text};
```

2023-11-03 14:11 UTC, sikkzz commented on src/components/ScheduleItemList/ScheduleItem/ScheduleItem.jsx
> +				bgColor={isGroup ? colors.sunday : colors.disabled_text}
해당 방식으로 사용하면 위에 useTheme도 사용하지 않아도 될 거 같네요

2023-11-03 14:11 UTC, sikkzz commented on src/components/ScheduleItemList/ScheduleItemList.jsx
> +						notification: "NO",
ScheduleModal쪽에서는 따로 사용이 안되고 있는 코드 같은데 이유가 있을까요?

2023-11-03 14:11 UTC, sikkzz commented on src/features/schedule/schedule-service.js
commonThunk로 리팩토링 진행한 부분 감안하면 error message 로직들 수정해야 할 부분들이 있는 거 같네요

2023-11-03 14:12 UTC, sikkzz commented
전체적으로 에러메시지나 텍스트들 constants로 빼는거 고려해보시면 좋을 거 같아요! 이외에는 공유 일정 들어가시면 리뷰 한번 더 해드리면 좋을 거 같습니다.

2023-11-07 01:53 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/Repeat.jsx
> +];
여러 곳에서 재사용해야 하는 상수의 경우에만 constants로 뺴야 한다는 생각이었습니다.
해당 컴포넌트 안에서만 사용할 거라 일부러 안 뺐는데, 아예 이런 것들 따로 다 constants에 분리해두는 게 나으려나요?

2023-11-07 01:53 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/DateAndTime.jsx
> +const TIME_PICKER_TYPE = {
이것도 딱 여기서만 쓰는 거라 따로 분리하진 않았습니다. 어떤가요?

2023-11-07 01:54 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/RepeatDetail.jsx
> +	return "년";
이것도 해당 컴포넌트에서만 사용되는 상수라 가까운 곳에 위치시키는 게 좋을 것 같아 한 파일에 정리했는데,
분리해야 할까요?

2023-11-07 02:00 UTC, kimyoungyin commented on src/components/ScheduleItemList/ScheduleItem/ScheduleItem.jsx
> +				bgColor={isGroup ? colors.sunday : colors.disabled_text}
아 근데 저 부분은 추후에 그룹 일정 추가도 구현되면 저렇게 할 수밖에 없는게, 
제가 그룹일정을 sunday 색 처리한 건 임시 방편입니다. 나중에 `useTheme`은 삭제될 것 같아요.

개인 일정 쪽에서도 본인이 속한 그룹의 일정들도 다 나오는 상황에서 랜덤으로 그룹 색깔을 부여하게 되는데
이 떄 prop으로 bgColor를 넣어주게 됩니다. 그렇기 때문에 `isGroup`은 랜덤 색을 다루는 컴포넌트 파일에서 동일하게 다루는 게 맞을 것 같습니다!

2023-11-07 02:03 UTC, kimyoungyin commented on src/components/ScheduleItemList/ScheduleItemList.jsx
> +						notification: "NO",
아 이런.. 수정했습니다

2023-11-07 02:18 UTC, kimyoungyin commented on src/features/schedule/schedule-service.js
아 try catch를 한 번 더 썼었네요.. 수정했습니다

2023-11-07 07:39 UTC, sikkzz commented
> 전체적으로 에러메시지나 텍스트들 constants로 빼는거 고려해보시면 좋을 거 같아요! 이외에는 공유 일정 들어가시면 리뷰 한번 더 해드리면 좋을 거 같습니다.

내부 파일들이 전체적으로 길다보니까 빼는게 어떨까 생각했던거라 전체 상수들 모두 편하신대로 작성해도 괜찮을 거 같습니다

2023-11-26 10:14 UTC, sikkzz approved these changes

2023-11-29 08:50 UTC, merged