136 front task 설정 페이지 구현
Selody-project/Frontend pull request #143
Opened 2023-10-25 20:04 UTC by 2Junsu

# 설명

- #136 
- BaseModal
  - bg 대신 style로 받도록 수정
  - X 버튼 필요 없을 때 hasClose에 false 부여
- useAxios 훅 추가

# 테스트

-

# Demo

2023-11-03 09:55 UTC, sikkzz requested changes

2023-11-03 09:55 UTC, sikkzz commented on src/components/Setting/CustomInput/CustomInput.jsx
> +	const { gap = 30 } = inputProps;
PasswordTab에서 gap을 어차피 받는 걸 고려하면 이렇게 하기보다는 UserInfo에서도 gap={30}을 받는게 낫지 않을까요? 속성들을 차라리 일관적으로 받아주는게 더 이해하기 편할 거 같아서요!

2023-11-03 09:55 UTC, sikkzz commented on src/components/Setting/GroupModals/GroupModals.jsx
각 modal 종류들 파일을 나눠서 작성해놓는 방향성은 별로일까요?

2023-11-03 09:55 UTC, sikkzz commented on src/components/Setting/GroupScheduleItem/GroupScheduleItem.jsx
> +			if (type === "shareScheduleOption") {
Option contants에서 상수로 관리하는게 좋을 거 같아요!

2023-11-03 09:55 UTC, sikkzz commented on src/components/Setting/GroupScheduleItem/GroupScheduleItem.jsx
> +						handleClickToggle("shareScheduleOption");
option 동일

2023-11-03 09:55 UTC, sikkzz commented on src/components/Setting/GroupScheduleItem/GroupScheduleItem.jsx
> +						handleClickToggle("notificationOption");
option 동일

2023-11-03 09:55 UTC, sikkzz commented on src/components/Setting/GroupScheduleItem/GroupScheduleItem.style.js
> +export const TitleSpan = styled.span``;
특별한 속성이 없다면 제거하고 시멘틱 태그로 작성하면 되지 않을까요?

2023-11-03 09:55 UTC, sikkzz commented on src/components/Setting/GroupScheduleSetting/GroupScheduleSetting.jsx
> +	const { response, error, isLoading, refetch } = useAxios({
useAxios 관련은 로그인 issue에서 내용 확인했었는데 보통 토큰 관련 작업에서 많이 사용한다고 하더라구요. 해당 기능에서 이 방식을 사용하는데 이점이 있을까요? 있으면 다른 api 관련 기능들에서도 리팩토링의 여지가 있나 싶어서요!

2023-11-03 09:55 UTC, sikkzz commented on src/components/Setting/UserInfo/UserInfo.style.js
> +	${({ spaceBetween }) =>
```css
justify-content: ${({ spaceBetween }) =>
		spaceBetween ? "space-between" : "flex-start"};
```

2023-11-03 09:55 UTC, sikkzz commented on src/components/Setting/UserInfo/UserInfo.style.js
> +	${({ spaceBetween }) =>
이렇게 작성 가능할 거 같은데 어떠세요?

2023-11-03 09:55 UTC, sikkzz commented on src/components/Setting/WithdrawalTab/WithdrawalTab.jsx
> +				<BaseModal
이부분 modal 나중에 변경되면 컴포넌트화 하는게 좋을 거 같아요.

2023-11-03 09:55 UTC, sikkzz commented on src/features/auth/auth-service.js
commonThunk 사용해서 간소화 진행해야 할 거 같아요

2023-11-03 09:55 UTC, sikkzz commented on src/features/group/group-service.js
commonThunk

2023-11-03 09:55 UTC, sikkzz commented on src/components/Header/Header/Header.jsx
```jsx
const closeDropdown = (e) => {
  const { target } = e;

  if (!profileRef.current.contains(target)) {
    setIsDropdownOpen(false);
  }
};

<ProfileImg
  ref={profileRef}
  onClick={() => setIsDropdownOpen(!isDropdownOpen)}
  src="https://yt3.ggpht.com/ytc/AOPolaSlb8-cH_rN_lZDD1phXr7aHFpoOqMVoepaGuTm=s48-c-k-c0x00ffffff-no-rj"
  alt="user-profile"
/>

```

이렇게 작성하면 forwardRef랑 dropdownRef 사용 안해도 가능할 거 같은데 어떠신가요?

2023-11-06 18:09 UTC, 2Junsu commented on src/components/Setting/GroupScheduleSetting/GroupScheduleSetting.jsx
> +	const { response, error, isLoading, refetch } = useAxios({
음..우선 useAxios 훅을 만든 이유는 #127 이슈에서 `중복 확인 기능은 redux를 사용하지 않으니까 thunk에서 사용하는 것보단 다른 방식으로 사용하는 게 좋겠다` 라는 코멘트에서 시작됐어요
이 훅을 만듦으로써 thunk에서 통신하지 않는 api들을 모두 useAxios로 관리하고자 했습니다!

2023-11-06 18:19 UTC, 2Junsu commented on src/components/Setting/GroupModals/GroupModals.jsx
아 그게 나으려나요? 저는 style 파일에 컴포넌트들 모아놓고 쓰는 것처럼 여기도 모아봤는데 가독성이 떨어져 보일까요?

2023-11-13 08:57 UTC, kimyoungyin requested changes

2023-11-13 08:57 UTC, kimyoungyin commented on __test__/pagesTest/SettingPage.test.jsx
- mockStore 만들 필요 없이 그대로 render 쓰시면 됩니다. [제가 정리했던 링크](https://www.notion.so/2fc0cf39dfe14b0187d5df8d920092a8?pvs=4#a2bc97a0d0274db7807ec129785eef0b)
- testId보단 role로 부탁드립니다

2023-11-13 08:57 UTC, kimyoungyin commented on src/components/Base/BaseModal/BaseModal.jsx
일단 이 부분은 나중에 머지하고 같이 구현해봐요

2023-11-13 08:57 UTC, kimyoungyin commented on src/pages/SettingPage/SettingPage.jsx
> +	const selectedTabList = [<ProfileTab />, <PasswordTab />, <WithdrawalTab />];
- 각각이 그런지는 모르겠는데, 굳이 스크롤할 필요 없는 높이를 가졌음에도 스크롤이 되버리는 현상이 있어서 해당 부분 수정 부탁드립니다!
- 그럼에도 불구하고 스크롤이 되어야 되는 높이를 가진 window에서는, selectedTab이 변경 될 때마다 scroll to top 처리해주셔야 될 것 같습니다. 아니면 각 탭마다 스크롤했던 위치를 %로 기억해둬도 되구요

2023-11-13 08:57 UTC, kimyoungyin commented on src/pages/SettingPage/SettingPage.jsx
> +	const [selectedTab, setSelectedTab] = useState(0);
selectedTabIndex 혹은 selectedTabeIdx가 나아보입니다!

2023-11-13 08:57 UTC, kimyoungyin commented on src/components/Setting/UserInfo/UserInfo.jsx
> +				<ProfileImg src={newProfileImg} alt="profile-img" />
프로필 이미지가 보이지 않는 에러가 있습니다!
![스크린샷 2023-11-10 오후 5 53 24](https://github.com/Selody-project/Frontend/assets/78777345/6e70f5fa-4bdb-4299-bcc2-f6751b767d1c)

2023-11-13 08:57 UTC, kimyoungyin commented on src/components/Setting/WithdrawalTab/WithdrawalTab.style.js
> +	padding: 88px 160px;
여기 너무 패딩이 큰 것 같은데 수정 가능할까요? 브라우저 너비가 충분한데도 text-wrap이 되서요!

2023-11-13 08:57 UTC, kimyoungyin commented on src/components/Setting/WithdrawalTab/WithdrawalTab.jsx
> +	};
`drawal`은 오타일까요? 어떤 걸 의미하나요?
async만 붙이고 await를 사용하지 않은 이유가 있을까요?

2023-11-13 08:57 UTC, kimyoungyin commented on src/features/commonThunk.js
> +};
이 부분 조금 개선해야 할 것 같습니다. 예상치 못한 에러의 경우는 message를 띄워야 합니다!

2023-11-13 08:57 UTC, kimyoungyin commented on src/features/group/group-service.js
여기 commonThunk 적용해야겠네요!

2023-11-13 08:57 UTC, kimyoungyin commented on src/features/group/group-slice.js
> +	refetchUserGroup: true,
boolean 타입이니 동사형으로 하는게 어떠세요?
`isUserGroupRefetching`

2023-11-13 08:57 UTC, kimyoungyin commented on src/components/Setting/GroupModals/GroupModals.jsx
> +	};
여기는 내부적 state도 promise 결과에 따라 관리하려면 `unwrap()` 처리하는 게 낫지 않을까요?

2023-11-13 08:57 UTC, kimyoungyin commented on src/components/Setting/GroupModals/GroupModals.jsx
> +	};
여기도요!

2023-11-13 08:57 UTC, kimyoungyin commented on src/components/Setting/GroupModals/GroupModals.jsx
> +	};
여기도 마찬가지 아닐까요?

2023-11-13 08:57 UTC, kimyoungyin commented on src/components/Setting/PasswordTab/PasswordTab.jsx
> +	};
현재 비밀번호가 맞는지 확인하는 로직이 선행되어야 할 것 같습니다.
3개의 Input을 입력했을 때 유효성 검사는 그 순서대로 이루어져야 하는데, 현재 비밀번호가 맞지 않더라도 새 비밀번호에 대한 매칭 검사를 먼저 하게 됩니다.

2023-11-16 17:43 UTC, 2Junsu commented on src/pages/SettingPage/SettingPage.jsx
> +	const selectedTabList = [<ProfileTab />, <PasswordTab />, <WithdrawalTab />];
헤더랑 탭 사이 간격이 너무 넓은 거 같아서 스크롤할 때 일정 길이 같이 스크롤되게 했었는데, 다시 보니까 그냥 고정되는 게 나을 것 같네요!
둘다 수정했습니다.

2023-11-16 17:43 UTC, 2Junsu commented on src/components/Setting/UserInfo/UserInfo.jsx
> +				<ProfileImg src={newProfileImg} alt="profile-img" />
에러 재현이 안 되는데 어떤 경우인가요?

2023-11-16 17:43 UTC, 2Junsu commented on src/components/Setting/WithdrawalTab/WithdrawalTab.jsx
> +	};
withdraw는 동사이고 withdrawal은 명사예요
async는 실수로 안 지워서 지웠습니다!

2023-11-16 17:43 UTC, 2Junsu commented on src/components/Setting/PasswordTab/PasswordTab.jsx
> +	};
api에서는 `현재 비밀번호`가 정확히 입력됐고 `새 비밀번호`가 10자 이상이면, `새 비밀번호 확인` 인풋값에 관계없이 비밀번호 정상 수정 처리를 해요

따라서 `새 비밀번호`랑 `새 비밀번호 확인` 일치 여부는 api 통신이 성공되기 전에 확인해야하는데, 통신이 성공하면 바로 수정이 돼서 고칠 수 없다고 판단됩니다ㅠㅠ

혹시 다른 방안이 떠오르시나요??

새 비밀번호 먼저 판별하는 것도 크게 문제 있어보이진 않습니다

2023-11-17 05:47 UTC, kimyoungyin commented on src/components/Setting/PasswordTab/PasswordTab.jsx
> +	};
아 api가 그렇게 구현되어 있었나요?? api 수정이 필요할 것 같아요
일단 지금은 그대로 가고,
제가 아직 도커로 배포하는 부분을 막 건드릴 수 없어서 제가 배포 가능해진다면 이후에 따로 브랜치 파서 진행해봐요 
## 개선점
- '변경 정보 저장하기` 버튼은 새 비밀번호, 새 비밀번호 확인이 10자 이상이 아니면 비활성화될 것(물론 api에서도 검사한다는 전제)

## api 개선점
- PATCH에 담아보낼 데이터는 현재 비밀번호, 새로운 비밀번호, 새로운 비밀번호 확인 3가지
- 검사 순서
  - 현재 비밀번호가 맞는지를 먼저 검사: 틀리면 현재 비밀번호 불일치 에러
  - 이후 새 비밀번호, 새 비밀번호 확인의 길이 확인: 10자 이하면 길이 에러(이건 유저가 프론트 validate를 뚫고 왔을 경우)
  - 이후 비밀번호가 새 비밀번호와 다른지 검사: 같다면 비밀번호 동일 에러
  - 이후 새 비밀번호, 새 비밀번호 확인이 같은지 검사: 다르다면 불일치 에러

2023-11-17 06:20 UTC, kimyoungyin commented on src/components/Setting/UserInfo/UserInfo.jsx
> +				<ProfileImg src={newProfileImg} alt="profile-img" />
혹시 준수님 계정은 로컬이신가요?
저는 로컬로 로그인했다보니 기본 이미지가 보여야 되는데 접근이 안되는 것 같습니다.

2023-11-17 06:25 UTC, kimyoungyin commented on src/pages/SettingPage/SettingPage.jsx
> +	const selectedTabList = [<ProfileTab />, <PasswordTab />, <WithdrawalTab />];
https://github.com/Selody-project/Frontend/assets/78777345/f432e7e1-5fe0-42c4-8474-e14af9571859

계속 스크롤되는 것 같아요 ㅠㅠ

2023-11-17 07:31 UTC, sikkzz requested changes

2023-11-17 07:31 UTC, sikkzz commented on src/components/Setting/GroupModals/GroupModals.jsx
한 파일에 모아놓았을 때 이점이 없는 거 같아서요! 추후에 리팩토링을 통해 겹치는 로직이나 코드들을 컴포넌트화해서 하나의 파일로 두면 좋은데 지금은 나눠 놓는게 더 파일별로 코드를 깔끔하게 볼 수 있다는 생각이 들었어요

2023-11-25 13:33 UTC, merged