issue #144 design: move notification button to Header
Selody-project/Frontend pull request #145
Opened 2023-10-26 06:16 UTC by 2Junsu

# 설명

- #144 
- FEED IN SELODY 내에 있던 알림 탭을 헤더로 이동

# 테스트

-

# Demo

https://github.com/Selody-project/Frontend/assets/77619905/a1222690-5c03-40aa-a7f7-d7db0156eac8

2023-11-03 10:19 UTC, sikkzz commented
```jsx
const handleDropdown = (e) => {
  const { target } = e;

  if (isProfileDropdownOpen && !profileRef.current.contains(target)) {
    setIsProfileDropdownOpen(false);
  }
};

const handleNotification = (e) => {
  const { target } = e;

  if (isNotiDropdownOpen && !notiRef.current.contains(target)) {
    setIsNotiDropdownOpen(false);
  }
};

useEffect(() => {
  window.addEventListener("click", handleDropdown);

  return () => {
    window.removeEventListener("click", handleDropdown);
  };
});

useEffect(() => {
  window.addEventListener("click", handleNotification);

  return () => {
    window.removeEventListener("click", handleNotification);
  };
});

<NotificationDiv>
  <NotificationButton
    ref={notiRef}
    onClick={() => {
      setIsNotiDropdownOpen(!isNotiDropdownOpen);
    }}
  >
    <NotificationIcon />
  </NotificationButton>
  {isNotiDropdownOpen && <NotificationDropdown />}
</NotificationDiv>

<ProfileDiv>
  <ProfileImg
    ref={profileRef}
    src="https://yt3.ggpht.com/ytc/AOPolaSlb8-cH_rN_lZDD1phXr7aHFpoOqMVoepaGuTm=s48-c-k-c0x00ffffff-no-rj"
    alt="user-profile"
    onClick={() => {
      setIsProfileDropdownOpen(!isProfileDropdownOpen);
    }}
  />
  {isProfileDropdownOpen && <ProfileDropdown />}
</ProfileDiv>
```

여기도 이렇게 작성하면 fowardRef랑 불필요 ref 제거하고 사용할 수 있을 거 같아요

2023-11-14 00:47 UTC, kimyoungyin requested changes

2023-11-14 00:47 UTC, kimyoungyin commented on src/components/Header/SubHeader/SubHeader.jsx
> +		</SubHeaderDiv>
FEED IN SELODY 아래 SubHeader의 시작지점이 FEED IN SELODY 왼쪽과 맞아야하는데 왼쪽으로 너무 치우쳐진 것 같아요 수정부탁드립니다!

2023-11-14 00:47 UTC, kimyoungyin commented on src/components/Header/SubHeader/SubHeader.jsx
>  			  ];
마이페이지 접근 시 오류가 나는데 정상인가요?

2023-11-14 00:47 UTC, kimyoungyin commented on src/components/Header/Header/Header.jsx
> +					</NotificationDiv>
여기랑 양쪽 사이 공간이 figma 시안보다 넓은 것 같아요!
버튼 사이즈까지 고려해서 줄여주면 좋을 것 같습니다

2023-11-16 06:40 UTC, 2Junsu commented on src/components/Header/SubHeader/SubHeader.jsx
>  			  ];
네 여기선 연결된 게 없어서 정상입니다!

2023-11-16 07:48 UTC, kimyoungyin submitted a review, later dismissed

2023-11-17 07:23 UTC, sikkzz submitted a review, later dismissed

2023-11-25 11:23 UTC, sikkzz approved these changes

2023-11-25 11:23 UTC, merged