147 front task 랜딩페이지 개선
Selody-project/Frontend pull request #148
Opened 2023-11-15 08:45 UTC by kimyoungyin

# 설명

- #147 
- 랜딩페이지 퍼블리싱(디렉토리 수정도 진행)

## 반응형 디자인
- 그라데이션이 적용된 background는 100%
- `LandingHeader`, `LandingMain`의 최대 너비는 `1440px`로 제한
- `768px` 이하의 경우 `LandingMain`의 정렬이 column으로 변경

## typing library 변경([react-type-animation](https://www.npmjs.com/package/react-type-animation#react-type-animation))
저는 한 번 타이핑 된 후 유지되는 것을 원했는데,

기존에 사용되었던 방식은 '**무조건** 텍스트가 지워져야 하는(infinity)` 문제가 있어서 대체했습니다.

## 애니메이션
기존에 [framer-motion](https://www.framer.com/motion/)을 사용하여 구현이 되어 있었으며, 해당 애니메이션을 그대로 이어감

main.content의 경우: 첫 줄 -> 두 번째 줄 -> 시작하기 버튼

순으로 보이도록 시간 조정

## `SelodyLogo` 재사용
`iconConstants`로 svg를 사용하지 않고(어차피 재사용할 건 SelodyLogo 컴포넌트임), `SelodyLogo` 컴포넌트를 만들어 필요한 곳에 대체하였습니다.

`prop`으로는 `size`를 받습니다.

# 테스트

initial render에 대한 테스트 진행

# Demo
## `768px` 이하
![스크린샷 2023-11-15 오후 5 40 49](https://github.com/Selody-project/Frontend/assets/78777345/b01d2eb9-078e-4a21-b216-07d159f51739)

## ~`1440px`
![스크린샷 2023-11-15 오후 5 41 29](https://github.com/Selody-project/Frontend/assets/78777345/a91c9dd2-ef17-48fa-a8cb-5f612ce672f0)

## 그 이상의 너비
![스크린샷 2023-11-15 오후 5 42 12](https://github.com/Selody-project/Frontend/assets/78777345/f0d8ebbd-7de2-4a24-bfbd-d5dc8a5bf59a)

2023-11-20 09:42 UTC, sikkzz requested changes

2023-11-20 09:42 UTC, sikkzz commented on src/components/Landing/LandingMain/LandingMain.jsx
motion 속성들 따로 정의해놓고 variants props로 넘겨서 사용할 수 있는거로 알고 있어요. 인라인 코드들 깔끔하게 정리하고 싶으시면 한번 사용해보셔도 좋을 거 같아요

2023-11-20 09:42 UTC, sikkzz commented on src/components/Landing/LandingMain/LandingMain.styles.js
> +			}) => weight.regular};
제거해도 될 거 같아요 400 default 값이라

2023-11-20 09:42 UTC, sikkzz commented on src/styles/GlobalStyles.js
> -			margin: 0 auto;
이 코드 제거하면 다른 모든 페이지에서도 max-width가 사라져서 width 100%로 잡혀버릴텐데 지우면 안되지 않을까요? 현재 반응형 작업이 없다 보니 모든 작업들이 1440px 기준으로만 작업된 상태라 유지해야 할 거 같아요

2023-11-21 12:45 UTC, kimyoungyin commented on src/components/Landing/LandingMain/LandingMain.styles.js
> +			}) => weight.regular};
상위에서 weight를 설정해둔 터라 유지하는게 맞습니다!
그런데 오늘 회의에서 진하게 하기로 했으니 결과적으로 지우게 되겠네요!

지웠습니다!

2023-11-22 01:20 UTC, kimyoungyin commented on src/styles/GlobalStyles.js
> -			margin: 0 auto;
아 그럴 수 있겠군요..
일단 원상복구했습니다.

2023-11-22 02:01 UTC, kimyoungyin commented on src/components/Landing/LandingMain/LandingMain.jsx
제가 알아보니 오히려 variant로하면  오히려 애니메이션 코드 양이 많아지는 것 같아서

그냥 prop 객체를 return하는 함수를 만들어 분리 후 spread 처리해보았습니다. 확인 부탁드려요!

2023-11-26 10:15 UTC, sikkzz approved these changes

2023-11-27 06:31 UTC, merged