issue #153 refactor: navigate landing, userLoading state refactoring
Selody-project/Frontend pull request #154
Opened 2023-11-27 08:50 UTC by sikkzz

# 설명

- [https://github.com/Selody-project/Frontend/issues/153](https://github.com/Selody-project/Frontend/issues/153)
- 로그아웃시 랜딩페이지로 이동 안되는 오류 수정
- auth slice state 변수명 수정

2023-11-27 08:55 UTC, kimyoungyin requested changes
auth-slice에서도 userLoading -> isLoading 부탁드립니다

2023-11-27 08:58 UTC, kimyoungyin approved these changes

2023-11-28 00:06 UTC, kimyoungyin requested changes
기본 auth.isLoading을 true로 바꿔주셔야 깜빡임이 사라질 것 같아요

2023-11-28 10:27 UTC, sikkzz commented
> 기본 auth.isLoading을 true로 바꿔주셔야 깜빡임이 사라질 것 같아요

어떤 깜빡임인지 알려주실 수 있을까요?

2023-11-29 06:40 UTC, kimyoungyin requested changes
```js
	if (isLoading && !user) {
		return <p>Loading,,,</p>;
	}
	if (!user) {
		return <Navigate to="/landing" />;
	}
```
이런 식으로 하던가 isRefreshing state를 하나 만들어주던가 해야 할 것 같아요.
굳이 토큰 재발급이 아니라 비밀번호 변경이나 다른 유저 정보 변경 시도 시에도 `isLoading = true`가 되는데,
그 때도 로딩화면이 떠버리네요 ㅠ

2023-11-30 06:28 UTC, sikkzz commented
> ```js
> 	if (isLoading && !user) {
> 		return <p>Loading,,,</p>;
> 	}
> 	if (!user) {
> 		return <Navigate to="/landing" />;
> 	}
> ```
> 
> 이런 식으로 하던가 isRefreshing state를 하나 만들어주던가 해야 할 것 같아요. 굳이 토큰 재발급이 아니라 비밀번호 변경이나 다른 유저 정보 변경 시도 시에도 `isLoading = true`가 되는데, 그 때도 로딩화면이 떠버리네요 ㅠ

해당 방식으로 리팩토링 진행 할게요

2023-12-01 11:18 UTC, kimyoungyin approved these changes

2023-12-01 11:19 UTC, merged