138 front task 커뮤니티 페이지 구현
Selody-project/Frontend pull request #159
Opened 2023-12-01 10:28 UTC by sikkzz

# 설명

- [https://github.com/Selody-project/Frontend/issues/138](https://github.com/Selody-project/Frontend/issues/138)
- Group Page 전반적인 사항 구현
- 미구현 기능들
  - 피드 업로드
  - 댓글 기능
- 추후 수정 예정 기능들
  - 백엔드 ISSUE 달려있는 기능들
  - setting 페이지랑 겹치는 기능들
  - 테스트코드 관련
 
세부 기능들중 미구현이거나 아직 문제가 있는 기능들이 있을 수 있습니다. 간단한건 해당 브랜치에서 수정 예정이고 수정할 부분이 많으면 ISSUE 새로 올려서 작업하겠습니다.

코드양이 많아서 천천히 확인해보면서 리뷰 부탁드리고 이후 작업부터는 좀 세부적으로 쪼개서 작업하도록 하겠습니다.. 제가봐도 양이 끔찍하네요

2023-12-08 08:22 UTC, kimyoungyin requested changes

2023-12-08 08:22 UTC, kimyoungyin commented on __test__/pagesTest/CommunityPage.test.jsx
이 테스트 파일을 삭제하신 이유가 있을까요?

2023-12-08 08:22 UTC, kimyoungyin commented on src/components/Group/MyGroup/MyGroup.jsx
> +							</a>
태그: a -> Link
attr: href -> to

2023-12-08 08:22 UTC, kimyoungyin commented on src/features/post/post-slice.js
> +			})
`payload.feed`가 빈 배열일 경우를 고려해야 할 것 같습니다.

계속 에러가 발생하네요

ex) postId

2023-12-08 08:22 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +		</ContainerMain>
둘 중 하나에 margin-bottom을 적당히 주어야 할 것 같습니다

2023-12-08 08:22 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +				<ProfileLeftDiv>
헤더에 메뉴들이 나왔을 때 겹치지 않도록 마진이나 display를 수정해야 할 것 같습니다

2023-12-08 08:22 UTC, kimyoungyin commented on src/hooks/useObserver.jsx
다시 보니 다른 hooks도 마찬가지인데, `.jsx` 처리하신 이유가 있을까요?

jsx element를 다루는 컴포넌트도 아니라 `.js`로 하는 게 맞는 것 같아서요

2023-12-08 08:22 UTC, kimyoungyin commented on src/hooks/useObserver.jsx
> +
이건 선택사항인데, 이렇게 복잡한 param을 받는 경우나 타입을 명시하고 싶은 경우, 타입스크립트에 준하는 기능을 다음과 같이 주석을 달아보는 건 어떤가요?(jsDoc) 

다른 곳에서 이 hook을 사용할 때 편리할 것 같습니다.

제가 임의로 만들어봤어요
```js
/**
 * @param {React.MutableRefObject} ref useRef로 생성
 * @param {IntersectionObserverInit} options 옵저버 옵션
 * @returns
 */
```

2023-12-08 08:22 UTC, kimyoungyin commented on src/components/Group/MyGroup/MyGroup.jsx
> +					</RightButtonDiv>
Button을 div 말고 `button` 태그로 하는 게 낫지 않을까요?

`LeftButtonDiv`도 마찬가지입니다!

2023-12-08 08:22 UTC, kimyoungyin commented on src/components/Group/MyGroup/MyGroup.jsx
> +										<img src={info.image} alt="groupImg" />
의미상 `li` 태그당 하나의 그룹이 있어야 될 것 같은데 하나에 모여있네요?

`li` 태그도 map안에 포함시켜야 할 것 같네요

2023-12-08 08:22 UTC, kimyoungyin commented on src/pages/CommunityPage/CommunityPage.jsx
> +							onKeyPress={handleSearchKeyPress}
`onKeyPress`는 사용되지 않는 prop이라고 하네요

수정 부탁드립니다!

2023-12-08 08:22 UTC, kimyoungyin commented on src/components/Group/GroupSearch/GroupSearch.jsx
> +	const [group, setGroup] = useState([]);
배열이면 복수형으로 명명 부탁드립니다!

2023-12-08 08:22 UTC, kimyoungyin commented on src/components/Group/GroupSearch/GroupSearch.jsx
> +	return <GroupInfo groupInfo={group} target={target} />;
여기도 Prop 명을 복수형으로 부탁드립니다

2023-12-08 08:22 UTC, kimyoungyin commented on src/components/Base/BaseCard/BaseCard.styles.js
> +	border: 1px solid #6c55fe;
primary 색이네요!

2023-12-08 08:22 UTC, kimyoungyin commented on src/components/Common/ToggleButton/ToggleButton.styles.js
> +export const OuterDiv = styled.div`
cursor에 pointer를 주는 건 어떤가요?

2023-12-08 08:22 UTC, kimyoungyin commented on src/features/group/group-slice.js
> +	groupMemberList: null,
`groupInviteLink`를 제외하고 나머지는 굳이 따로 빼서 관리할 이유가 있을까요?
`groupInfo` state도 있는데, 이 안에 객체 프로퍼티로 정리하면 될 것 같은데요?

2023-12-08 08:22 UTC, kimyoungyin commented on src/features/group/group-slice.js
> +	isEnd: false,
isEnd는 굳이 여러 곳에서 공유하지 않고 검색하는 곳에서만 독립적으로 쓰일 것 같은데 전역으로 하지 않는 게 어떠세요? 전역으로 안하면 아래와 같은 번거로움도 없습니다.

(전역으로 하겠다는 가정하에)
일단 현재 코드에서는 안 보이는데, isEnd가 true로 되고 나서, 해당 컴포넌트가 unmount될 때 isEnd를 false로 만들어주는 초기화 작업이 이루어지지 않고 있는 것 같아요

2023-12-08 08:22 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
> +	const { user } = useSelector((state) => state.auth);
구조분해할당으로 줄일 수 있을 것 같아요
(group state에 경우 slice에서 합치는 거에 대해서 먼저 고려해보는 게 좋을 것 같아요)

2023-12-08 08:22 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
> +	});
deps를 없앤 이유가 있을까요?

2023-12-08 08:22 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
>  	const userGroup = useSelector((state) => state.user.userGroupList);
복수형으로 변경 가능할까요?

2023-12-08 08:22 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
>  			if (info.groupId === Number(param.id)) {
리더임을 검증하는 `useEffect` 코드와 합쳐서 진행하는 게 좋을 것  같습니다
- 리더이면 이미 멤버니 forEach문을 실행할 필요 없이 바로 setIsGroupMember(true)
- 리더가 아니면 forEach문으로 탐색

2023-12-08 08:22 UTC, kimyoungyin commented on src/components/Tab/Tab.jsx
> +}) => {
- 아예 tab을 배열로 받는 게 이해하기 쉬울 것 같아요: defaultTitle, tabTitle -> tabTitles or titles
- ~option 명명을 `isDisabled`로 변경 후 tab 배열 각각 인덱스에 isDisabled로 넣기(option의 용도가 뭘까요?)
- `tabs.map()`로 렌더링 

등등 리팩토링할 게 많아보여요

질문은
- Tab 관련 컴포넌트가 되게 모호한 이름이라 명명을 확실하게 차이를 두는 게 좋아보입니다. 다른 컴포넌트명 없을까요?
- option들은 어떻게 활용되는지 정확히 모르겠어서 설명 한 번만 부탁드려도 될까요?

2023-12-08 08:22 UTC, kimyoungyin commented on src/constants/accessConstants.jsx
> +		text2: "본인이 작성한 글에 한해 수정 및 삭제",
이렇게 말고 그냥 개행문자 "\n"로 하나의 text로 처리하면 좋을 것 같아요

2023-12-08 08:22 UTC, kimyoungyin commented on src/features/group/group-service.js
> +	"group/changeGroupPublic",
이름만 봐서는 public으로만 변경하는 것으로 오해할 수 있으니
명명을 변경하는 게 좋을 것 같아요(`changeGroupPublicOption` 또는 다른 좋은 이름으로!)

key도 같이 변경 부탁드려요

2023-12-08 08:22 UTC, kimyoungyin commented on src/features/group/group-service.js
> +	async ({ groupId, status }, thunkAPI) => {
`status`보단 `isPublic`으로 하는게 boolean 값으로는 더 낫지 않을까요?

2023-12-08 08:22 UTC, kimyoungyin commented on src/features/group/group-service.js
> +);
명세서에 보니까 초대 코드 조회하는 엔드포인트가 있던데,
먼저 get 요청으로 이를 확인해보고, exp가 지났다면 생성하는 게 어떨까요?
(이 부분은 백엔드에서 하나로 통합해서 처리해주는 게 나을 것 같아요)

2023-12-08 08:59 UTC, kimyoungyin requested changes

2023-12-08 08:59 UTC, kimyoungyin commented on src/features/group/group-slice.js
> +				state.isEnd = payload.isEnd;
이를 전역으로 쓰지 말고 내부 컴포넌트에서 관리하는 건 어떠세요?
해당 thunk의 경우 그 컴포넌트에서 Unwrap 처리해서 setState 시키는게 나아보여요

2023-12-08 08:59 UTC, kimyoungyin commented on src/features/group/group-slice.js
> +				state.isEnd = payload.isEnd;
여기도요!

2023-12-08 08:59 UTC, kimyoungyin commented on src/features/post/post-slice.js
> +	isLoading: false,
true가 initial Value여야 할 것 같아요

2023-12-08 08:59 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	const recordId = useSelector((state) => state.post.lastRecordId);
구조 분해 할당하면 좋겠네요

2023-12-08 08:59 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	const handleLikeClick = (isLike, postGroupId, postId) => {
isLike -> isLiked

2023-12-08 08:59 UTC, kimyoungyin commented on src/pages/CommunityPage/CommunityPage.jsx
> +	const [tabIndex, setTabIndex] = useState(0);
이를 전역 state로 변경하는 건 어떠세요? 사용자 경험 측면에서 느낀 걸 말씀드리면

'그룹 검색'에서 그룹을 클릭해서 그룹 route로 갔다가 뒤로 가기를 눌렀을 때 인덱스가 초기화되면서 이전에 보던 화면을 보지 못하는 불편함이 있었습니다.

2023-12-08 08:59 UTC, kimyoungyin commented on src/pages/CommunityPage/CommunityPage.jsx
> +					<SearchDiv>
검색 input도 Index가 1일 때(그룹 탐색)만 보여줘야 하지 않을까요?

2023-12-08 08:59 UTC, kimyoungyin commented on src/pages/CommunityPage/CommunityPage.jsx
> +						setTabIndex={setTabIndex}
다른 컴포넌트도 확인해봐야할 것 같은데 setState를 직접 Prop으로 넘겨주면 안됩니다. state를 변경하는 함수를 넘겨주어야 합니다

2023-12-08 08:59 UTC, kimyoungyin commented on src/pages/CommunityPage/CommunityPage.styles.js
> +	}
이 id는 안 쓰이는 것 같은데요? 만약 나중에 필요하다면 className으로 부탁드립니다

2023-12-08 08:59 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	};
여기서 걸러주는 게 아니라 내 글이 아닌 경우 '삭제' 버튼이 아예 숨겨야 할 것 같습니다

그러면 param으로 isMine도 필요 없을 거에요

2023-12-08 08:59 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +									</li>
`isMine === false`라면 렌더링하지 않아아 합니다!

2023-12-08 08:59 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +						<img src={post.authorImage} alt="postImg" />
alt text를 명시하면 좋을 것 같아요. "~님의 프로필 이미지"와 같이요

2023-12-09 10:13 UTC, sikkzz commented on __test__/pagesTest/CommunityPage.test.jsx
아마 과거 117번이랑 겹쳐서 작업할 때 오류때문에 지웠을꺼에요 추후 테스트 코드 작성할때 다시 생성할게요

2023-12-09 16:40 UTC, sikkzz commented on src/pages/MyPage/MyPage.jsx
> +		</ContainerMain>
관련해서 전에 말씀드리려다 까먹었는데 footer 하나 요청드려서 제작하는게 좋을 거 같다는 생각이 들었어요.
아래 영역이 허전하기도 하고 공간 여백 기준이 없는 부분도 있고 해서요 어떻게 생각하시나요?

2023-12-09 16:42 UTC, sikkzz commented on src/pages/MyPage/MyPage.jsx
> +				<ProfileLeftDiv>
안겹치지 않나요? 현재 여백이 존재합니다

2023-12-09 16:42 UTC, sikkzz commented on src/hooks/useObserver.jsx
맞네요 변경하겠습니다.

2023-12-09 16:45 UTC, sikkzz commented on src/hooks/useObserver.jsx
변경하는김에 다른 hook도 변경했습니다

2023-12-09 18:13 UTC, sikkzz commented on src/pages/GroupPage/GroupPage.jsx
> +	});
추가했습니다.

2023-12-09 18:20 UTC, sikkzz commented on src/components/Tab/Tab.jsx
> +}) => {
회의때 말씀드렸듯 리팩토링 진행 예정입니다.

2023-12-09 18:32 UTC, sikkzz commented on src/pages/CommunityPage/CommunityPage.jsx
> +						setTabIndex={setTabIndex}
동일하게 이후 리팩토링 예정입니다.

2023-12-09 18:36 UTC, sikkzz commented on src/pages/CommunityPage/CommunityPage.jsx
> +	const [tabIndex, setTabIndex] = useState(0);
리팩토링 이후 확인하고 적용시켜볼게요

2023-12-09 18:38 UTC, sikkzz commented on src/pages/CommunityPage/CommunityPage.jsx
> +					<SearchDiv>
리팩토링 후 수정

2023-12-09 18:39 UTC, kimyoungyin requested changes
일단 확인 안되는 것 빼고 대략 봤습니다 후..

2023-12-09 18:39 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +	const [group, setGroup] = useState([]);
groups로 변경하는 게 나아보여요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupInfo/GroupInfo.jsx
> +const GroupInfo = ({ groupInfo, target, menu }) => {
컴포넌트명이나 prop명이 바로 이해하기 어려운 것 같아요
- 컴포넌트명은 그냥 보기에 그룹 정보를 보여주는 '단일 박스'로 이해되는 것 같아요. 뭔가 배열 요소를 담고 있는 컴포넌트명으로 변경했으면 좋겠어요(~List, ~s)
- groupInfo -> groups
- target -> ~ref
- menu -> index

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupInfo/GroupInfo.jsx
> +			{groupInfo?.map((info) => (
optional(?)을 준 이유가 있을까요?

빈 배열이면 알아서 렌더링되지 않을 것 같아요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/CreateGroupLink/CreateGroupLink.jsx
컴포넌트명이 동사형인 게 어색한 것 같아요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfile.jsx
> +								setIsCreateLinkClick={setIsCreateLinkClick}
setState함수를 그대로 자식에게 넘겨주면 안됩니다!

그리고 이 prop의 용도는 링크 페이지를 닫기 위함이니까
`onClose={( ) => setIsCreateLinkClick(false)}`
이렇게 넘겨주면 좋겠네요.
보통 자식에서 이벤트가 발생할 때 대응되는 prop 명은 `on이벤트이름`으로 하는 경우가 많습니다. onChange, onSubmit 처럼요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfile.jsx
> +	const [isCreateLinkClick, setIsCreateLinkClick] = useState(false);
블리언 타입이면서 모달을 띄우는지 여부를 말해주는 state이니 isLinkCreatorOpen과 같이 변경하는 게 좋겠네요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/CreateGroupLink/CreateGroupLink.jsx
> +				</button>
버튼의 용도가 반대인 것 같은데 어떻게 생각하세요?
위에 작은 텍스트는 '닫기' 버튼으로, 링크 오른쪽 잘 보이는 검은색 버튼은 '생성'과 같이 해야 할 것 같아요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/CreateGroupLink/CreateGroupLink.styles.js
> +	left: 50px;
살짝 포지션이 틀어진 부분이 있는 것 같은데
이렇게 애매한 값으로 하지 말고,
같은 레벨에 '링크 생성하기' 버튼의 자식으로 포함시켜서
```css
top: 100%;
left: 0;
```
이렇게 주는 게 더 좋아보여요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeader.jsx
컴포넌트명이 GroupLeader면 바 이해하기 힘든 것 같아요
그룹 관리하는 창이니 `GroupManagement`와 같이 변경하는 게 좋아보여요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeader.jsx
> +	const [menu, setMenu] = useState("그룹 프로필");
여기서만 쓰는 상수니까 컴포넌트 밖 위쪽에 상수로 선언하고 쓰는 게 좋을 것 같아요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeader.jsx
> +							disabled={menu === "그룹원 관리"}
`disabled`를 기능적으로 사용하는 게 아니라 스타일 용도로 쓰고 있네요?

이럴 경우 굳이 필요 없이 className으로 구분하는게 나아보이는데 어떠세요?

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderManagement/AccessInfo.jsx
`AccessLevelInfo`가 낫지 않을까요?

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderManagement/AccessInfo.jsx
> +							<h4>{data.text2}</h4>
이미 리뷰 남긴 것 같긴 한데 애초에 text에 개행문자 넣어서 하나의 text로 하는 게 좋을 것 같아요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderManagement/GroupLeaderManagement.jsx
그룹 리더를 관리하는 게 아니라 그룹 멤버들을 관리하는 거니,
`GroupMemberManagement`가 나아보여요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderManagement/GroupLeaderManagement.jsx
> +				<TitleLi red>내보내기</TitleLi>
대부분 상수이니 컴포넌트 밖으로 뺴서 map 처리하는 게 좋아보여요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderManagement/GroupLeaderManagement.jsx
> +	}, []);
useOutSideClick을 써보는 게 어떨까요? 생각해보니 제가 만들어둔게 작업 브랜치에 있습니다
```js
import { useEffect } from "react";

const useOutsideClick = (ref, trigger) => {
	useEffect(() => {
		const handleClick = (event) => {
			if (!ref.current || ref.current.contains(event.target)) {
				return;
			}
			trigger();
		};
		document.addEventListener("click", handleClick);
		return () => {
			document.removeEventListener("click", handleClick);
		};
	}, [ref, trigger]);
};

export default useOutsideClick;
```
[링크](https://github.com/Selody-project/Frontend/blob/129-front-task-%EA%B0%9C%EC%9D%B8-%EC%9D%BC%EC%A0%95-%ED%8E%98%EC%9D%B4%EC%A7%80-%EB%8B%AC%EB%A0%A5-%EB%94%94%EC%9E%90%EC%9D%B8/src/hooks/useOutsideClick.js)

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderManagement/GroupLeaderManagement.jsx
> +	const [isInnerDropdownOpen, setIsInnerDropdownOpen] = useState(false);
innerDropdown이 어떤 걸 의미하는지 바로 이해하기 힘든 것 같습니다. 컴포넌트명을 그대로 따라간 것 같은데 컴포넌트명을 바로 이해할 수 있도록 변경해주시면 좋을 것 같고(`AccessLevelOptions`과 같이요)
 
`isAccessLevelOptionsOpen`과 같이 정확히 명시하는 게 어떨까요?

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderManagement/GroupLeaderManagement.jsx
> +						<img src={memberInfo.member.image} alt="profileImg" />
altimg를 의미 있게 작성해주실래요?

2023-12-09 18:39 UTC, kimyoungyin commented on src/constants/accessConstants.jsx
.js로 해야할 것 같습니다

2023-12-09 18:39 UTC, kimyoungyin commented on src/constants/accessConstants.jsx
> +		id: "viewer",
key를 id가 아니라 accessLevel로 하는 게 낫지 않을까요? 
해당 상수를 이용하는 곳에서 바로 이해하기 힘들었습니다

2023-12-09 18:39 UTC, kimyoungyin commented on src/constants/accessConstants.jsx
> +export const accessData = [
accessLevelData가 낫지 않을까요? 
그리고 대문자 처리하는 게 좋아보입니다(ACCESS_LEVEL_DATA). icon을 제외하고(컴포넌트로 쓰이니까) 다 대문자 처리하고 있어요!

2023-12-09 18:39 UTC, kimyoungyin commented on src/features/post/post-service.js
> +	"post/getGroupAllPost",
`getAllGroupPosts`가 맞는 것 같습니다(key도 post/getAllGroupPosts)

(복수형으로)

2023-12-09 18:39 UTC, kimyoungyin commented on src/features/post/post-service.js
> +	"post/getGroupPost",
getGroupPosts

2023-12-09 18:39 UTC, kimyoungyin commented on src/features/post/post-service.js
> +	"post/getUserGroupPost",
getUesrGroupPosts

2023-12-09 18:39 UTC, kimyoungyin commented on src/features/post/post-service.js
> +	"post/dislikeGroupPost",
cancelGroupPostLike or cancelLikeGroupPost

2023-12-09 18:39 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +	const [group, setGroup] = useState([]);
유저가 속한/가입 요청한 그룹들은 위에서 가져오셨다시피, 
user-slice에 userGroupList, userRequestGroupList를 사용하면 되지 않나요? 따로 다시 할당하는 이유가 있을까요?

GroupInfo에 전달할 prop 때문이라면, 예를 들 다음과 같이 하면 되지 않을까요?
```js
groupInfo={ tabIndex ? userRequestGroupList : userGroupList}
```

2023-12-09 18:39 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +	const isEnd = useSelector((state) => state.group.isEnd);
구조분해할당해야 할 것 같아요. slice별로 하면 가독성이 좋을 것 같아요

2023-12-09 18:39 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +	const isEnd = useSelector((state) => state.group.isEnd);
복수형으로 처리할 부분은 처리해주시고요!
그리고 groupList는 어디 쓰이는 건가요? 여기서는 유저 관련 그룹들만 보여주면 되지 않나요?

2023-12-09 18:39 UTC, kimyoungyin commented on src/features/user/user-service.js
>  );
inquery보단 그냥 get~이 낫지 않을까요?
그리고 복수형 처리도 해주고요!

2023-12-09 18:39 UTC, kimyoungyin commented on src/features/user/user-slice.js
>  	isUserGroupFetching: false,
isUserGroupFetching도 기본값 true로 해주세요!

2023-12-09 18:39 UTC, kimyoungyin commented on src/features/post/post-slice.js
> +	userGroupPost: [],
유저 관련 state는 user-slice로 가는 게 좋지 않을까요?

2023-12-09 18:39 UTC, kimyoungyin commented on src/features/post/post-slice.js
> +	isLoading: false,
- groupPost -> currentGroupPost(현재 보고 있는 post)
- allGroupPost -> allGroupPosts
- userGroupPost -> userGroupPosts(user로 옮겨야 하지 않을까..)
- isLoading의 기본값 true

2023-12-09 18:39 UTC, kimyoungyin commented on src/features/post/post-slice.js
> +			})
getGroupAllPost(s).rejected 일 때 isEnd라던가, lastRecordId를 조정해줘야 하지 않을까요? 초기화한다던지 하는 조치가 필요할 것 같은데 어떠세요?

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Setting/SharedSettings.jsx
이건 아직이라 스킵할게요!

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Header/GroupCreateModal/GroupCreateModal.jsx
>  		<BaseModal title="그룹 만들기" bg="#fff">
배경색이 안 보입니다! 아마 모달 리팩토링하면서 수정된 것 같기도 하네요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Header/GroupCreateModal/GroupCreateModal.jsx
> +	const isButtonActive = () => groupName.trim() && groupDescription.trim();
active보다는 able/disable로 표현해주는게 좋을 것 같아요
active는 클릭한 상황을 보통 의미하더라구요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/MyGroup/MyGroup.jsx
> +	const [disableNextButton, setDisableNextButton] = useState(false);
동사형이라 함수처럼 느껴지고, disabled라기보단 display 여부라
is~DisPlayed와 같이 수정해야 할 것 같아요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/MyGroup/MyGroup.jsx
> +						disabled={disableNextButton}
양쪽 버튼 모두 어차피 document안에 없으면 클릭할 수 없으니 필요 없는 속성 같아요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/MyGroup/MyGroup.jsx
> +	const userGroup = useSelector((state) => state.user.userGroupList);
굳이 단수형으로 바꿔 할당하면 더 혼동되는 것 같아요. 동일한 이름으로 사용하는 게 낫지 않을까요?

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/MyGroupFeed/MyGroupFeed.jsx
이건 제가 지금 게시물을 업로드 할 방법을 못 찾겠어서 놔둘게요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupRequestCancelModal/GroupRequestCancelModal.styles.js
이것도 현재 그룹 참여 요청 기능이 연결이 안돼있어서 확인을 못해서 놔둘게요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupRequestCancelModal/GroupRequestCancelModal.jsx
여기도 기능 구현되면요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfile.jsx
> +	const locate = useLocation();
이 훅들은 순서가 위쪽으로 가야 하지 않을까요?

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfile.jsx
> +
불리언값이니 IsManageMode or isManaging과 같이 해주시면 좋을 것 같아요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfile.jsx
중첩된 삼향연산자로 이루어진 렌더링의 가독성을 더 좋게 하기 위해 좀 분리하는 게 좋아보여요. eslint 비활성화할 필요 없이요!

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeader.jsx
> +				)}
groupDetailInfo가 확실히 있을 때만 이들을 렌더링해야 하는데, 그게 아닌 경우도 발생할 수 있기에 자식 컴포넌트 `GroupLeaderProfile` 내부에서 `groupDetailInfo`를 사용할 때 ? 연산자 사용/ 제약이 발생하는 것 같습니다. 

아예 부모 컴포넌트인 `GroupLeader`컴포넌트에서 `getGroupInfo` thunk를 호출하고, 여기서 groupInfo가 존재할 때만 렌더링을 허용하도록 하며, GroupLeaderProfile에서 useEffect code를 제거하는  낫지 않을까요?

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeader.jsx
> +				)}
groupInfo가 있는게 확실하니 아예 prop으로 groupInfo를 주는 것도 좋아보입니다

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderManagement/GroupLeaderManagement.jsx
> +				<MemberUl key={memberInfo.member.userId}>
- group.isLoading이 true일 때 로딩 중이라는 문구가 필요하지 않을까요?
- ?은 필요 없을 것 같아요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderManagement/InnerDropdown.jsx
이 컴포넌트명을 좀 더 구체적으로 작성해야 할 것 같아요!
`userCommentList`와 같이요!

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderManagement/InnerDropdown.jsx
> +					<TitleDiv>
더미이긴 하지만 따로 데이터를 배열로 빼서 map 처리하는 게 좋지 않을까 싶네요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderManagement/InnerDropdown.jsx
> +	return (
여기도 useOutsideClick 쓰는 게 좋아보이네요!

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderManagement/GroupLeaderManagement.jsx
> +				<TitleLi red>내보내기</TitleLi>
이건 리더 본인의 경우는 안 보여줘야 될 것 같네요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderProfile/GroupExitModal.jsx
그룹 멤버가 그룹장 하나인 경우 위임 관련 정보를 렌더링하지 않고 삭제하기가 허용되게 해야겠네요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderProfile/GroupLeaderProfile.jsx
> +	const [isPublicClick, setIsPublicClick] = useState(isPublicGroup);
IsPublic이 맞는 것 같아요. 클릭인지를 판단하는 state는 아니니까요!

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderProfile/GroupLeaderProfile.jsx
> +	const [profileObj, setProfileObj] = useState();
initial value가 필요하지 않을까요?

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderProfile/GroupLeaderProfile.jsx
> +	);
new를 굳이 붙일 필요가 없을 것 같고, input value니 ~value라 표현하는 게 가독성이 좋을 것 같아요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderProfile/GroupLeaderProfile.jsx
> +	};
딜레이가 생기지 않도록 퍼블릭 여부를 먼저 변경한 뒤 dispatch하는 게 좋아보이고,

에러 발생 시 퍼블릭 여부를 원상복구하는 코드가 추가되어야 할 것 같아요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderProfile/GroupLeaderProfile.jsx
> +	}, []);
이거를 부모로 빼고 groupDetailInfo가 확실히 있다는 코드 상 확인 거치고 이 컴포넌트를 렌더링하면 좋을 것 같아요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderProfile/GroupExitModal.jsx
그리고 애초에 위임해야지만 삭제할 수 있지 않나요...?

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderProfile/GroupDeleteModal.jsx
이건 제가 초대된/초대한 유저가 없어서 다음에 같이 확인해볼게요

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderProfile/GroupDelegateModal.jsx
> +								onClick={() => setSelectedMemberId(info.userId)}
토글이 가능해야 할 것 같아요. 위임할 대상을 취소할 수 있도록이요!

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/GroupLeader/GroupLeaderProfile/GroupDeleteModal.styls.js
여기도요!

2023-12-09 18:39 UTC, kimyoungyin commented on src/components/Group/MyGroupFeed/MyGroupFeed.styles.js
여기도요

2023-12-09 19:39 UTC, sikkzz commented on src/components/Group/GroupLeader/GroupLeader.jsx
> +							disabled={menu === "그룹원 관리"}
동일하게 탭이라 리팩토링때 고려할게요

2023-12-09 19:47 UTC, sikkzz commented on src/constants/accessConstants.jsx
이 파일은 icon 때문에 jsx파일로 작성했습니다

2023-12-09 19:50 UTC, sikkzz commented on src/components/Header/GroupCreateModal/GroupCreateModal.jsx
>  		<BaseModal title="그룹 만들기" bg="#fff">
Base modal 리팩토링 이후에 수정할 예정입니다

2023-12-10 08:52 UTC, sikkzz commented on src/features/post/post-slice.js
> +	userGroupPost: [],
네이밍을 이상하게 해서 그렇게 느끼시는거 같아요. 내가 가입된 그룹 포스트들을 담아줄 state인데 myGroupPosts로 변경했어요

2023-12-10 09:12 UTC, sikkzz commented on src/components/Group/GroupLeader/CreateGroupLink/CreateGroupLink.jsx
> +				</button>
회의때 한번 말씀드릴게요

2023-12-10 14:56 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +		</ContainerMain>
전 굳이 급한 건 아니라 생각하긴 한데, 프론트 측면에서는 그냥 footer를 임시로 만들어두고 마진만 주는 역할로 두는 건 괜찮지 않을까 싶네요!

2023-12-17 10:35 UTC, sikkzz commented on src/components/Group/GroupProfile/GroupProfile.jsx
리팩토링 진행해봤습니다. 더 최적화된 방법이 생각이 안나서 좋은 방법 있으면 말씀해주세요

[커밋 링크](https://github.com/Selody-project/Frontend/pull/159/commits/a3bb265ea5a7752d2a3cd88afe9ec5cad00afeda)

2023-12-17 10:53 UTC, sikkzz commented on src/features/group/group-slice.js
> +	isEnd: false,
getGroupList fulfilled쪽 코드에서 payload에 isEnd와 groups 배열이 넘어오는데 옵저빙을위해서 여기서 groups 배열만 api가 호출될때마다 계속 push해주고 isEnd값이 true이면 observing이 멈추는 방식입니다. 전역에서 관리를 안한다면 그때그때 받아오기 위해서 payload를 받아오고 isEnd값을 확인해야하고 payload에서 groups 배열만 따로 또 할당해줘야하는 코드가 추가되어야 하지 않나요?

2023-12-17 11:58 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfile.jsx
`GroupProfileButton`을 확인해보시면

return문을 사용해서 중복되는 조건 확인을 줄일 수 있을 것 같아요!
그럴 경우 `IsManaging`이 true일 때 버튼 밑에 버튼들은 `isManaging`이 false임이 당연하니까 논리 연산자 `&&`을 생략할 수 있을 것 같아요

```js
if (isManaging) {
  return <ProfileButtonDiv>
                 <ProfileButton onClick={() => setIsGroupInviteLinkOpen(true)}>
	             링크 생성하기
		 </ProfileButton>
		 <ProfileWhiteButton
		    onClick={() => dispatch(openModal({ type: "DELEGATE_GROUP" }))}
		 >
	             그룹장 위임
		 </ProfileWhiteButton>
          </ProfileButtonDiv>
// ...
```
대략 이런 느낌으로요!
두 개의 버튼이 나와야 하는 조건이니 위와 동일하지는 않지만, 조금 나눠서 return문을 통해 보여줄 컴포넌트들을 분리한다고 보면 됩니다.

2023-12-27 08:39 UTC, kimyoungyin requested changes
천천히 리뷰할게요.. 많이 바뀌었네요 ㅠ

2023-12-27 08:39 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
>  	const userGroup = useSelector((state) => state.user.userGroupList);
이거 해결이 안돼있는데 resolve되어 있네요. userGroup

2023-12-27 08:39 UTC, kimyoungyin commented on src/features/group/group-slice.js
>  				state.isLoading = false;
createGroup이 성공한 경우에는 groupList에 push해줘야 할 것 같은데 업데이트 로직이 없네요

2023-12-27 08:39 UTC, kimyoungyin commented on jest.setup.js
> +
모킹을 전역으로 해준 이유가 있을까요?
필요한 곳에서만 `beforeAll`이나, `beforeEach`로 처리해주면 될 것 같은데 어떠세요?

2023-12-27 08:39 UTC, kimyoungyin commented on __test__/__mocks__/mockIntersectionObserver.js
이렇게 작성한 이유가 있을까요? 검색해보니 간략하게 다음과 같이 모킹하던데

세부 로직 때문에 그럴까요?

2023-12-27 08:39 UTC, kimyoungyin commented on src/components/Group/GroupSearch/GroupSearch.jsx
> +	const isEnd = useSelector((state) => state.group.isEnd);
구조 분해 할당 하는 게 어떠세요?

2023-12-27 08:39 UTC, kimyoungyin commented on src/components/Group/GroupSearch/GroupSearch.jsx
> +	const [groups, setGroups] = useState([]);
여기서 전역 state가 있음에도 불구하고 다시 담는 이유가 있을까요? 전역 state를 그대로 getGroupList.fulfilled되었을 때 업데이트하면 될 것 같은데요?

2023-12-27 08:39 UTC, kimyoungyin commented on src/components/Group/GroupSearch/GroupSearch.jsx
> +	});
전역으로 그룹 리스트를 사용한다면 이것도 필요없을 것 같구요

2023-12-27 08:39 UTC, kimyoungyin commented on src/features/group/group-slice.js
> +	isEnd: false,
isEnd가 한 페이지 당 한 번만 쓰이면 상관은 없습니다. 대신 초기화시켜주는 코드만 추가 부탁드려요!

2023-12-27 08:39 UTC, kimyoungyin commented on src/features/group/group-slice.js
>  			.addMatcher(isAllOf(searchGroup.fulfilled), (state, { payload }) => {
여기 굉장히 비효율적으로 작성되어 있네요. 처리해주셔야 할 부분은

- 그룹 검색이 fulfilled되어도 빈 배열일 수 있다는 점. 예를 들어 lastRecordId를 얻기 위한 groupId 조회 시에도 에러가 나네요
- 다른 키워드로 변경 후 searchGroupList 검색을 할 때마다 전체 다 바꿔치기해야 함(기존 배열에 추가하는게 아닙니다)
- 같은 키워드로 lastRecordId가 변경된 검색의 경우만 기존 배열에 추가해야 합니다. 이것도 push로 추가하는 게 아니라, `[...prev, ...new]` 이렇게 하면 됩니다.

2023-12-27 08:41 UTC, kimyoungyin commented on src/features/group/group-service.js
`searchGroup`은 2글자 이상인 경우만 가능하던데 해당 부분을 예외 처리 부탁드립니다

2023-12-27 08:43 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	}, [isObserving, dispatch]);
의미없는 unwrap 처리네요. 제거 부탁드립니다!

2023-12-27 08:44 UTC, kimyoungyin commented on src/components/Group/MyGroupFeed/MyGroupFeed.jsx
> +	}, [isObserving, dispatch]);
여기도 의미없는 unwrap 처리인 것 같습니다.

2023-12-27 09:44 UTC, sikkzz commented on src/pages/GroupPage/GroupPage.jsx
>  	const userGroup = useSelector((state) => state.user.userGroupList);
수정했습니다

2023-12-27 09:51 UTC, sikkzz commented on src/features/group/group-slice.js
>  				state.isLoading = false;
그룹 리스트 조회할때 추가된 그룹들이 다 조회가 되기 때문에 상관 없지 않나요?

2023-12-28 00:08 UTC, kimyoungyin commented on src/features/group/group-slice.js
>  				state.isLoading = false;
그룹리스트를 보는 커뮤니티 홈 페이지에서, 헤더에 있는 그룹 만들기를 클릭했을 때를 생각해보시면 좋을 것 같아요

2023-12-28 06:26 UTC, kimyoungyin requested changes
일단 리뷰는 대략 마쳤습니다... 
다만, 조금 구현 시에 기존에 리뷰했던 것들, 코드에 대한 고민을 좀만 더 해주셨으면 합니다

코드 양이 많아 리뷰할 게 많다고 보기에는 너무 자잘한 요소들이 많습니다.
(_차라리 오타는 아무런 상관이 없습니다._)
리뷰를 한 적있는 요소라던지, React의 기본이라던지, 구현과 함께 이와 관련된 여러 실제 테스트를 해보며 발생할 수 있는 에러를 확인하지 않는 것 등등.. 번거로운 것들이 많은 것 같습니다.

다음 커밋부터는 조금 더 신경 써서 작업 부탁드릴게요. ㅠㅠ

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +			{allGroupPosts?.map((post) => (
빈 배열의 경우 어차피 map 메서드를 생략시켜주니, ?는 필요 없을 것 같아요

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +				>
시멘틱 태그 측면에서 Link나 button으로 변경하는 건 어떠세요?

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +const GroupInfoList = ({ groups, scrollRef, index }) => {
index같은 추상적인 표현보다 is~로 확실한 불리언 타입으로 정하는 게 좋을 것 같아요.
이 인덱스가 뭘 의미하는지는 상위 컴포넌트까지 찾아들어가서야 이해할 수 있는 형태인 것 같아요.

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupInviteLink/GroupInviteLink.jsx
> +				</button>
링크 생성을 기다리는 동안(`isLoading`이 true인 경우) disabled 처리해야 합니다

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupInviteLink/GroupInviteLink.jsx
> +	const [inviteLink, setInviteLink] = useState(false);
이건 필요 없고 group-slice의 isLoading을 쓰면 될 것 같네요

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupInviteLink/GroupInviteLink.styles.js
> +	}
disabled 처리 되어있을 때(로딩) 보여줄 디자인도 추가하면 좋을 것 같아요

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupInviteLink/GroupInviteLink.jsx
이 컴포넌트는 바깥 클릭 시 꺼지는 기능은 필요 없을까요?

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagement.jsx
> +			<InnerDiv>
두 개의 styled.div로 감싼 이유가 있을까요? 그냥 합쳐서 하나의 태그로 처리해도 구현 가능할 것 같은데 어떠세요?

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfileButton.jsx
> +	const profileButtonRender = [];
각 요소가 push될 때 key가 있어야 합니다. 관련 에러가 console에 계속 뜨니 확인 후 반영해주세요

변수명을 수정해주세요. 예시는 다음과 같습니다
- profileButtonsToRender
- profileButtons

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfileButton.jsx
> +	}
- 배열의 일관성을 위해 fragment보단, 컴포넌트 하나씩 push해주세요
- 그룹 멤버가 하나(그룹장)밖에 없는 경우는 '그룹장 위임'을 보여주지 않아야 합니다.

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfileButton.jsx
> +	const profileButtonRender = [];
(추가) 해당 방식으로 렌더링할 컴포넌트를 모으는 게 좋은 방식인지 모르겠습니다. state로 배열을 처리하거나 각각 불리언 값으로 각각 처리하는 게 좋아보입니다.

그 이유는 현재 치명적인 에러가 있기 때문입니다...
- 내가 만든 그룹(관리자)에 들어갔다가 나간 후 다른 그룹에 들어갔을 때 렌더링할 버튼이 초기화가 안됩니다. 즉 내가 만든 그룹이 아닌데 그룹 관리 경로에 접근할 수 있습니다.

이건 state로 관리할 경우 컴포넌트가 언마운트 될 때 자동으로 초기화시켜주기 때문에 편한데, 현재 그러지 않는 상태라고 볼 수 있습니다.

이런 부분은 기본적인 건데 조금 더 꼼곰하게 확인해주세요 ㅠㅠ

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
> +				groupInfo={groupInfo}
그룹 관련 컴포넌트들을 보니 옵셔널 체이닝을 너무 많이 쓰고 있는데, 이 부분이 의도치 않은 에러가 발생하는 원인이 되는 것 같고, 좋은 방식이 아닌 것 같습니다. 옵셔널 체이닝은 "해당 프로퍼티가 존재하지 않아도 괜찮을 때만" 써야 합니다. 하지만 하위 컴포넌트들은 다 필요한 프로퍼티를 참조할 때도 쓰고 있죠

Prop으로 보자면 group.groupInfo를 기반으로 하고 있는데, 해당 groupInfo 내부 프로퍼티(데이터)들이 존재하지 않으면 아예 렌더링하면 안되게 처리해야하는 게 정상입니다.

최상단, 즉 group-slice에서 groupInfo를 가져오는 컴포넌트에서 groupInfo가 있다면 이를 prop으로 가지는 컴포넌트들이 이것을 조회할 때 옵셔널을 사용할 필요가 없게 처리해야 할 것 같습니다. 여기 뿐만 아니라 GroupLeaderPage에서도 쓰이던데 마찬가지입니다.

```jsx
useEffect(()=> {
// unwrap 처리하여 에러가 났을 경우(groupInfo를 가져오지 못한 경우) 이전 페이지로 navigate
},[])

{groupInfo && <GroupProfile groupInfo={groupInfo} />}
```

위와 같이 처리한 후 관련 하위 컴포넌트들의 옵셔널 연산자를 모두 제거해주시길 바랍니다

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
> +	const [isGroupLeader, setIsGroupLeader] = useState(false);
두 state는 필요없이 groupInfo 내부 프로퍼티로 비교하면 될 것 같습니다.

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
>  					</FeedDiv>
아예 그룹 피드가 없을 경우에 보여줄 화면도 필요할 것 같아요. 지수님과 얘기해보죠

특이 이점은 내가 그룹원이 아닌 상태면서 Private가 아닌 그룹에 들어갔을 때 더 두드러집니다

![스크린샷 2023-12-28 오후 12 38 56](https://github.com/Selody-project/Frontend/assets/78777345/29529c9c-d7cc-4eda-ba2f-085dcca0dcb5)

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
>  						/>
그룹 멤버가 아닌 경우 이게 사라지게 되면서 중간에 그룹 피드 div가 flex로 인해 끝까지 벌어지게 되는데 의도하신 걸까요?
그게 아니라면 레이아웃 통일성을 위해 이 부분의 공간은 여백으로 남겨두는 게 좋아보입니다.

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupDelegateModal.jsx
> +const GroupDelegateModal = ({ groupDetailInfo, groupMember }) => {
groupMember -> groupMembers

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupDelegateModal.jsx
> +	};
로그만 남길 용도로 unwrap 처리하는 건 필요 없어보입니다. extraReducer에서 에러 처리를 해주시면 될 것 같아요

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupDelegateModal.jsx
> +	};
```js
setSelectedMemberId((prev) => (prev === userId ? null : userId));

```

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupManagementProfile.jsx
> +			)}
여기서 groupDetailInfo와 내부 프로퍼티들이 존재한다고 확신할 때만 이 모달을 렌더링해야 합니다. `GroupDeleteModal` 이 있다는 조건을 추가해서 렌더링하고, `GroupDeleteModal` 내부의 옵셔널 연산자를 모두 제거해주시면 됩니다. 

(이 방법이 싫다면 모달 내부에서 로딩(groupDetailInfo가 없을 때) 중 보여줄 또 다른 컴포넌트를 지정하면 됩니다. 대신 그런 디자인이 없기도 하고, 이 방식을 쓰더라고 결국 옵셔널 연산자는 모두 지우게 될 겁니다)

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupManagementProfile.jsx
> +			)}
위에서 리뷰했던 groupInfo의 하위 프로퍼티가 groupDetailInfo였네요. 그 리뷰를 해결하면 이 부분은 그냥 옵셔널 연산자를 지우기만 하면 해결되겠네요

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupManagementProfile.jsx
> +			descriptionValue !== groupDetailInfo?.description ||
전부 trim하여 비교

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupManagementProfile.styles.js
> +	}
focus되었을 때 Input과 다르게 primary 색으로 outline 처리가 되지 않음

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupManagementProfile.jsx
> +	};
공개 여부를 수정하는 것도 로직 상 '변경 정보 저장하기' 버튼 클릭 시(onSubmit) 같이 실행해야 하는 것 아닐까요?
`isPublic`이 변경되도 `isSaveEnabled`가 true가 되지 않는 게 어색한 것 같습니다.

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +	);
groupMemberList state를 애초에 배열 처리하여 옵셔널을 제거하고, member가 나밖에(그룹장) 없을 때 보여줄 ui도 있으면 좋겠네요(지수님과 상의 필요)

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +	const groupId = groupInfo?.information.group.groupId;
groupInfo가 있을 때만 컴포넌트를 렌더링하도록 상위에서 수정하고 내부 옵셔널 제거

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +				<TitleLi red>내보내기</TitleLi>
이건 어차피 멤버 하나하나마다 존재할 텐데 title에서는 없어도 될 것 같은데요?

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +			{memberList?.map((memberInfo) => (
옵셔널 제거

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +						click
isClickable

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +		dispatch(changeAccessLevel({ groupId, userId, accessLevel }));
이 관리창에서도 그룹장 위임을 할 수 있나요? 내가 그룹장인 상태에서 다른 멤버에게 Owner 권한을 주면 내 권한은 어떻게 되나요?

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +											onClick={() => {
셋 중 하나를 반영해야 할 것 같습니다

1. 여기서 보여줄 권한 선택지에서 현재 권한을 제외한 옵션만 보여줄 것
2. 다 보여주되, 현재 권한과 같은 선택지는 disabled 처리
3. 다 보여주고, 클릭 가능하게 하지만, 핸들러 함수에서 현재 권한과 같은 것이면 dispatch하지 않도록 하기

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupDeleteModal.jsx
> +				</ModalFooter>
여기서는 다른 사람에게 위임만 하는게 아니라 위임하고 탈퇴하는 로직이 같이 들어가야 하지 않을까요?
- 문구 수정: "다른 사람에게 그룹장 위임하고 탈퇴"
- `GroupDelegateModal`에서 submit 시 유저가 탈퇴되는 로직도 추가

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupDeleteModal.jsx
> +				</ModalFooter>
(추가) 이 부분은 그룹 인원이 나 하나 뿐이라면 안보여줘야 함

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupManagementProfile.jsx
> +				</ExitButton>
그룹 인원이 나 하나뿐이라면 렌더링 X

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfile.jsx
> +	const groupDetailInfo = groupInfo?.information.group;
이 부분도 상위 컴포넌트에서 groupInfo가 무조건 존재하도록 처리하면 옵셔널 연산자가 필요 없겠네요

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfile.jsx
> +			)}
그룹장 밖에 없다면 이를 비활성화해야 하는데, 이 부분은 `GroupProfileButton`에서 아예 렌더링 안하도록 처리하면 여긴 건드릴 필요는 없을 것 같습니다. 참고만 하시라고 comment 남깁니다!

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +					}}
이 onClick 이벤트 리스너가 그룹 참여 요청을 한 경우(옵션이 켜진 경우) 옵션 메뉴를 클릭할 수 없게 하는데, 해당 부분을 제외한 영역을 클릭한 경우에만 navigate되도록 수정해주세요

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +					}}
![스크린샷 2023-12-28 오후 2 18 16](https://github.com/Selody-project/Frontend/assets/78777345/9eb4c6ba-3b0f-475f-b487-f8a93604f06d)

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupRequestCancelModal/GroupRequestCancelModal.jsx
> +	const handleCancelGroupJoin = async () => {
async 필요 없음

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/GroupRequestCancelModal/GroupRequestCancelModal.styles.js
> +`;
고정된 padding이 아니라 그냥 중앙 정렬되도록 처리해주세요
![스크린샷 2023-12-28 오후 2 21 47](https://github.com/Selody-project/Frontend/assets/78777345/6d7205c2-5c33-478a-892d-f5ed67ea56bc)

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/CommunityPage/CommunityPage.jsx
> +						setTabIndex={setTabIndex}
리팩토링 이후 닫아주시면 될 것 같아요

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/MyGroup/MyGroup.jsx
transform은 scroll보다 매우 효율이 안 좋은 방식입니다([관련 링크](https://stackoverflow.com/questions/9269237/is-there-performance-difference-between-transform-translate-ans-scroll)). scroll로 로직 수정 부탁드립니다!

해당 요소에 scroll eventListener를 달아주고, 이동 시에는 scrollTo와 같은 메서드를 사용하면 됩니다.

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/MyGroup/MyGroup.jsx
> +						{userGroupList?.map((info) => (
옵셔널 제거. 빈 배열인 경우 자동으로 생략됨

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/MyGroupFeed/MyGroupFeed.jsx
> +					</OptionDiv>
내가 작성한 글이 아닌 경우 안 보여줘야 하는 옵션이네요...
이런 것도 꼼꼼하게 구현 부탁드려요 ㅠㅠ

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/MyGroupFeed/MyGroupFeed.jsx
> +		}
isMine 체크는 필요 없는 조건입니다. 애초에 렌더링을 안 시켜야 하는 컴포넌트에서 발생하는 이벤트입니다.

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/MyGroupFeed/MyGroupFeed.jsx
> +	const handleLikeClick = (isLike, postGroupId, postId) => {
isLike -> isLiked

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/MyGroupFeed/MyGroupFeed.jsx
> +			dispatch(cancelLikeGroupPost({ postGroupId, postId }));
이것도 해당 로직이 완료되면 myGroupPosts에서 해당 post를 찾아 isLiked를 당연히 업데이트 해야 합니다...!

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Group/MyGroupFeed/MyGroupFeed.styles.js
> +export const IconItemDiv = styled.div`
button으로 변경 및 cursor pointer

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Header/GroupCreateModal/GroupCreateModal.jsx
> +				onChange={(e) => setGroupName(e.target.value)}
그룹 이름도 길이 제한 있을 겁니다
```js
const groupSchema = Joi.object({
    name: Joi.string().min(1).max(45).required(),
    description: Joi.string().max(300),
});
```

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Header/GroupCreateModal/GroupCreateModal.jsx
> +				maxLength={40}
maxLength가 300자인 것 같아요.

2023-12-28 06:26 UTC, kimyoungyin commented on src/components/Header/GroupCreateModal/GroupCreateModal.jsx
> +	const isButtonClickAble = () => groupName.trim() && groupDescription.trim();
groupDescription은 선택사항입니다. 업로드할 때만 trim 처리하면 될 것 같아요

2023-12-28 06:26 UTC, kimyoungyin commented on src/features/group/group-slice.js
> +	groupMemberList: null,
[]

2023-12-28 06:26 UTC, kimyoungyin commented on src/features/group/group-slice.js
> +				state.isEnd = payload.isEnd;
빈 배열에 대한 대응

2023-12-28 06:26 UTC, kimyoungyin commented on src/features/post/post-slice.js
> +				});
`state.allGroupPosts = [ ...state.allGroupPosts, ...payload.feed ]`

2023-12-28 06:26 UTC, kimyoungyin commented on src/features/post/post-slice.js
> +				});
여기도 위와 마찬가지!

2023-12-28 06:26 UTC, kimyoungyin commented on src/features/user/user-slice.js
> +			);
`getUserGroups`와 `GetRequestUserGroups` 를 MyPage에서 동시에 dispatch하던데, `isUserGroupFetching`을 공유하고 있어 둘 중 하나가 먼저 끝나면 나머지 하나가 완료되기 전에 false가 되어버리지 않을까요?

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +		dispatch(getRequestUserGroups());
둘이 같은 로딩 state를 공유하던데 괜찮을까요?

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +	const auth = useSelector((state) => state.auth.user);
굳이 auth라 명명을 변경한 이유가 있을까요? 그냥 user나 currentUser가 더 맞는 표현인 것 같아요

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +	const [introduction, setIntroduction] = useState("");
필요없는 state입니다. 이미 auth에서 가져올 수 있습니다

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +		}
필요 없는 setState입니다. 이미 auth에 있습니다

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +							<p>{introduction}</p>
`introduction || "소개글을 입력해주세요."`

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/GroupPage/GroupLeaderPage/GroupLeaderPage.jsx
> +		dispatch(getGroupRequestMemberList(param.id));
둘이 같은 loading state를 공유하지 않나요?

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/GroupPage/GroupLeaderPage/GroupLeaderPage.jsx
> +			<GroupManagement groupInfo={groupInfo} />
여기서 확실히 groupInfo가 있을 때만 하위 컴포넌트들을 렌더링하도록 해야 할 것 같습니다. 그러면 하위에서 굳이 groupInfo가 존재하는 지에 대한 검증을 할 필요가 없게 됩니다.

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/CommunityPage/CommunityPage.jsx
> +			searchGroup({ keyword: searchKeyword, recordId: searchLastRecordId }),
키워드 trim 처리, input이 있어야만 검색 가능해야 함
현재 상태: 공백만 가득 차도, Input이 없어도 검색이 가능함

2023-12-28 06:26 UTC, kimyoungyin commented on src/pages/CommunityPage/CommunityPage.jsx
> +		if (searchKeyword.length <= 1) {
여기서 trim 처리 해주어야 하겠네요

2023-12-28 12:33 UTC, sikkzz commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +				>
내부에 img나 heading등 다른 요소들이 존재하는걸 고려하면 두개다 어울리지 않는거 같네요

2023-12-28 12:35 UTC, sikkzz commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +const GroupInfoList = ({ groups, scrollRef, index }) => {
과거 리뷰에서 index로 변경하는게 좋다고 해서 변경한부분입니다. 어떤게 나을까요?

2023-12-28 12:41 UTC, sikkzz commented on src/components/Group/GroupManagement/GroupInviteLink/GroupInviteLink.jsx
Modal로 작성을 한게 아니라서 불필요하다고 생각했습니다.
모달로 작성 안한 이유는 저희 모달들은 화면 가운데 렌더링되는데 해당 디자인은 아니기도 했구요

2023-12-28 12:53 UTC, sikkzz commented on src/components/Group/GroupProfile/GroupProfileButton.jsx
> +	const profileButtonRender = [];
저는 해당 내용이 발견되지는 않네요?
수정하는건 문제가 아닌데 key값 오류는 확인 했는데 다른 그룹 접근 시 정상적으로 버튼 확인 됩니다. console로 찍어도 마찬가지구요

2023-12-28 13:02 UTC, sikkzz commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +				<TitleLi red>내보내기</TitleLi>
디자인 상으로 존재합니다. 불필요시 회의때 말씀해주세요

2023-12-28 13:11 UTC, sikkzz commented on src/components/Group/GroupRequestCancelModal/GroupRequestCancelModal.styles.js
> +`;
모달 통일되면 수정할게요. 제가 작성한 코드가 아니라서요

2023-12-28 16:53 UTC, sikkzz commented on src/components/Group/GroupSearch/GroupSearch.jsx
> +	const [groups, setGroups] = useState([]);
검색된 그룹을 담는 경우와 그렇지 않은 경우 두가지 케이스를 상황마다 담아줘서 그렇습니다

2023-12-28 16:53 UTC, sikkzz commented on src/components/Group/GroupSearch/GroupSearch.jsx
> +	});
위와 동일하게요

2023-12-28 16:58 UTC, sikkzz commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +		dispatch(changeAccessLevel({ groupId, userId, accessLevel }));
따로 논의를 안했었네요 현재는 아무 제약 없이 넘어가는거 같아요

2023-12-28 17:12 UTC, sikkzz commented on src/components/Header/GroupCreateModal/GroupCreateModal.jsx
> +				maxLength={40}
과거 회의때 40자로 하기로 했던거 같은데 아니였을까요?

2023-12-29 00:55 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfileButton.jsx
> +	const profileButtonRender = [];
@sikkzz 
예시 화면 올려드릴게요
처음 접속한 그룹은 제가 만든 그룹이고, 두 번째 접속한 그룹은 준식님이 만든 그룹입니다. 

https://github.com/Selody-project/Frontend/assets/78777345/9ee29ca8-61b9-495a-9685-641c3c477bb3

2023-12-29 00:58 UTC, kimyoungyin commented on src/components/Group/GroupSearch/GroupSearch.jsx
> +	const [groups, setGroups] = useState([]);
그냥 groupList를 그대로 쓰고, 두 경우가 스위칭 될 때마다 새로 대체해주면 되지 않을까요?

2023-12-29 01:01 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +				>
음 내부에 img, h 태그 등이 들어가면 안되는 이유가 있나요?

2023-12-29 01:38 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfileButton.jsx
> +	const profileButtonRender = [];
제가 테스트해보니까 **두 가지 방법**으로 문제를 해결할 수 있습니다. 아래 코드는 모든 옵셔널 체이닝 연산자를 제거하고, `forEach`보다 `some` 빌트인 메서드로 대체하여 코드 작성했습니다.

저는 첫 번째 방식을 사용하길 **강력 권고**합니다. 불필요한 state 사용은 지양해야 하기 때문입니다. 두 번째 방식은 참고만 하시라고 올려드려요

## 첫 번째 방식(강력 권고)
GroupPage에서 `GroupInfo`를 통해 받아온 데이터를 그대로 state로 사용하지 않고, `isGroupMember`와 `isGroupLeader`로 따로 받아서 사용해서 생긴 문제로 확인됩니다. 그냥 두 값을 그냥 컴포넌트 내부에서 userGroups가 변경됨에 따라 판단되는 '변수'로써 사용하면 해결됩니다.
```js
	// const [isGroupMember, setIsGroupMember] = useState(false);
	// const [isGroupLeader, setIsGroupLeader] = useState(false);

	const isPublicGroup = groupInfo.information.group.isPublicGroup;
	const leaderId = groupInfo.information.leaderInfo.userId;

	const isGroupLeader = user.userId === leaderId;
	const isGroupMember = userGroups.some(
		(group) => group.groupId === Number(param.id),
	);

	useEffect(() => {
		dispatch(getGroupInfo(param.id));
		dispatch(getGroupRequestMemberList(param.id));
		dispatch(getUserGroups());
	}, []);

	// useEffect(() => {
	// 	console.log(user.userId, leaderId);
	// 	if (user.userId === leaderId) {
	// 		setIsGroupLeader(true);
	// 		setIsGroupMember(true);
	// 	} else {
	// 		userGroups?.forEach((info) => {
	// 			if (info.groupId === Number(param.id)) {
	// 				setIsGroupMember(true);
	// 			}
	// 		});
	// 	}
	// }, [userGroups, leaderId]);

```

## 두 번째 방식(비추천)
useEffect 내에 조건문 수정: 컴포넌트가 매우 많이 리렌더링 되는 과정에서, 한 번 `true`로 변해버린 `isGroupLeader` state가 `false`로 바뀔 수 있는 코드가 없음 `setIsGroupLeader(false)`
```js
	useEffect(() => {
		if (user.userId === leaderId) {
			setIsGroupLeader(true);
			setIsGroupMember(true);
		} else {
			setIsGroupLeader(false);
			const isAlreadyMember = userGroups.some(
				(info) => info.groupId === Number(param.id),
			);
			setIsGroupMember(isAlreadyMember);
		}
	}, [userGroups, leaderId]);
```

2023-12-29 01:41 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
> +	const [isGroupLeader, setIsGroupLeader] = useState(false);
위 리뷰 보시면 자동 해결됩니다
[리뷰 링크](https://github.com/Selody-project/Frontend/pull/159#discussion_r1437942900)

2023-12-29 01:42 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +				<TitleLi red>내보내기</TitleLi>
그니까요 얘기해봅시다

2023-12-29 01:48 UTC, kimyoungyin commented on src/components/Header/GroupCreateModal/GroupCreateModal.jsx
> +				maxLength={40}
아 그랬었나요? 그러면 title도 40자 제한이던데, 해당 부분 회의로 정해보죠!

2023-12-29 10:24 UTC, sikkzz commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +				>
div태그가 저희가 흔히 생각하는 다른 요소들이 담기는 Box의 역할을 하는데 비해 anchor태그와 button태그 또한 각각의 역할이 있지 않나요? 어떤 시멘틱 태그 측면을 고려해서 변경하는게 좋은건지 잘 모르겠어요

2023-12-29 11:36 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +											onClick={() => {
3번으로 진행

2023-12-29 11:37 UTC, sikkzz commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +											onClick={() => {
3번으로 수정하겠습니다,

2024-01-02 12:10 UTC, sikkzz commented on src/components/Header/GroupCreateModal/GroupCreateModal.jsx
> +				onChange={(e) => setGroupName(e.target.value)}
그룹 이름 20자, 그룹 소개 100로 변경

2024-01-02 12:10 UTC, sikkzz commented on jest.setup.js
> +
기본 렌더링 테스트 코드 작성 중에 에러가 나서 서칭해보니까 관련 로직을 작성해야 하더라구요 임시로 처리해놓은거라 나중에 테스트 코드 작성할때 수정해야 합니다 안넣으면 test가 안돌아가서요

2024-01-02 12:10 UTC, sikkzz commented on __test__/__mocks__/mockIntersectionObserver.js
위와 동일합니다

2024-01-02 12:10 UTC, sikkzz commented on src/features/post/post-slice.js
> +				});
해당 방식으로 수정했는데 작동을 안하는 부분이 있네요 해결을 못해서 한번 확인해주실 수 있나요?

1. 그룹 페이지에서 새로고침시 post 렌더링 안됨
2. 다른 그룹 페이지 접근시 다른 그룹 post도 같이 렌더링

2024-01-05 08:04 UTC, sikkzz commented on src/components/Group/MyGroup/MyGroup.jsx
carousel은 scroll의 방식으로 작동하지 않습니다. 현재 로직은 전체 width가 디스플레이를 넘어갈정도로 클때 overflow 상태로 보여지고 버튼 클릭시 해당 컴포넌트에서 일정 gap만큼 이동하는 방식인데 scrollTo는 윈도우 기준으로 이동하지 않나요?

2024-01-08 06:40 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +				>
오히려 `div`가 의미가 없는(필요없는 게 아니라 '의미' 자체가 없는 그저 영역 묶음인) Box입니다. 일단 해당 구역은 클릭했을 때 **'Route를 이동시키기 때문에'** `a`(`Link`)를 사용하는 것이 원칙상 맞긴 합니다. 

`div`는 정말 여러 요소들을 **묶기만** 해야 되는 것이라면 사용하는 게 좋습니다.

2024-01-08 06:45 UTC, kimyoungyin commented on src/components/Group/MyGroup/MyGroup.jsx
요소 자체도 scrollTo로 구현 가능합니다.
[관련 공식 문서](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo)

일정 gap만큼 transform을 주는 것이 아니라, scrollTo(혹은 다른 scroll 관련 메서드)를 사용하여 이동시키면 됩니다.
저도 해당 부분 구현해본 경험이 있으니 모르는 게 있으면 연락주세요!

2024-01-08 07:33 UTC, kimyoungyin commented on src/features/post/post-slice.js
> +				});
1. 첫 렌더링시 무조건 한 번(componentDidMount) 모든 피드를 GET 해야 하는데 `isObserving && !isEnd` 조건으로 필터링하고 있음. 확인해보니 새로 고침 시 `isObserving`이 `false`임.
   - 해결법 1: 해당 함수(`dispatchgetGroupAllPosts`)를 위에 deps가 없는 `useEffect` 안에서 한 번 호출해야 함.
   - 해결법 2(이게 맞지 않을까요?): `useObserver` 내부 `isObserving`의 Initial state를 `true`로 변경 후 **아래 2번 내용**을 반영. 일단 Observe는 무조건 할 거니까? 

2. `GroupPage`가 언마운트될 떄 피드 관련 `state`의 초기화 작업(빈 배열로, `lastRecordId`를 0으로)이 없음. 
    - 해당 부분을 `reducer`로 하나 만들어 `GroupPage`에서 cleanup function에서 호출하는 코드를 추가해야 함

전역 state는 이를 사용하는 컴포넌트가 어떤 상태이건 상관 없이 유지된다는 점을 잊지 마세요!

@sikkzz

2024-01-08 08:21 UTC, kimyoungyin commented on src/components/Common/Feed/Feed.jsx
> +		setOptionMenuOpenedFeedIndex((prev) => (prev === num ? null : num));
이걸 Feed 내부에서 구현하면 의미가 없습니다. 실제로 다른 옵션을 클릭했을 때 켜져있던 옵션이 꺼지지도 않구요

옵션이 열려있는 피드에 대한 state 관리는 `Feed`의 상위 컴포넌트에서 해줘야 합니다.

```js
// Parent.js
	const [optionMenuOpenedFeedIndex, setOptionMenuOpenedFeedIndex] =
		useState(null);

    feeds.map(feed => 
        <Feed 
            post={feed} 
            optionOpenedFeedIndex={optionMenuOpenedFeedIndex} 
            onThreeDotClick={(postId) => setOptionMenuOpenedFeedIndex(postId)}
        />)
```
```js
// Feed.jsx
const Feed = ({ post, optionOpenedFeedIndex, onThreeDotClick }) = > {
// ...
    <OptionThreeDotIcon
        onClick={( ) => onThreeDotClick(post.id)}
    />
    {optionOpenedFeedIndex === post.id && ... }
// ...
};
```

2024-01-08 08:22 UTC, kimyoungyin commented on src/components/Common/Feed/Feed.jsx
> +const Feed = ({ groupId, post }) => {
groupId는 post 내부 프로퍼티이므로 분리할 필요가 없습니다.

2024-01-08 08:23 UTC, kimyoungyin commented on src/components/Common/Feed/Feed.jsx
> +						}}
`onClick={handleLikeClick}`

2024-01-08 08:25 UTC, kimyoungyin commented on src/components/Common/Feed/Feed.jsx
> +	HeartClickIcon,
`HeartClickIcon`은 의미가 모호한 것 같아요.
`emptyHeartIcon`, `filledHeartIcon` 이렇게 하는 건 어떠세요?

2024-01-08 08:26 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +					<Feed post={post} key={post.postId} groupId={groupId} />
여기서 Feed의 리뷰 사항을 반영해주세요. 여기서 어떤 index의 option을 열 지의 id값은 postId로 쓰시면 됩니다.

2024-01-08 08:28 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +					</InfoDiv>
Div -> Link

2024-01-08 08:30 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagement.styles.js
> +export const InnerDiv = styled.div``;
아무 스타일도 없으면 그냥 div로 작성하면 되지 않을까요?

2024-01-08 09:23 UTC, sikkzz commented on src/components/Common/Feed/Feed.jsx
> +const Feed = ({ groupId, post }) => {
api에서 문제가 있어서 분리해놨습니다. 그룹 피드 조회랑 내 그룹 피드 조회 api 2개 확인해보시면 그룹 피드 조회 api 결과값에 그룹 Id가 없습니다. 그래서 따로 넘겨줘야하더라구요. 

백엔드에서 수정 가능하면 이부분도 수정이 가능할 거 같아요

2024-01-08 09:43 UTC, sikkzz commented on src/components/Group/GroupManagement/GroupManagement.styles.js
> +export const InnerDiv = styled.div``;
미사용이네요 삭제 했습니다.

2024-01-09 10:54 UTC, sikkzz commented on src/features/post/post-slice.js
> +				});
해결이 되지는 않네요.. 흠 뭐를 잘못하고 있는건지

2024-01-11 14:35 UTC, sikkzz commented on src/components/Group/MyGroup/MyGroup.jsx
scroll에 대한 이동이 안보이네요 방법 좀 알려주시겠어요?

2024-01-11 15:05 UTC, sikkzz commented on src/features/group/group-slice.js
>  				state.isLoading = false;
커뮤니티 페이지에서 내 그룹 목록은 user slice에서 관리하고 create group은 group slice에서 관리됩니다. 합쳐서 관리한다 쳐도 createGroup payload값이 group정보랑 다른데 추가할 방법이 안보이네요 어떻게 해야 할까요?

2024-02-05 05:27 UTC, kimyoungyin requested changes
일단 자잘한 asset과 그룹 초대 관련만 리뷰했습니다

우선적으로 확인 부탁드려요

2024-02-05 05:27 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +	}, []);
전역으로 관리하지 않고 여기서 먼저 초대코드 GET을 한 뒤, exp가 지났으면 다시 POST 요청해서 받아오면 좋을 것 같네요. 해당 코드는 내부 state로 관리하구요

2024-02-05 05:27 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +	const { groupInfoWithInviteLink } = useSelector((state) => state.group);
이걸 굳이 전역으로 가지고 있을 필요 없을 것 같습니다.

2024-02-05 05:27 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +				>
직접 Url을 입력하는게 아니라 `window.location.host`를 써야 할 것 같습니다.

2024-02-05 05:27 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +							`http://localhost:3000/group/${groupInfoWithInviteLink?.groupId}?invite=${inviteLink.inviteCode}`,
이건 그냥 `onClick={handleCopyClipBoard}`하고 핸들러에서 처리하면 될 것 같네요.
복사할 url은 정해져 있으니까요

2024-02-05 05:27 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +	const { groupInfoWithInviteLink } = useSelector((state) => state.group);
링크, isLoading을 useState를 사용하고, isLoading이 true라면 복사 클릭이 안되도록 disabled 처리하면 될 것 같습니다.

2024-02-05 05:27 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
>  			)}
GroupJoin을 거절했을 때(X 버튼을 눌렀을 때) `setSearchParams`로 초대코드가 포함된 Url을 초기화시켜줘야 합니다.

2024-02-05 05:33 UTC, kimyoungyin commented on src/features/group/group-slice.js
>  				state.isLoading = false;
slice는 합칠 필요 없고 `createGroup.fulfilled` action을 `user-slice`의 `extraReducer`에 연결하면 됩니다.

후자 내용은 POST의 Response가 userGroupList의 객체와 프로퍼티가 다르다는 것 같은데, 이 부분은 제가 반영해두겠습니다.
(애초에 createGroup의 Response는 계속 그룹의 요약 정보를 제공하고 있는데 이를 활용하고 있지 않더군요. 위 때문에 그랬던 거겠죠?)

2024-02-05 05:39 UTC, kimyoungyin commented on src/features/group/group-slice.js
>  				state.isLoading = false;
+ 확인해보니 userGroupList 요소의 프로퍼티가 다 사용되지 않네요. 오히려 POST의 Response 정도면 데이터 정보량이 충분한 것 같습니다. userGroupList 조회 API의 response 프로퍼티를 POST response에 맞춰 줄이도록 하겠습니다.

2024-02-05 07:39 UTC, kimyoungyin requested changes
나머지는 계속 리뷰 진행할게요

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/Feed/Feed.jsx
> +		dispatch(deleteGroupPost({ postGroupId: groupId, postId }));
fulfilled 시 `post-slice`에서 `allGroupPosts`, `myGroupPosts` Update

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/Feed/Feed.jsx
> +	const deletePost = (postId) => {
postId를 param으로 받을 필요 없음

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/Feed/Feed.jsx
> +											deletePost(post.postId);
`onClick={deletePost}`

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/Feed/Feed.jsx
> +	const [postIsLiked, setPostIsLiked] = useState(post.isLiked);
isPostLiked가 맞는 표현인 것 같습니다

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupCreateModal/GroupCreateModal.jsx
> +				<GroupImgAddIcon />
이미지 업로드 기능은 나중에 구현 예정인가요? 그렇다면 이슈나 PR에 저번에 얘기드린 부분과 함께 정리 부탁드립니다.

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupCreateModal/GroupCreateModal.jsx
> +			<GroupNameH3>그룹 이름</GroupNameH3>
이건 label 태그로 처리해서 textarea에 연결시켜주는 게 좋아보입니다.

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupCreateModal/GroupCreateModal.jsx
> +			<GroupIntroduceH3>그룹 소개</GroupIntroduceH3>
이것도 label 태그로 처리해서 textarea에 연결시켜주는 게 좋아보입니다.

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupCreateModal/GroupCreateModal.jsx
> +			description: description.trim(),
description이 빈 문자열일 경우 `undefined` 처리해줘야 합니다. 빈 문자열 채로 POST 요청 시 실패합니다.

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupDelegateModal/GroupDelegateModal.jsx
> +	</SelectBoxDiv>
리스트이니 `li` 태그로 처리하는 게 맞아보입니다.

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupDelegateModal/GroupDelegateModal.jsx
> +					<SelectWrapDiv>
`ul` 태그가 맞아보입니다.

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupDelegateModal/GroupDelegateModal.jsx
> +			dispatch(setRefetchUserGroup(true));
이 dispatch는 용도가 뭔가요?

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupDeleteModal/GroupDeleteModal.jsx
> +					<p>그룹원이 없어야 삭제가 가능합니다</p>
그룹 삭제는 그룹원이 없어야 삭제 가능하다고 되어있는데, 이에 대한 validation이 안되있습니다. 바로 지워져요

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupJoinModal/GroupJoinModal.jsx
> +const GroupJoinModal = ({ inviteLink }) => {
close 시 searchParam을 초기화시켜줄 필요가 있습니다

2024-02-05 07:39 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
> +		}
exp가 지나지 않았는지, 유효한 링크인지 체크 후 띄워주는 게 좋아보입니다. 그게 아니라면 Url 초기화 시켜주구요

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupModal.Shared.styles.js
`Shared.styles.js`는 이상한 것 같은데요? 컨벤션에도 없던 내용이라 수정하는 게 어떨까요?

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +				allGroupPosts?.map((post) => (
allGroupPosts.map이면 충분합니다

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
에러가 있는 컴포넌트기 때문에 나중에 더 자세히 볼게요

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +							{openedModal === "REQUESTCANCEL" && (
오타... 이것 때문에 요청 취소 모달이 뜨지 않았었습니다.

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupRequestCancelModal/GroupRequestCancelModal.jsx
> +			navigate(`/community?${TAB_KEY}=${TAB_PARAM.MY_GROUP_FEED}`);
굳이 커뮤니티 페이지로 갈 필요 없어보입니다. onSubmit 이벤트 핸들러를 `GroupRequestCancelModal`의 prop으로 주고 부모 컴포넌트에서 요청 중인 그룹 배열 요소 중 '요청 취소'한 그룹을 제거해주는 setState(혹은 dispatch) 작업을 하면 됩니다.

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +					<Link to={`/group/${info.groupId}`}>
해당 요소에 요청 취소 menu가 떠있는 경우에는 이동하지 않고, menu를 꺼주기만 하는 게 좋아보이는데 어떠세요?
해당 요소에 열린 Menu가 꺼져있을 때만 link를 활성화하는 게 좋지 않을까요?

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagement.jsx
> +						disabled={
다른 탭들과 마찬가지로 굳이 disabled 처리할 필요는 없지 않을까 싶습니다. `not-allowed` cursor 처리된 것도 어색하네요

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagement.jsx
> +					{memberList.length ? (
`memberList.length === 0`

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagement.jsx
> +};
둘 중 하나니 굳이 constant를 생성할 필요 없이 boolean으로 구분하면 편하지 않을까요?

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagement.jsx
> +	const [menu, setMenu] = useState(GROUP_MANAGEMENT_TAB_TITLE.GROUP_PROFILE);
이것도 IsGroupProfile 뭐 이렇게 하고 boolean 처리하면 되지 않을까요?

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupManagementProfile.jsx
> +			isPublicGroup !== isPublic) &&
isPublickGroup은 number이고 isPublic은 boolean 값이어서 제대로 비교가 안됩니다. 한 번 변경한 순간 다시 되돌려도 두 값이 다르다고 판단해버립니다. 수정 부탁드려요

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupManagementProfile.jsx
> +		nameValue.trim();
어떤 건 구조분해할당으로 원래의 groupDetailInfo를 조회하고, 어떤 건 그대로 groupDetailInfo.~로 조회하니 일관성이 맞지 않는 것 같아요. 하나로 통일하는게 좋아보이는데요?

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupManagementProfile.jsx
> +			{openedModal === "DELETE_GROUP" && (
이것도 UI_TYPE으로 조회해야 안전하겠네요

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupManagementProfile.jsx
> +	const [profileObj, setProfileObj] = useState("");
이미지라고 변수명을 명시해줘야 할 것 같아요

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupManagementProfile.styles.js
> +	}
색이 너무 밝아서 별로인 것 같아요

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +		}
이 promise가 완료되었을 떄 처리가 필요한데 안했네요. extraReducer에서 작업 부탁드립니다
- fulfilled: groupMemberList에서 해당 멤버 accessLevel 업데이트
- rejected: 실패 toast 띄우기

2024-02-05 07:39 UTC, kimyoungyin commented on src/App.jsx
> +			{ path: "group/:id/leader", element: <GroupLeaderPage /> },
이 Route는 그룹 리더가 아닐 때 접근 불가능(리다이렉트)하도록 설정해야 합니다.

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +		}
owner로 변경했을 경우는 unwrap 처리 후 이 컴포넌트에서 그룹 메인으로 redirect 시키기 등등...

2024-02-05 07:39 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +									내보내기
이것도 경고 모달이 하나 더 필요하지 않을까요?

2024-02-05 11:31 UTC, sikkzz commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +	}, []);
전역으로 관리하지 않는다는게 slice에서 관리하지 않고 내부 컴포넌트에서 사용하자는 말씀 맞으실까요? 맞다면 여기서 dispatch로 받는 결과값을 내부에서만 받아올 방법이 있나요?

이게 아니라면 제가 이해를 잘못한건지 모르겠네요

2024-02-05 11:39 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +	}, []);
네 전자가 맞습니다

2024-02-06 02:10 UTC, kimyoungyin requested changes
일단 이 부분 변경사항 리뷰했습니다

2024-02-06 02:10 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +			createGroupInviteLink(setInviteLink, groupId, setIsLoading);
setState를 바로 인자로 담지 말아주세요..

2024-02-06 02:10 UTC, kimyoungyin commented on src/utils/groupInviteUtils.js
> +};
- 그냥 하나로 묶는게 편하지 않아요? 먼저 GET 요청을 하고 response를 분석하고 유효하면 그대로, 아니면 다시 POST 요청해서 만드는 식으로 하면 되지 않을까요? 이게 이 유틸을 사용할 때 편할 것 같네요.
- `isLoading`: 유틸 함수 내부로 가져올 필요는 없어보이네요. 또 `isLoading`은 함수보단 원시 값처럼 보이는 이름이라 어색하네요.
- `groupId`: 이거만 Param으로 가져오면 됩니다

2024-02-06 02:10 UTC, kimyoungyin commented on src/utils/groupInviteUtils.js
> +};
이건 dispatch해야 할 action 아닌가요? 완료되면 UserGroupList에 넣어줘야 하니까요

2024-02-06 02:10 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupJoinModal/GroupJoinModal.jsx
> +		};
유효하지 않은 초대 링크(exp 지남 혹은 잘못된 경우)로 조회 시도했을 땐 redirect해줘야

2024-02-06 02:10 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupJoinModal/GroupJoinModal.jsx
> +		};
HOME이든 어디든

2024-02-06 02:10 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +			createGroupInviteLink(setInviteLink, groupId, setIsLoading);
두 개를 하나의 Util로 통일하여 `const groupInviteLink = await getGroupInviteLink(groupId);`

2024-02-06 02:10 UTC, kimyoungyin commented on src/features/group/group-service.js
> -
이건 필요하지 않을까요? 다른 comment를 참고해보실래요?

2024-02-08 07:58 UTC, kimyoungyin requested changes
더 볼게요

2024-02-08 07:58 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +			)}
inviteLink가 있기 전까지 대기하는 게 아니라 `MiddleDiv` rendering은 시켜놓고 '복사' 버튼만 disabled 처리했다가 inviteLink가 생기면 enable시키는 게 나아보이지 않나요?

2024-02-08 07:58 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +	};
복사되었다는 toast를 띄워줘야 할 것 같아요

2024-02-08 07:58 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
> +		}
생각해보니 이미 이 그룹의 유저라면 그냥 GroupPage로 redirect되어야 하지 않을까요? userGroupList에서 찾아보면 될 것 같습니다

2024-02-08 07:58 UTC, kimyoungyin commented on src/components/Group/GroupMember/GroupMember.jsx
> +	groupInfo,
- `isGroupMember`: 그룹 멤버인 경우만 이 컴포넌트를 보여주면 되므로 굳이 여기 prop으로 가져올 필요 없이 밖에서 display or not을 결젇하면 됩니다.
- `requestMemberList`: 어차피 group-slice에서 가져올 수 있어서 굳이 여기 prop으로 줄 필요 없어보입니다

2024-02-08 07:58 UTC, kimyoungyin commented on src/components/Group/GroupMember/MemberList.jsx
> +						<img src={info.member.image} alt="memberImg" />
alt를 'nickname`님의 이미지로 명시하는 게 좋아보여요

2024-02-08 07:58 UTC, kimyoungyin commented on src/components/Group/GroupMember/MemberModal/MemberModal.jsx
> +					</MemberUl>
scrollbar 지우는게 깔끔해보이네요

2024-02-08 07:58 UTC, kimyoungyin commented on src/components/Group/GroupMember/MemberModal/MemberModal.jsx
> +									)}
`ACCESS_LEVEL_DATA`를 쓸 때마다 순회해가면서 찾던데 그냥 `Map`이나 객체 자료구조를 쓰면 바로 찾기 쉽지 않을까요?

2024-02-08 07:58 UTC, kimyoungyin commented on src/components/Group/GroupMember/MemberModal/MemberModal.styles.js
> +export const MemberUl = styled.ul`
scrollbar 지우는게 좋지 않아요?

2024-02-08 07:58 UTC, kimyoungyin commented on src/components/Group/GroupMember/MemberModal/MemberRequestModal.jsx
> +							<MemberLi key={memberData.member.nickname}>
key로는 userId가 좋아보입니다

2024-02-08 07:58 UTC, kimyoungyin commented on src/components/Group/GroupProfile/GroupProfile.jsx
여기도 에러 포인트라 스킵

2024-02-08 07:58 UTC, kimyoungyin commented on src/components/Group/GroupSearch/GroupSearch.jsx
> +		};
이걸 이렇게 따로 뺀 이유가 있을까요? 그냥 바로 dispatch하면 안되나요?

2024-02-08 07:58 UTC, kimyoungyin commented on src/components/Group/MyGroup/MyGroup.jsx
관련 링크는 잘 달려있습니다. 실제 예시를 궁금해하시면 제가 구현했던 부분 코드 링크 올려드려요. 인스타 게시글 이미지 슬라이더입니다
[링크](https://github.com/Instagram-Clone-Coding/React_instagram_clone/blob/develop/src/components/Common/Article/ArticleImgSlider/ArticleImgSlider.tsx)

2024-02-08 07:58 UTC, kimyoungyin commented on src/components/PersonalTodoList/PersonalTodoItem/PersonalTodoItem.jsx
제 부분 rebase 안했었나요? 이 컴포넌트는 안 쓰입니다

2024-02-08 07:58 UTC, kimyoungyin commented on src/features/group/group-service.js
> +);
이게 정확히 어떤 thunk인지 이름만 보고 알기 쉽지 않았습니다. "그룹 가입 신청 또는 취소" 기능과 맞게 이름을 명시해주세요.
그리고 
- pending: 이게 신청인지 취소인지 api call하기 전에 어떻게 판단하나요? 이미 신청해놓은 사람이 그룹 참여 신청 요청을 다시 클릭 못하도록 막아둬야 할 텐데요? 그 반대도 마찬가지구요
- fulfilled: response 메세지에 따라 취소되었는지, 신청되었는지 명시해줘야 할 것 같아요

2024-02-08 08:26 UTC, sikkzz commented on src/components/Common/GroupModal/GroupModal.Shared.styles.js
과거 코드 리뷰때 영인님이 겹치는 스타일 이렇게 빼자고 제안했던거로 기억합니다

2024-02-09 09:22 UTC, kimyoungyin requested changes
GroupInviteLink 관련 하나 리뷰 남겨드려요

2024-02-09 09:22 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +					disabled={isLoading}
invitelink가 없을 때 disabled 처리

2024-02-09 09:32 UTC, sikkzz commented on src/components/Common/GroupModal/GroupCreateModal/GroupCreateModal.jsx
> +			description: description.trim(),
description이 빈 문자열 상태로는 api가 안넘어가네요 빈 값이어도 상관 없는거로 기획상 기억하는데

2024-02-09 09:39 UTC, sikkzz commented on src/features/group/group-service.js
> +);
api를 나누는게 좋지 않을까요? 하나로 합쳐서 동작시킬때의 장점이 있을까요? 그룹 참여 요청쪽을 아직 구현을 안해서 확인을 못했네요 저는 따로 동작하는게 좋을 거 같다고 생각합니다.

2024-02-14 08:00 UTC, kimyoungyin requested changes
에러 포인트 제외 진행했습니다. 해당 부분은 계속 해결 시도하죠..

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Common/Feed/Feed.jsx
> +	groupId,
post 안에 groupId가 있기 때문에 굳이 따로 prop으로 받을 필요는 없어보입니다.

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/SharePage/ShareTodoList/ShareTodoList.jsx
>  	const { inviteCode } = useSelector((state) => state.groupInvite);
이 컴포넌트가 지워질 거긴 하지만 해당 slice는 없는 거라 삭제해주시겠어요?
존재하지 않는 slice명입니다.

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Common/GroupModal/DeleteMemberWarningModal/DeleteMemberWarningModal.jsx
> +				deleteGroupMember({
fulfilled된 경우 group.groupMemberList를 업데이트 시켜주세요

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupCreateModal/GroupCreateModal.jsx
> +			description: description.trim(),
모델(스키마)에서는 description이 `allowNull: true`로 되어 있어서 빈 문자열인 경우 아예 데이터가 없다는 의미로 `null`을 담아 보내주시면 됩니다. 원래 undefined인 경우만 됐었는데 제가 반영시켜서 배포해놓을게요.

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupCreateModal/GroupCreateModal.style.js
> +	margin: 12px 0 14px;
margin-bottom은 2px만 주면 됩니다. form modal의 32px padding이 합쳐서 34px로 디자인과 동일해집니다. 반영 부탁드려요

2024-02-14 08:00 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +	const [searchParams, setSearchParams] = useSearchParams();
searchParams 없이 `/mypage`로 그냥 접근했을 때에 대처가 없습니다. setSearchParams로 초기값으로 초기화시켜주는 로직 추가 부탁드려요

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +					<Link to={!optionMenuOpenedFeedIndex && `/group/${info.groupId}`}>
`to` attribute를 빈값으로 처리하면 자동으로 현재 페이지로 이동하는 링크가 됩니다. 비활성화를 시켜주는 게 목적이니 다음 링크를 참조해서 수정해주세요
[Link 비활성화하기](https://stackoverflow.com/questions/38321601/easier-way-to-to-disable-link-in-react)

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +					<Link to={!optionMenuOpenedFeedIndex && `/group/${info.groupId}`}>
현재 상태에서는 `/mypage` 기준, `GroupRequestCancelModal`을 띄운 뒤에 클릭도 가능하고, 클릭하면 `/mypage`로 이동됩니다. 물론 여기서도 `searchParam`가 없는 문제도 보입니다

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupManagementProfile.jsx
> +		groupInfo.information.group.description,
null인 경우 빈 문자열로 대체 필요

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupManagementProfile/GroupManagementProfile.jsx
> +			description: descriptionValue,
빈 문자열인 경우 null로 변경 필요

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +		}
fulfilled된 경우 `memberList` 내 해당 유저 accessLevel 업데이트 필요합니다. 현재는 바로 컴포넌트가 업데이트 되지 않는 상태에요

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/AccessLevelInfo.styles.js
> +	left: -36px;
info 아이콘 딱 위에 있어야 하는데 텍스트 중앙에 위치해있네요

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Group/MyGroup/MyGroup.styles.js
> +export const Div = styled.div`
- 그냥 div는 이상한 것 같습니다.
- `overflow: hidden`보다 가로 스크롤은 열어두는 게 어떨까요?
```css
	overflow-x: auto;
	&::-webkit-scrollbar {
		display: none;
	}
	-ms-overflow-style: none;
	scrollbar-width: none;
```

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Group/MyGroup/MyGroup.styles.js
> +`;
캐러셀 딱 중간이 아닌 것 같아요.

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Group/MyGroupFeed/MyGroupFeed.jsx
> +						groupId={post.groupId}
post가 이미 groupId를 가지고 있어서 prop으로 따로 줄 필요 없습니다

2024-02-14 08:00 UTC, kimyoungyin commented on src/features/group/group-slice.js
하나의 action만 들어있는 경우 addMatcher, allof를 사용할 필요가 없습니다.
상단에서 addCase로 작성해주세요!

2024-02-14 08:00 UTC, kimyoungyin commented on src/features/post/post-slice.js
여기도 불필요한 addMatcher를 제거해주세요

2024-02-14 08:00 UTC, kimyoungyin commented on src/features/user/user-slice.js
> +			.addMatcher(isAllOf(createGroup.fulfilled), (state, { payload }) => {
여기도네요

2024-02-14 08:00 UTC, kimyoungyin commented on src/pages/CommunityPage/CommunityPage.jsx
> +	const [searchParams, setSearchParams] = useSearchParams();
여기도 그냥 `/community`로 접근 시도시 searchParams이 없으므로 첫 번쨰 tab으로 setSearchParams 처리해줘야 합니다.

2024-02-14 08:00 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
여기도 에러 포인트라 스킵할게요. 같이 원인을 찾아봐요

2024-02-14 08:00 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
> +			{openedModal === "JOIN_GROUP" && (
UI_TYPE 활용..

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +							{openedModal === "REQUEST_CANCEL" && (
UI_TYPE

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Group/GroupMember/MemberList.jsx
> +			{openedModal === "MEMBER_MODAL" && (
UI_TYPE

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Group/GroupMember/MemberRequestList.jsx
> +				{openedModal === "MEMBER_REQUEST_MODAL" && (
UI_TYPE

2024-02-14 08:00 UTC, kimyoungyin commented on src/components/Header/Header/Header.jsx
UI_TYPE

2024-02-14 08:00 UTC, kimyoungyin commented on src/pages/SettingPage/SettingPage.jsx
> +			{openedModal === "EXIT_GROUP" && <GroupExitModal />}
UI_TYPE

2024-02-15 04:45 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +				<CloseIcon onClick={() => onClose(false)} />
onClose는 그냥 닫는 `() => setIsOpen(false)`로 전달해주면 되니
`onClick={onClose}`로 해줘야 합니다.

2024-02-15 05:07 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.styles.js
> +	left: 48px;
이건 컴포넌트마다 다르니 지워주는 게 좋겠습니다. 상위에서 한 번 묶어서 진행하는 게 좋아보여요

2024-02-15 05:15 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.styles.js
> +	z-index: 1;
z-index: 2로 해야 할 것 같습니다. 달력이 z-index: 1로 구성되어 있어서요

2024-02-15 05:30 UTC, kimyoungyin commented on src/components/Common/GroupInviteLink/GroupInviteLink.jsx
> +					disabled={isLoading || inviteLink === null}
`isLoading || inviteLink === ""`

2024-02-15 10:52 UTC, sikkzz commented on src/components/Common/Feed/Feed.jsx
> +	groupId,
전에도 말씀 드렸는데 그룹별 피드 조회에는 groupId가 담겨있지 않습니다. 백엔드에서 수정해야 삭제 가능합니다

2024-02-15 10:56 UTC, sikkzz commented on src/components/Group/GroupManagement/GroupMemberManagement/AccessLevelInfo.styles.js
> +	left: -36px;
디자인상으로는 중앙이 맞는데 디자인 변경 요청할까요?

2024-02-15 11:05 UTC, sikkzz commented on src/pages/SettingPage/SettingPage.jsx
> +			{openedModal === "EXIT_GROUP" && <GroupExitModal />}
setting page 쪽 modal은 우선은 다 냅둘게요 아마 다른 브랜치에서 리팩토링 한번 싹 봐야해서 그때 적용시킬게요. 준수님이 작성한 부분이기도 해서 제꺼 모달로 아마 흡수시켜야할거에요

2024-02-15 16:00 UTC, sikkzz commented on src/features/group/group-slice.js
reject, pending시 실행되는 부분은 동일한데 addCase로 작성시 pending, reject도 addCase로 작성해야 해서 코드가 오히려 늘어나지 않나요? 그래서 리뷰주신대로 addMatcher로 간소화 시킨거로 기억합니다

2024-02-16 01:45 UTC, kimyoungyin commented on src/features/group/group-service.js
> +);
저도 그렇게 생각해요.. 일단 api쪽은 건드리지 않았는데 일단 보류하고 다음에 또 브랜치 팔 때 얘기 한 번 해주세요!

2024-02-16 01:57 UTC, kimyoungyin commented on src/components/Common/Feed/Feed.jsx
> +	groupId,
그룹피드 조회(예를 들어`getGroupAllPost`)애초에 조회할 때 `groupId`를 param으로 받기 때문에 `response`에서 주지 않는 것 같습니다. groupId를 지우고 진행할 수 있는 해결 방법은 두 가지인데, 
- 이 `thunk`나 `fulfilled` action에서 `groupId` params를 `response`로 담아서 `setState`하면 됩니다.
- `GroupFeed.jsx` 말씀하시는 거면 거기서 다음과 같이 변경해보시면 됩니다.
```js
const GroupFeed = forwardRef(({ allGroupPosts, groupId, leaderName }, ref) => {
	const [optionMenuOpenedFeedIndex, setOptionMenuOpenedFeedIndex] =
		useState(null);

	return (
		<FeedSection>
			{allGroupPosts &&
				allGroupPosts.map((post) => (
					<Feed
                                                 // 이렇게 변경하면 됩니다.
						post={{ ...post, groupId }}
						key={post.postId}
						// groupId={groupId}
						optionOpenedFeedIndex={optionMenuOpenedFeedIndex}
						onThreeDotClick={() =>
							setOptionMenuOpenedFeedIndex((prev) =>
								prev === post.postId ? null : post.postId,
							)
						}
						leaderName={leaderName}
					/>
				))}
			<div ref={ref} />
		</FeedSection>
	);
});
```

2024-02-16 02:05 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +								</OptionMenuDiv>
`useOutsideClick` 적용 필요 + `button` tag로 변경 필요

2024-02-16 02:09 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/AccessLevelInfo.styles.js
> +	left: -36px;
넵 그게 좋아보이네요

2024-02-16 02:15 UTC, kimyoungyin commented on src/pages/CommunityPage/CommunityPage.jsx
> +	}, []);
이게 아니라 searchParams이 없거나, feed 혹은 search가 아닐 때 초기화 시켜줘야 됩니다... 이렇게 하면 search일 때 새로 고침하거나 나갔다 오면 다 group이 되버려요 ㅠㅠ

2024-02-16 02:16 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +	const [searchParams, setSearchParams] = useSearchParams();
community 페이지와 마찬가지로 잘못 처리했습니다. 다시 부탁드려요

2024-02-16 02:17 UTC, kimyoungyin commented on src/pages/MyPage/MyPage.jsx
> +	}, []);
있을 때가 아니라, 없거나 group 혹은 request가 아닐 때입니다...

2024-02-16 06:59 UTC, kimyoungyin commented on src/pages/SettingPage/SettingPage.jsx
> +			{openedModal === "EXIT_GROUP" && <GroupExitModal />}
관련해서 회의 때 얘기해봐요

2024-02-21 08:06 UTC, kimyoungyin commented on src/features/group/group-slice.js
`group`은 안쓰이지 않나요?

2024-02-22 08:07 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
에러 해결했으니 회의 끝나고 알려드릴게요

2024-02-29 06:35 UTC, kimyoungyin requested changes

2024-02-29 06:35 UTC, kimyoungyin commented on src/components/Common/Feed/Feed.jsx
여기도 useOutsideClick 적용해야겠네요.. useOutsideClick 적용된 모달(드롭다운) wrapper 컴포넌트를 따로 파는 것도 고민해보죠

2024-02-29 06:35 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
> +	};
`useEffect` 안에서만 쓰이면 굳이 밖으로 뺼 이유가 없습니다.

2024-02-29 06:35 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfo.jsx
> +				/>
ref, useOutsideClick는 GroupOption 내부에서 선언해야 할 것 같습니다. 작동 안하기도 하구요

2024-02-29 06:35 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +	const [searchParams] = useSearchParams();
에러 있습니다. 일단 searchParams는 부모 컴포넌트에서 쓰고 있으니 그걸 받아서 적용해주시고
- 커뮤니티 페이지해서 탭을 '그룹 검색'으로 갔다가 마이페이지에서 확인해보면 내그룹(혹은 신청 중인 그룹)이 그룹 검색 컴포넌트로 뜹니다. 관련 에러 수정 부탁드립니다

2024-02-29 06:35 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupOption.jsx
여기서 useOutsideClick 쓰시면 됩니다

2024-02-29 06:35 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +				))}
이 중 하나만 나오게 되어있지 않나요? 명확한 필터링이 필요해보입니다. 위 에러 코멘트 처럼요

2024-02-29 06:35 UTC, kimyoungyin commented on src/components/Group/GroupManagement/GroupMemberManagement/GroupMemberManagement.jsx
> +];
프로퍼티가 하나밖에 없는데 객체 형태로 할 필요 없지 않을까요? 그냥 string array로 처리하면 될 것 같습니다.

2024-02-29 06:35 UTC, kimyoungyin commented on src/components/Group/GroupMember/GroupMember.jsx
> +	};
이것도 useEffect 내부에서만 쓰이는 거니 굳이 밖으로 안 빼는 게 좋습니다

2024-02-29 06:35 UTC, kimyoungyin commented on src/pages/GroupPage/GroupPage.jsx
> +	const isGroupMember = groupInfo?.accessLevel !== null;
optional 제거 후 line 80 밑으로 내리는 게 낫지 않을까요? side effect가 불안합니다

2024-03-01 09:47 UTC, sikkzz commented on src/components/Group/GroupInfoList/GroupInfo.jsx
> +				/>
안옮겨도 작동 정상이지 않나요?
옮기면 아래 Link onClick 부분이 작동 안해서 문제기도 합니다만, 현재 문제 없이 작동하는거 같아서요

2024-03-21 08:02 UTC, kimyoungyin approved these changes

2024-03-21 08:02 UTC, kimyoungyin commented on src/constants/emptyConstants.jsx
> +];
이건 `EmptyLayout`에서만 쓰이는 값이니 굳이 여기서 선언하고 Imort할 필요 없이 `EmptyLayout.jsx`에서 선언하는게 좋아보여요

2024-03-21 08:02 UTC, kimyoungyin commented on src/constants/emptyConstants.jsx
> +];
이렇게 배열형태로 두면 조회 시 map으로 쓸데 없는 순회를 통해 원하는 데이터를 찾아야합니다. `EMPTY_TYPE`을 키값으로 가지는 객체 형태로 변경하면 조회 시 용이합니다.
```js
export const EMPTY_DATA = {
	[EMPTY_TYPE.SEARCH_RESULT]: {
		icon: <EmptySearchResultIcon />,
		text: "검색 결과가 없습니다.",
		subText: "입력하신 검색어를 확인해주세요",
	},
	[EMPTY_TYPE.GROUP_FEED]: {
		icon: <EmptyFeedIcon />,
		text: "게시된 글이 없어요",
		subText: "첫 게시글의 주인공이 되어보세요!",
	},
	[EMPTY_TYPE.MY_GROUP_FEED]: {
		icon: <EmptyFeedIcon />,
		text: "그룹에서 등록된 피드가 없습니다.",
		subText: "피드를 등록해보세요",
	},
	[EMPTY_TYPE.MY_GROUP]: {
		icon: <EmptyGroupListIcon />,
		text: "가입된 그룹이 없습니다.",
		subText: "그룹을 만들거나 신청해 보세요.",
	},
	[EMPTY_TYPE.REQUEST_GROUP]: {
		icon: <EmptyGroupListIcon />,
		text: "요청 중인 그룹이 없습니다.",
		subText: "그룹 신청하기를 통해 그룹에 가입해 보세요.",
	},
};
```

2024-03-21 08:02 UTC, kimyoungyin commented on src/constants/emptyConstants.jsx
> +];
```suggestion
```

2024-03-21 08:02 UTC, kimyoungyin commented on src/constants/emptyConstants.jsx
> +} from "@/constants/iconConstants";
```suggestion
```

2024-03-21 08:02 UTC, kimyoungyin commented on src/components/Common/EmptyLayout/EmptyLayout.jsx
> +			))}
```suggestion
import React from "react";
import { useDispatch } from "react-redux";
import { useNavigate } from "react-router-dom";

import { EMPTY_TYPE } from "@/constants/emptyConstants";
import {
	EmptyFeedIcon,
	EmptyGroupListIcon,
	EmptySearchResultIcon,
} from "@/constants/iconConstants";
import { openCreateGroupModal } from "@/features/ui/ui-slice";

import { LayoutDiv, ButtonDiv } from "./EmptyLayout.style";

const EMPTY_DATA = {
	[EMPTY_TYPE.SEARCH_RESULT]: {
		icon: <EmptySearchResultIcon />,
		text: "검색 결과가 없습니다.",
		subText: "입력하신 검색어를 확인해주세요",
	},
	[EMPTY_TYPE.GROUP_FEED]: {
		icon: <EmptyFeedIcon />,
		text: "게시된 글이 없어요",
		subText: "첫 게시글의 주인공이 되어보세요!",
	},
	[EMPTY_TYPE.MY_GROUP_FEED]: {
		icon: <EmptyFeedIcon />,
		text: "그룹에서 등록된 피드가 없습니다.",
		subText: "피드를 등록해보세요",
	},
	[EMPTY_TYPE.MY_GROUP]: {
		icon: <EmptyGroupListIcon />,
		text: "가입된 그룹이 없습니다.",
		subText: "그룹을 만들거나 신청해 보세요.",
	},
	[EMPTY_TYPE.REQUEST_GROUP]: {
		icon: <EmptyGroupListIcon />,
		text: "요청 중인 그룹이 없습니다.",
		subText: "그룹 신청하기를 통해 그룹에 가입해 보세요.",
	},
};

const EmptyLayout = ({ emptyType }) => {
	const dispatch = useDispatch();

	const navigate = useNavigate();

	const contentData = EMPTY_DATA[emptyType];

	return (
		<LayoutDiv
			hasMargin={
				emptyType === EMPTY_TYPE.MY_GROUP ||
				emptyType === EMPTY_TYPE.REQUEST_GROUP
			}
		>
			<>
				<div>{contentData.icon}</div>
				<h3>{contentData.text}</h3>
				<h4>{contentData.subText}</h4>
			</>
```

2024-03-21 08:02 UTC, kimyoungyin commented on src/components/Common/EmptyLayout/EmptyLayout.jsx
> +			{openedModal === UI_TYPE.CREATE_GROUP && <GroupCreateModal />}
```suggestion
```
헤더에도 이 코드가 있네요. 필요 없어보입니다. 전역으로 관리하니까요

2024-03-21 08:02 UTC, kimyoungyin commented on src/components/Common/Feed/FeedOption.jsx
> +	useOutsideClick(optionMenuRef, () => setOptionMenuOpenedFeedIndex(null));
이건 왜 이런 식으로 되어 있을까요? 

코드를 살펴보니 최상단에서 `FeedOption`을 하나 두고 다루는 게 아니라, `Feed`마다 각각 `FeedOption`이 자식 컴포넌트로 포함되어있는데, 

그냥 `Feed`에서 `isOptionOpen` boolean state로 토글 가능하게 하고, `useOutsideClick`의 경우에도 `Feed`에서 선언 후 Trigger function에서 `() => setIsOptionOpen(false)`로 해주고  `FeedOption`에 ref를 걸어주면 되지 않을까요?

2024-03-21 08:02 UTC, kimyoungyin commented on src/components/Group/GroupFeed/GroupFeed.jsx
>  		groupPostFetching();
제가 최근에 효율적인 코드 작성 면에서 발견한 방식이 있는데, 즉시 실행 함수를 사용하는 겁니다! 어치파 이러한 `useEffect` 내부 함수 선언은 비동기 로직을 위해 감싸주는 건데, 사용도 line 27에서 한 번 하기 때문에 다음과 같이 하면 좋습니다.

```suggestion
		(async () => {
			await dispatch(getGroupAllPosts(groupId));
			setIsLoading(false);
		})();
```

제가 작성했던 쪽에 있는 `useEffect` 코드에도 발견될 때마다 수정할 예정입니다.

2024-03-21 08:02 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +	// eslint-disable-next-line consistent-return
이 옵션 해제하고 모든 렌더링 조건문과 일치하지 않을 때에 대한 에러 처리 혹은 Redirect 처리를 해주는게 좋아보입니다. 의도치 않은 에러가 발생할 수 있습니다.

2024-03-21 08:02 UTC, kimyoungyin commented on src/components/Group/GroupMember/GroupMember.jsx
>  		groupMemberListFetching();
```suggestion
		(async () => {
			await dispatch(getGroupRequestMemberList(groupId));
			await dispatch(getGroupMemberList(groupId));
			setIsLoading(false);
		})();
```

2024-03-21 08:02 UTC, kimyoungyin commented on src/components/Group/MyGroupFeed/MyGroupFeed.jsx
>  		myGroupPostFetching();
```suggestion
		(async () => {
			await dispatch(getMyGroupPosts(myGroupPostslastRecordId));
			setIsLoading(false);
		})();
```

2024-03-21 08:02 UTC, kimyoungyin commented on src/components/Group/MyGroup/MyGroup.jsx
> +			{openedModal === UI_TYPE.CREATE_GROUP && <GroupCreateModal />}
```suggestion
```
`Header`와 연결된 `GroupCreateModal`은 어디로 접근하던 항상 대기중입니다.

2024-03-21 08:31 UTC, sikkzz commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +	// eslint-disable-next-line consistent-return
최상위 페이지에서 처리되는거라 리다이렉트 시킬 곳은 없고 조건문 이외의 조건은 페이지마다 searchParams 조건으로 걸러주기 때문에 접근될 수 없습니다. 그렇다고 empty 레이아웃 적용시키기는 애매할 거 같아서 그룹이 없습니다의 텍스트만 띄워줬습니다. 다만 이 문구를 유저가 확인할 수 있는 방법은 안생긴다고 확실하게 볼 수 있습니다.

2024-03-22 02:09 UTC, kimyoungyin commented on src/components/Group/GroupInfoList/GroupInfoList.jsx
> +	// eslint-disable-next-line consistent-return
일단 알겠습니다!

2024-03-22 02:13 UTC, kimyoungyin approved these changes

2024-03-22 08:25 UTC, kimyoungyin approved these changes

2024-03-22 08:26 UTC, merged