issue #162 refactor: BaseModal refactoring
Selody-project/Frontend pull request #163
Opened 2023-12-02 18:38 UTC by sikkzz

# 설명

- [https://github.com/Selody-project/Frontend/issues/162](https://github.com/Selody-project/Frontend/issues/162)

서비스 대표 modal들은 다음과 같습니다. 현재는 close 버튼이 없는 모달은 없고 bgColor 또한 모두 white로 확인됩니다. 또한 padding은 20px로 동일합니다.

<img width="1027" alt="스크린샷 2023-12-03 오전 3 12 47" src="https://github.com/Selody-project/Frontend/assets/100590110/8e34591c-2c9b-4933-b4da-1f0547cfa619">

padding 20px, background white, close button만 default로 유지시키고 나머지 내부 요소는 상황에 맞게 재사용성 고려해서 스타일링 하는게 낫다고 판단했습니다.

해당 방식에 맞춰서 리팩토링 진행했고 컨벤션에 맞게 스타일 컴포넌트들 이름 수정했고 미사용 코드 삭제했습니다.

2023-12-05 13:45 UTC, sikkzz commented
isBackdropClose boolean prop만 추가해서 간단하게 리팩토링 해봤는데 의견 부탁드려요

2023-12-07 00:54 UTC, kimyoungyin requested changes

2023-12-07 00:54 UTC, kimyoungyin commented on src/components/Base/BaseModal/BaseModal.style.js
> +	right: 20px;
button 가로 세로 길이가 달라서 통일 한 번만 시켜주실래요?

2023-12-07 00:54 UTC, kimyoungyin commented on src/components/Base/BaseModal/BaseModal.jsx
> +			onClick={() => isBackdropClose && dispatch(closeModal())}
아예 `Backdrop` 쪽 뿐만 아니라, X 버튼을 클릭했을 때도 주의 모달 하나 띄워주는 게 어때요?
form의 경우는 어떤 쪽으로든 나가려는 시도를 했을 때 경고해주는 게 맞는 것 같아서요

경고(주의) 모달 디자인은 지수님께 요청드리고 반영해보는게 어떤가요?

2023-12-07 06:19 UTC, sikkzz commented on src/components/Base/BaseModal/BaseModal.jsx
> +			onClick={() => isBackdropClose && dispatch(closeModal())}
이해가 잘 안가서 form의 경우 backdrop 클릭이나 x 버튼 클릭시 경고 모달 하나 띄워주자는게 맞을까요? 
아니면 전체 모달에 적용시키자는 말씀이실까요?

2023-12-07 08:32 UTC, kimyoungyin commented on src/components/Base/BaseModal/BaseModal.jsx
> +			onClick={() => isBackdropClose && dispatch(closeModal())}
form의 경우입니다!
Backdrop 클릭 시와  X 버튼 클릭 시에 둘 다 동일한 경고 모달 하나 띄워주자는 뜻입니다

2023-12-07 08:44 UTC, sikkzz commented on src/components/Base/BaseModal/BaseModal.jsx
> +			onClick={() => isBackdropClose && dispatch(closeModal())}
네 확인했습니다. 요청드려놓을게요!

2024-01-02 13:38 UTC, sikkzz commented
form modal 말고 기본 모달 최종입니다. rebase까지 완료해서 한번 확인 부탁드려요

2024-01-09 04:34 UTC, kimyoungyin reviewed
Base가 약간 의미가 퇴색된 것 같기도 하네요? 한 번 이에 대해서 정해보죠

2024-01-09 04:34 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
혹시 BaseModal도 Common으로 옮겼던데, 그럼 Base와 Common의 차이가 뭐라고 봐야 할까요?
- Common: 여러 곳에서 사용되는 컴포넌트
- Base: ?(UI?)

2024-01-09 05:15 UTC, sikkzz commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
저는 원래 Commom으로 공통 컴포넌트 빼서 사용했어서 옮겼고 Base는 과거 분들이 만들어 놓은거라 저는 불필요하다 생각합니다

2024-01-09 05:16 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
Base를 UI로 바꿔서 내부 상태를 가지지 않는 컴포넌트(Card)를 넣어두는 게 어떠세요?

2024-01-09 05:20 UTC, sikkzz commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
네 좋은거 같아요

2024-01-09 05:21 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
그럼 그 부분 디렉토리명만 여기서 변경해주실래요? Rebase해서 작업 브랜치에 반영할게요

2024-01-09 05:24 UTC, sikkzz commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
디렉토리 이름만 바꾸고 내부 파일은 변경 안했습니다. BaseAxios도 후에 어디로 빼던가 해야겠네요

2024-01-09 05:25 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
i도 대문자로 해주실래요? 약어라서요

2024-01-09 05:27 UTC, sikkzz commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
반영했어요

2024-01-09 05:27 UTC, kimyoungyin approved these changes

2024-01-09 05:29 UTC, merged