169 front task refactor tab component
Selody-project/Frontend pull request #174
Opened 2023-12-19 08:20 UTC by sikkzz

# 설명

- [https://github.com/Selody-project/Frontend/issues/169(https://github.com/Selody-project/Frontend/issues/169)

공통화를 시켜보려했는데 현재 작업에서는 Header와 subHeader는 통일화가 가능했습니다.
SettingPage쪽 탭은 조금 구성이 달라서 여기다가 138번 머지 이후 커뮤니티 부분 탭까지는 통일화가 가능은 할 거 같아요.

다만 해당 리팩토링 방식이 괜찮을지는 의문이네요 한번 확인해보시고 의견 주세요

추가적으로 Pathname 비교때문에 라우트 url을 좀 변경했어요 안ㅁ이

2023-12-22 14:56 UTC, kimyoungyin requested changes

2023-12-22 14:56 UTC, kimyoungyin commented on src/components/Base/Tab/Tab.jsx
> +		<TabUl role="tablist" className={name}>
`name`이 의미하는 게 단순히 header인지, subheader인지라면,
 `isSubHeader`로 불린값으로 대체한 뒤 `Tab` 컴포넌트 내부에서 className 처리하는 게 이해하기 직관적이고 편한 방식일 것 같아요

2023-12-22 14:56 UTC, kimyoungyin commented on src/components/Base/Tab/Tab.jsx
> +					{name === "header" && <SubHeader data={tabData.subHeader} />}
`SubHeader`를 따로 컴포넌트로 분리할 필요 없이, `TabUl을 한 번 더 렌더링하는 건 어떠세요?

```jsx
<SubHeaderDiv>
  <Tab data={data} isSubHeader={true} />
</SubHeaderDiv>
```

2023-12-27 05:05 UTC, sikkzz commented on src/components/Base/Tab/Tab.jsx
> +		<TabUl role="tablist" className={name}>
추후 다른 컴포넌트도 적용시 아마 더 추가될 수도 있어서 isSubHeader로 사용하면 안될 거 같아요.

2023-12-27 05:11 UTC, sikkzz commented on src/components/Base/Tab/Tab.jsx
> +					{name === "header" && <SubHeader data={tabData.subHeader} />}
다른 컴포넌트에서도 이 tab 컴포넌트를 사용한다면 그 컴포넌트들 사용하는 사람 입장에서는 SubHeader의 코드가 안중요하지 않을까요? 이 Tab 컴포넌트 안에 코드를 더 복잡하게 작성할 이유가 없을 거 같아서요

2023-12-27 08:49 UTC, kimyoungyin commented on src/components/Base/Tab/Tab.jsx
> +					{name === "header" && <SubHeader data={tabData.subHeader} />}
아하 그럴 수 있겠네요. 그대로 가도 좋을 것 같습니다

2023-12-27 08:51 UTC, kimyoungyin commented on src/components/Base/Tab/Tab.jsx
> +		<TabUl role="tablist" className={name}>
탭의 종류가 navbar 내에 헤더에 있는 탭이 아니라면, 서브헤더가 있는 다른 탭은 없을 것 같은데 예를 들면 어떤 게 있을까요?

2023-12-27 08:54 UTC, kimyoungyin commented on src/components/Base/Tab/Tab.jsx
> +const Tab = ({ data, name }) => {
보다보니, 너무 추상적인 `data`가 아니라 배열의 의미를 담아 복수형으로 하면서, `contents`와 같이 prop 명을 변경하는 게 좋을 것 같은데 어떠세요?

복수형은 꼭 반영해야 할 것 같고, prop명은 괜찮은 게 딱히 없으면 그대로 가도 좋습니다.

2023-12-27 09:18 UTC, sikkzz commented on src/components/Base/Tab/Tab.jsx
> +		<TabUl role="tablist" className={name}>
서브헤더가 있는 탭은 없지만 현재 name의 역할은 해당 tab의 name이라 명칭을 tabName으로 수정해야할 거 같기도 하네요

다른 페이지에서 활용가능한 탭들도 적용시킬 예정이라서요 해당 [이슈](https://github.com/Selody-project/Frontend/issues/169) 가보면 내용이 있습니다.

2023-12-27 09:19 UTC, sikkzz commented on src/components/Base/Tab/Tab.jsx
> +const Tab = ({ data, name }) => {
복수형 제외하면 동일할거 같아서 contents로 변경할게요

2023-12-27 09:26 UTC, sikkzz commented on src/components/Base/Tab/Tab.jsx
> +const Tab = ({ data, name }) => {
수정하는 김에 지금 컴포넌트 폴더가 Base인데 제가 잘못 넣어놨네요. Common으로 옮길게요

2023-12-28 06:54 UTC, kimyoungyin commented on src/components/Base/Tab/Tab.jsx
> +		<TabUl role="tablist" className={name}>
이슈에 작성된 탭(?)들은 디자인이 다 제각각인데 굳이 묶을 필요가 있을까 싶네요. 이 브랜치를 판 것이 그 목적이었다면 차라리 common component를 만드는 게 아니라, hook으로 탭 관련 로직을 정리하는게 더 나아보이는데요?

전 디자인이 동일한 탭들만 묶는다고 생각했었습니다

2023-12-28 06:59 UTC, kimyoungyin requested changes

2023-12-28 06:59 UTC, kimyoungyin commented on src/constants/tabConstants.js
> +export const HEADER_TAB_TYPE = [
TAB_TYPE보단 TAB_CONTENTS와 같이 변경하는 게 낫지 않을까요?
TYPE은 탭의 종류를 구분하는 식별자로 쓰여야 할 것 같아요

2023-12-28 13:16 UTC, sikkzz commented on src/components/Base/Tab/Tab.jsx
> +		<TabUl role="tablist" className={name}>
그게 낫다고 생각하시면 여기는 위에 리뷰주신대로 수정하고 더이상 수정 없이 진행할게요

2023-12-30 14:08 UTC, kimyoungyin requested changes

2023-12-30 14:08 UTC, kimyoungyin commented on src/components/Common/Tab/Tab.jsx
> +			{contents.map(({ ...tabContents }) => (
여기 rest 연산자를 사용할 필요가 없지 않을까요?
`(tabContent) => ()`

2024-01-08 06:30 UTC, kimyoungyin approved these changes

2024-01-08 09:44 UTC, merged