129 front task 개인 일정 페이지 달력 디자인, 및 schedule state 관련 컴포넌트 정리
Selody-project/Frontend pull request #175
Opened 2023-12-28 07:18 UTC by kimyoungyin

# 설명

- #129
- 머지 후 진행할 예정인 구현 사항: 모달 UI 통일 후 진행 예정
  - 일정 삭제 클릭 시 경고 모달
  - `ScheduleModal`의 깨진 디자인 수정

# 테스트
일단 기능은 구현되었으니 전부 작성하진 않았어요
- **비동기 로직을 제외한** 렌더링에 대해서만 작성해두었습니다

# Demo
## 월별 뷰
<img width="722" alt="스크린샷 2023-12-28 오후 4 14 51" src="https://github.com/Selody-project/Frontend/assets/78777345/cd4903d2-5dea-4805-9b27-3b87ed8e032b">

## 리스트 뷰
<img width="1436" alt="스크린샷 2023-12-28 오후 4 15 31" src="https://github.com/Selody-project/Frontend/assets/78777345/fd27dfb0-594d-4109-826a-716392279cac">

## 겹친 일정
<img width="1436" alt="스크린샷 2023-12-28 오후 4 15 52" src="https://github.com/Selody-project/Frontend/assets/78777345/eec4e7de-e206-463f-b107-f0676f6344af">

## 일청 추가/수정/뷰 모달
<img width="1436" alt="스크린샷 2023-12-28 오후 4 16 14" src="https://github.com/Selody-project/Frontend/assets/78777345/02085e9d-5d86-4774-9a94-a594907c2288">

2024-01-08 08:59 UTC, sikkzz requested changes

2024-01-08 08:59 UTC, sikkzz commented on src/styles/GlobalStyles.js
body에 max-width 제거 부탁드려요 #root 코드에 max-width가 있어서 왼쪽으로 치우쳐있네요

2024-01-08 08:59 UTC, sikkzz commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +const getDayHeaderContentInTimeGridWeek = (props) => {
props 변수명 변경하는게 좋지 않을까요?

2024-01-08 08:59 UTC, sikkzz commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +			if (currentCalendarView === VIEW_TYPE.DAY_GRID_MONTH) return;
중괄호 코드 컨벤션 맞추기로 했었던거 같아요

2024-01-08 08:59 UTC, sikkzz commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +					height={currentCalendarView === VIEW_TYPE.DAY_GRID_MONTH ? 654 : 964}
height값이 네이밍이 가능한 값이라면 상수 처리하는거도 좋을 거 같아요. 어떤 기준에서 값이 정해지는지 잘 모르겠어서요. 특별한 기준을 매기기 어렵다면 유지하셔도 좋습니다

2024-01-08 08:59 UTC, sikkzz commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.styles.js
> +		/* min-width: ${({ isMonthly }) => (isMonthly ? 812 : 812 + 73)}px; */
필요 없는 주석이라면 지워도 될 거 같아요

2024-01-08 08:59 UTC, sikkzz commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.styles.js
저는 코드 작성할 때 css 선택자 사이는 한줄씩 띄어서 작성합니다. 구분되는걸 명확히 알 수 있어서요. 각자의 코딩 스타일이고 해당 컨벤션은 맞추지 않았지만 띄어주는게 어떠신가요?

2024-01-08 08:59 UTC, sikkzz commented on src/components/Common/ScheduleModal/Picker.styles.js
TimePickerWrapperDiv 보시면 대문자 하나 오타 있습니다

2024-01-08 08:59 UTC, sikkzz commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
> +		if (isCreateMode) return "일정 추가";
여기도 중괄호 추가해줘야 할 거 같아요. 추가적으로 위에 69~71 라인쪽 보시면 변수와 if문 사이 같은 곳도 한줄씩 띄어주는게 코드 확인하기 훨씬 좋지 않을까 싶어요! 앞서 style 선택자 관련 리뷰랑 비슷하게요!

2024-01-08 08:59 UTC, sikkzz commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
setFormValues들을 util로 빼서 뭔가 간소화 시키는건 어렵겠죠? 공통 부분이 보이긴하는데 기능들이 다 다르게 작동하긴 해서 간소화 시키면 좋을 거 같긴한데 어려워 보이긴 하네요

2024-01-08 08:59 UTC, sikkzz commented on src/components/ScheduleItemList/ScheduleItem/ScheduleItem.jsx
> +					bgColor={isGroup ? colors.sunday : colors.disabled_text}
style파일에서 조건부 스타일링 하는게 낫지 않을까요? 그럼 useTheme도 사용 안해도 될 거 같구요

2024-01-08 08:59 UTC, sikkzz commented on src/pages/PersonalSchedulePage/PersonalSchedulePage.styles.js
> +	padding-left: ${({ isMonthly }) => (!isMonthly ? "22px" : undefined)};
undefined일 이유가 있을까요? 95px 적용이면 95px이나 0으로 작성하면 되지 않을까요?

2024-01-08 09:01 UTC, sikkzz commented
우선 test코드는 제외하고 리뷰했습니다. test코드는 제가 아직 잘 몰라서 후에 학습하고 나눌 내용 있으면 말씀드릴게요

추가적으로 개인의 코딩 스타일이고 컨벤션을 맞추지는 않았지만 deps가 깊은 코드들이 많은데 코드들이 다 붙어 있어서 읽기 어려운 점이 조금 있는 거 같아요ㅠ 공백도 컨벤션이라는 얘기도 있어서 코드 간 줄바꿈을 활용해주시면 읽기 더 편할 거 같아요! 코드의 길이가 길어지긴 하겠지만 로직별로 한눈에 파악하기 좀 더 용이할 거 같아서 의견 드립니다!

2024-01-08 09:10 UTC, sikkzz commented
반복 일정 작성시 오류가 있는 거 같아요. 1월부터 3월까지 매주 월, 수 일정을 작성하니까 이후의 날짜에도 앞에 일정들이 다 겹쳐서 블럭 색깔이 정상적이지 않은 거 같아요 
<img width="605" alt="스크린샷 2024-01-08 오후 6 09 37" src="https://github.com/Selody-project/Frontend/assets/100590110/5cb8658a-3f7c-4213-a742-b860ee2fc886">
<img width="1402" alt="스크린샷 2024-01-08 오후 6 09 41" src="https://github.com/Selody-project/Frontend/assets/100590110/6b768fd6-80bf-4160-8171-904c877c3b66">
<img width="1430" alt="스크린샷 2024-01-08 오후 6 09 49" src="https://github.com/Selody-project/Frontend/assets/100590110/0a427b62-baaf-44d4-9fce-ec60fae0c949">

2024-01-09 00:02 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +			if (currentCalendarView === VIEW_TYPE.DAY_GRID_MONTH) return;
바로 return하는 경우에는 필요 없이 그냥 작성해도 된다고 하지 않았나요? 아무 것도 안하는 로직을 먼저 제외하는 코드라..
[링크](https://www.notion.so/2ced219f10db4d99850ff24d9bdfe393?pvs=4#3000f4cde508400a91a88ae37d20f70f)

2024-01-09 00:05 UTC, kimyoungyin commented on src/pages/PersonalSchedulePage/PersonalSchedulePage.styles.js
> +	padding-left: ${({ isMonthly }) => (!isMonthly ? "22px" : undefined)};
위에 작성했던 것을 그대로 유지하기 위해서 입니다. undefined 처리를 하면 해당 css 속성을 작성하지 않은 것으로 처리되서 위쪽에서 작성했던 코드가 반영이 되거든요!

2024-01-09 00:11 UTC, kimyoungyin commented
> 반복 일정 작성시 오류가 있는 거 같아요. 1월부터 3월까지 매주 월, 수 일정을 작성하니까 이후의 날짜에도 앞에 일정들이 다 겹쳐서 블럭 색깔이 정상적이지 않은 거 같아요 <img alt="스크린샷 2024-01-08 오후 6 09 37" width="605" src="https://private-user-images.githubusercontent.com/100590110/294853464-5cb8658a-3f7c-4213-a742-b860ee2fc886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NTg4OTEsIm5iZiI6MTcwNDc1ODU5MSwicGF0aCI6Ii8xMDA1OTAxMTAvMjk0ODUzNDY0LTVjYjg2NThhLTNmN2MtNDIxMy1hNzQyLWI4NjBlZTJmYzg4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwMDAzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2FlYTg5NDAxZTEzMGYyMzE3OTI1MjEyZWIwZDkyZjA0ZGE1NTQ4OWM0ZWNiMDdkZjI5NTUxYmVjMTIwOTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D50meoj3gUpKszzAz_eBAwhlWeOlvzx9n4EMZq6x1a8"> <img alt="스크린샷 2024-01-08 오후 6 09 41" width="1402" src="https://private-user-images.githubusercontent.com/100590110/294853470-6b768fd6-80bf-4160-8171-904c877c3b66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NTg4OTEsIm5iZiI6MTcwNDc1ODU5MSwicGF0aCI6Ii8xMDA1OTAxMTAvMjk0ODUzNDcwLTZiNzY4ZmQ2LTgwYmYtNDE2MC04MTcxLTkwNGM4NzdjM2I2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwMDAzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmJmYzEyNTE0ZjcwZjY2OGQ1NDBkZjM0ZGEyNzU5NTIxMDRmNTU0ODJkMTU2Nzk0YTUwNmMwYWQwMTQ0OWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bHBSGwC4mO789r8pvy93hW772naeGGKAIQjJESSAVb8"> <img alt="스크린샷 2024-01-08 오후 6 09 49" width="1430" src="https://private-user-images.githubusercontent.com/100590110/294853475-0a427b62-baaf-44d4-9fce-ec60fae0c949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NTg4OTEsIm5iZiI6MTcwNDc1ODU5MSwicGF0aCI6Ii8xMDA1OTAxMTAvMjk0ODUzNDc1LTBhNDI3YjYyLWJhYWYtNDRkNC05ZmNlLWVjNjBmYWUwYzk0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwMDAzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmZiZGNhZGIyY2JlN2QzNWUxNWRmMGVjYmMxN2ViMTI4YjdhOWM5MzcwMjU2N2JkNTAwMjkzNjFjZjJhM2Q4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mw1YRwS8GNgxXtcKKvWJ9958q37Fl5jgH0A5K6q61m8">

이건 준식님이 일정을 잘못 등록해서 그런 것 같습니다. 일정의 각 요소에 대해 한 번 더 확인해보세요!
준식님이 올린 일정은 하나에 두 달 치 간격이에요.
1월 3일 -> 3월 13일
1월 5일 -> 3월 15일
1월 10일 -> 3월 23일
... 
이런 식으로 하면 4월 종료로 잡았으니 한 6월까지는 계속 겹칩니다. 겹침의 정도는 다르지만요

2024-01-09 00:14 UTC, kimyoungyin commented on src/components/ScheduleItemList/ScheduleItem/ScheduleItem.jsx
> +					bgColor={isGroup ? colors.sunday : colors.disabled_text}
나중에 속해있는 그룹마다 유니크한 색을 주어야 함을 감안했습니다. 
현재는 개인 일정 내부만 고려하여 그룹 일정을 모두 빨간색(`sunday`)으로 처리했는데, 그룹일정에서도 이를 사용할 거라 그 때는 그룹마다 다른 색들을 지정해주어야 해요!

2024-01-09 00:16 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
맞아요.. 저도 고려해본 사항이긴 한데
워낙 상황상황마다 변하는 state들이 제각각이라, 그대로 인라인으로 살려두는게 더 가독성이 좋을 거라 판단했습니다 ㅠ

2024-01-09 00:20 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/Picker.styles.js
아 오타를.. 죄송합니다 ㅠ

2024-01-09 00:22 UTC, kimyoungyin commented on src/styles/GlobalStyles.js
반응형으로 바뀔 걸 고려해서 뻈었었네요.. 일단 제거했습니다

2024-01-09 00:23 UTC, kimyoungyin commented on src/components/Common/ScheduleModal/ScheduleModal.jsx
> +		if (isCreateMode) return "일정 추가";
여기도 위와 동일합니다. 공백은 추가했습니다!

2024-01-09 00:26 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +const getDayHeaderContentInTimeGridWeek = (props) => {
그냥 구조 분해 할당 인라인 처리하였습니다!

2024-01-09 00:27 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +					height={currentCalendarView === VIEW_TYPE.DAY_GRID_MONTH ? 654 : 964}
이건 Fullcalendar 높이 커스텀이 정확하지 않아서(쩝..) 디자인과 동일한 지점을 찾은 값들이라고 보시면 될 것 같아요

2024-01-09 00:28 UTC, kimyoungyin commented on src/components/Common/CalendarContainer/CustomCalendar/CustomCalendar.styles.js
아하 좋은 생각이네요 반영하겠습니다

2024-01-09 01:21 UTC, kimyoungyin commented
> 우선 test코드는 제외하고 리뷰했습니다. test코드는 제가 아직 잘 몰라서 후에 학습하고 나눌 내용 있으면 말씀드릴게요
> 
> 추가적으로 개인의 코딩 스타일이고 컨벤션을 맞추지는 않았지만 deps가 깊은 코드들이 많은데 코드들이 다 붙어 있어서 읽기 어려운 점이 조금 있는 거 같아요ㅠ 공백도 컨벤션이라는 얘기도 있어서 코드 간 줄바꿈을 활용해주시면 읽기 더 편할 거 같아요! 코드의 길이가 길어지긴 하겠지만 로직별로 한눈에 파악하기 좀 더 용이할 거 같아서 의견 드립니다!

전반적으로 공백 체크 한 번 씩 했습니다

2024-01-12 08:37 UTC, sikkzz approved these changes

2024-01-15 07:02 UTC, merged