189 front task 공유 일정 페이지 그룹 목록 사용자 초대 버튼 그룹 목록 select
Selody-project/Frontend pull request #190
Opened 2024-01-30 06:30 UTC by kimyoungyin

# 설명
사용자 초대 코드를 생성하는 컴포넌트를 받아와서 사용해야 할 것 같습니다. 일단 해당 부분 제외 기능 구현하였습니다.
## 1) 세부 내용
`GroupMenu`
- `div.GroupMembers`: 그룹에 속한 유저 목록을 받아오고, 그룹장을 첫 번째 인덱스로 설정하여 렌더링합니다. 각 유저는 유니크한 색으로 border 처리가 되어 있습니다.
- `div.inviteButton`: 내가 이 그룹의 owner인 경우에만 렌더링됩니다. 클릭 시 링크 생성 컴포넌트(미완)를 띄워야 합니다
- `GroupSelect`: `userGroupList`를 가져와 option으로 설정합니다. initial value는 첫 번째 인덱스로 설정하였습니다. `ScheduleModal`의 `CustomSelect`를 재사용하려 했다가 번거로울 것 같아 디자인만 조금 수정하여 따로 구현하였습니다.

## 2) 미완성
- 관련 이슈: #189 
- [ ] : 사용자 초대 코드 컴포넌트 재사용(관련 컴포넌트는 여기에 - #159)
- [ ] : 테스트 코드 작성

# 테스트

- 사용자 초대 코드 컴포넌트 재사용 구현 후 작성 및 리팩토링 예정
- `act..` 관련 테스트 코드 에러는 수정 예정

# Demo
- 내 그룹이다: 내가 그룹장이면서, 속한 유저가 일정을 공유하기로 설정함

<img width="841" alt="스크린샷 2024-01-30 오후 3 18 30" src="https://github.com/Selody-project/Frontend/assets/78777345/ec2bd910-66dc-4fb6-8750-a10a9ca03a80">

- 내 그룹2: 내가 그룹장이면서, 속한 유저가 일정을 공유하지 않기로 설정함

<img width="841" alt="스크린샷 2024-01-30 오후 3 18 40" src="https://github.com/Selody-project/Frontend/assets/78777345/0a4c2857-ea4d-4709-9c31-58464fd70852">

- 예시: 내가 그룹장이 아닌 경우

<img width="841" alt="스크린샷 2024-01-30 오후 3 28 19" src="https://github.com/Selody-project/Frontend/assets/78777345/206fd0c6-990e-410e-a2b7-355b3ce3b2e2">

2024-02-05 11:53 UTC, sikkzz requested changes

2024-02-05 11:53 UTC, sikkzz commented on src/components/Common/SchedulePage/CalendarContainer/CustomCalendar/CustomCalendar.jsx
> +import React, { Fragment, forwardRef, useEffect } from "react";
fragment 미사용 인거 같네요

2024-02-05 11:54 UTC, sikkzz commented
<img width="282" alt="스크린샷 2024-02-05 오후 8 53 32" src="https://github.com/Selody-project/Frontend/assets/100590110/9da11ad3-456b-42ce-a95d-b6b2b0dbdfdc">

이 부분 스크롤이 작동이 안되는거 같은데 아직 미구현인건가요? 아니면 오류인건가요 확인 한번만 해주세요

2024-02-05 11:56 UTC, sikkzz commented
> <img alt="스크린샷 2024-02-05 오후 8 53 32" width="282" src="https://private-user-images.githubusercontent.com/100590110/302279375-9da11ad3-456b-42ce-a95d-b6b2b0dbdfdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzQzNTYsIm5iZiI6MTcwNzEzNDA1NiwicGF0aCI6Ii8xMDA1OTAxMTAvMzAyMjc5Mzc1LTlkYTExYWQzLTQ1NmItNDJjZS1hOTVkLWI2YjJiMGRiZGZkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxMTU0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NThkZmE2NTMyZDBmOWQ4NTZjOTFkMTQyODAxZWQ5ODQ3ZWEzZjhmNGYyMWI0OGQwNjk5ZDRhMGMxNTRkN2FlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.akS2jp5gvBRxgR6lrvIUEVHwP5mFntiMefSjWXHy8fI">
> 이 부분 스크롤이 작동이 안되는거 같은데 아직 미구현인건가요? 아니면 오류인건가요 확인 한번만 해주세요

해당 부분 디자인을 위로 빼신 이유가 있을까요? 피그마 상에서는 못찾긴했는데 페이지 위에 요소가 헤더만 있는걸 고려하면 아래쪽으로 내리고 z-index로 올려놓는게 낫지 않나 싶어서요

2024-02-05 11:57 UTC, sikkzz commented
![스크린샷 2024-02-05 오후 8 57 17](https://github.com/Selody-project/Frontend/assets/100590110/a44cda62-7fb7-4249-b569-02c4fb67c75f)

이 디자인 관련 기능도 들어가야겠네요

2024-02-06 11:06 UTC, kimyoungyin commented
> <img alt="스크린샷 2024-02-05 오후 8 53 32" width="282" src="https://private-user-images.githubusercontent.com/100590110/302279375-9da11ad3-456b-42ce-a95d-b6b2b0dbdfdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTc3MDAsIm5iZiI6MTcwNzIxNzQwMCwicGF0aCI6Ii8xMDA1OTAxMTAvMzAyMjc5Mzc1LTlkYTExYWQzLTQ1NmItNDJjZS1hOTVkLWI2YjJiMGRiZGZkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxMTAzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTdjMjYwMTJkNTBiZDA3NzdlZDVkNGVjZDMxNWVjMzVlN2I1YzI1YTY3MzIyMGM0NTFhZTcwYzc0NzBlOGNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lBGsb3a3tvwQIaeCEtb4l3IBQOrIzzuXp71kyayo_LY">
> 이 부분 스크롤이 작동이 안되는거 같은데 아직 미구현인건가요? 아니면 오류인건가요 확인 한번만 해주세요

밑으로 내려가도록 할게요

2024-02-07 05:47 UTC, kimyoungyin commented
> ![스크린샷 2024-02-05 오후 8 57 17](https://private-user-images.githubusercontent.com/100590110/302280307-a44cda62-7fb7-4249-b569-02c4fb67c75f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzk5NTYsIm5iZiI6MTcwNzI3OTY1NiwicGF0aCI6Ii8xMDA1OTAxMTAvMzAyMjgwMzA3LWE0NGNkYTYyLTdmYjctNDI0OS1iNTY5LTAyYzRmYjY3Yzc1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNDIwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTM0NTNjODE2NTE5NGZmNWM4N2UzMTVlNmFlM2I4NTdjOWY4YmJmNDU5YjI2NWM1Mzc0NTk3NTI3ZWRmOWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qL9YRcLZD4wnGXvkqoB1Xq7gCusUTrAuQAP5gOCCn5E)
> 
> 이 디자인 관련 기능도 들어가야겠네요

해당 부분 구현했는데 디자인은 똑같이 겹치는 게 어울릴 것 같아 연속으로 배치해봤어요, 어떠세요?
@sikkzz

2024-02-09 08:06 UTC, sikkzz commented
<img width="211" alt="스크린샷 2024-02-09 오후 5 06 17" src="https://github.com/Selody-project/Frontend/assets/100590110/196af84f-4b00-4535-8dae-2c5b59f62a4e">

max-height이 필요하지 않을까요?

2024-02-09 08:55 UTC, kimyoungyin commented
> <img alt="스크린샷 2024-02-09 오후 5 06 17" width="211" src="https://private-user-images.githubusercontent.com/100590110/303589301-196af84f-4b00-4535-8dae-2c5b59f62a4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NjkxOTgsIm5iZiI6MTcwNzQ2ODg5OCwicGF0aCI6Ii8xMDA1OTAxMTAvMzAzNTg5MzAxLTE5NmFmODRmLTRiMDAtNDUzNS04ZGFlLTJjNWI1OWY2MmE0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQwODU0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmE5NjBhMGJhMjI4ZDM0ZjRkOGNkNDViMDUyOTczOTZkNmZkMjUxNzY0MDJkMWZmMTAyNTg5YmY3MzA1YTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M-dJaaTlsZdYSeQmd9e1A29ww_LzEBJLArq7UflIQtA">
> max-height이 필요하지 않을까요?

이건 디자인 완성되면 수정할게요 아예 디자인이 없어서 ㅠ

2024-02-22 14:13 UTC, sikkzz approved these changes

2024-02-23 04:06 UTC, merged