196 front task 그룹 생성 시 그룹 이미지 첨부 기능 추가
Selody-project/Frontend pull request #197
Opened 2024-03-23 15:43 UTC by sikkzz

# 설명

- [https://github.com/Selody-project/Frontend/issues/196](https://github.com/Selody-project/Frontend/issues/196)
- 그룹 생성 시 그룹 이미지 첨부 기능 추가
- assets 폴더에 없는 이미지 파일 수정

2024-03-27 04:26 UTC, kimyoungyin requested changes

2024-03-27 04:26 UTC, kimyoungyin commented on src/components/Common/GroupModal/GroupCreateModal/GroupCreateModal.jsx
생성하기 버튼의 disabled 여부를 조금 더 명시해주는 게 좋아보입니다.
- 그룹 이름이 없거나, 있더라도 길이가 20 초과일 때
- 그룹 소개가 있더라도 길이가 100자 초과일 때

2024-03-27 12:24 UTC, sikkzz commented on src/components/Common/GroupModal/GroupCreateModal/GroupCreateModal.jsx
textarea maxLength가 잡혀있어서 그 이상 입력이 불가능하기에 해당 경우로 버튼이 disabled 되는 경우를 확인이 불가능합니다

2024-03-29 12:19 UTC, kimyoungyin approved these changes

2024-03-29 13:28 UTC, merged