200 front task 그룹 피드 클릭 시 상세 정보 및 댓글 구현
Selody-project/Frontend pull request #205
Opened 2024-04-02 08:42 UTC by sikkzz

# 설명

- [https://github.com/Selody-project/Frontend/issues/200](https://github.com/Selody-project/Frontend/issues/200)
- 그룹 피드 디테일 구현
- 댓글 조회, 작성, 삭제, 수정 구현

2024-04-05 06:43 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +		<BaseModal>
모달이 꺼지는 게 안되네요 수정 부탁드립니다. FormModal로 해서 댓글 작성 혹은 수정 중이면 경고를 줘도 됩니다

2024-04-05 06:43 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +						<button type="button" onClick={handleCommentButton}>
type을 submit으로 하는 게 낫지 않을까요?

2024-04-05 06:43 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +							{author === leaderName && <CrownIcon />}
유저의 일치 여부를 비교할 때는 id로 비교하는 게 좋아보입니다

2024-04-05 06:43 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +						<img src={authorImage} alt="profileImg" />
```suggestion
						<img src={authorImage} alt={`${author}님의 프로필 이미지`} />
```

2024-04-05 06:43 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.style.js
> +	overflow-y: scroll;
스크롤바를 없애주는 게 나아보입니다. 스크롤 할게 없을 때도 옆에 여백이 뜨고 조금 부자연스럽네요

2024-04-05 06:43 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +const FeedDetailModal = ({
댓글 수정을 할 때는 댓글이 있던 그 위치에서 수정하는 form이 뜨는 게 나아보이는데 어떠세요?
지금 어떤 댓글을 수정하고 있는지도 잘 모르겠고 전반적인 현 상태 구분이 안됩니다.

2024-04-05 06:43 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +	const [commentBtnText, setCommentBtnText] = useState("등록하기");
string을 constant로 이 파일 내에 만들어 오타 방지 및 가독성 향상

2024-04-05 06:43 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +const FeedDetailModal = ({
아니면 수정하고 있는 해당 댓글에 강조 표시를 해주던가 하면 간접적으로도 해결이 가능할 것 같네요

2024-04-05 06:43 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +	const [commentId, setCommentId] = useState(0);
이건 댓글 업로드할 때 param으로 받으면 되니 굳이 state로 관리할 필요 없지 않을까요

2024-04-05 06:43 UTC, kimyoungyin commented on src/components/Common/Feed/FeedOption.jsx
> +							<button
click 핸들러를 버튼에 달아뒀는데 버튼이 full width가 아니라서 클릭하기 불편합니다. button의 너비를 full로 li를 꽉 채워주시고 text-align을 center로 맞춰주는게 UX가 좋아요.

2024-04-05 06:43 UTC, kimyoungyin commented on src/components/Common/Feed/Feed.jsx
> +			key={post.postId}
key는 여기서 안 달아줘도 됩니다. 상위에서 map 처리할 때 해주네요

2024-04-05 06:43 UTC, kimyoungyin commented on src/constants/uiConstants.js
> +	FEED_DETAIL_MODAL: (feedId) => `FEED_DETAIL_MODAL${feedId}`,
메서드니까 명사형보단 동사형이 좋아보입니다

2024-04-05 06:43 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +		dispatch(getComments({ groupId, postId }));
나갈 때 comment 배열 초기화

2024-04-05 06:44 UTC, kimyoungyin requested changes
comment로 잘못 설정해서 request로 다시 바꿔서 리뷰 드립니다

2024-04-05 07:48 UTC, sikkzz commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +							{author === leaderName && <CrownIcon />}
이건 피드 작성자의 leaderID가 따로 없어서 닉네임으로 비교해야할 거 같아요

2024-04-05 07:54 UTC, sikkzz commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +		<BaseModal>
왜 FormModal로 바꿔도 작동을 안할까요? 문제점 한번 봐주실수 있을까요 모달 꺼지는 함수는 콘솔찍어보면 작동은 하는데 모달은 안꺼지네요

2024-04-05 08:00 UTC, sikkzz commented on src/constants/uiConstants.js
> +	FEED_DETAIL_MODAL: (feedId) => `FEED_DETAIL_MODAL${feedId}`,
ui 타입은 param에서 어떤 모달을 여는지를 나타내니까 통일성 생각하면 명사형으로 그대로 냅두는게 좋지 않을까요? 
UI_TYPE.~어떤 모달 이런 형식으로 사용하고 있으니까요

2024-04-05 08:06 UTC, sikkzz commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +	const [commentId, setCommentId] = useState(0);
commentId를 받는건 해당 컴포넌트가 아닌데 edit action은 여기서 실행되서 결국 전달 받을 state가 필요하더라고요 혹시 다른 좋은 방법이 있을까요?

2024-04-05 08:56 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +		<BaseModal>
isEmpty와 같은 prop도 잘 사용해보셨나요? 제가 지금 바로 확인하기 힘든 상황이라

2024-04-05 08:59 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +							{author === leaderName && <CrownIcon />}
아 그건 제가 수정해볼까요? leaderId로

2024-04-06 12:04 UTC, sikkzz commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +		<BaseModal>
네 여유있으실때 한번만 봐주세요

2024-04-06 14:59 UTC, kimyoungyin commented on src/constants/uiConstants.js
> +	FEED_DETAIL_MODAL: (feedId) => `FEED_DETAIL_MODAL${feedId}`,
혹시 그렇게 사용하는 게 좋다 하는 예시 글이나 사례가 있을까요? 저는 함수 베이스인 메서드는 동사형으로 명명하는 게 좋다고 알고 있어서

2024-04-08 08:36 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +		<BaseModal>
FormModal로 변경 안되어 있는데요? 일단 이건 되게 찾기 쉬운 에러입니다.. 연습해보시면 다음과 같습니다. 자세히 알려드릴 테 다음부터는 스스로 해보시길 바랍니다.

1. 문제 인식
문제: 모달이 안 닫힘? 
-> 이유: closeModal action이 작동하지 않거나, 작동해도 해당 모달을 유지시켜주는 action이 함께 발생해 배칭되면서 그대로 유지되버리는 것 둘 중 하나겠구나 생각.

2. redux action 문제니 크롬 익스텐션 활용
redux 크롬 익스텐션을 잘 활용해보시면 openFeedDetailModal이 closeModal 직후에 함께 생성됨을 확인할 수 있습니다.
그럼 왜 `openFeedDetailModal`이 같이 발생하는 지 알아봐야겠죠?

3. 해당 action을 dispatch하는 곳을 IDE에서 검색
검색 해보면 Feed에서만 사용 중이네요. 보면 가장 최상단에서 onClick 핸들러로 연결되어 있네요.

4. 난 Feed 클릭한 적 없는데? -> 컴포넌트 상하관계 체크해보기. 이벤트 버블링(혹은 캡처링)
FeedDetailModal은 Feed 컴포넌트 wrapper tag 내부에 함께 있기 때문에 이벤트 버블링이 발생하겠죠?
`FeedDetailModal`만을 클릭하더라도 상위 `Feed`도 클릭한 게 되버리는 거죠

5. 해결책: 모달이 상위 컴포넌트와 분리된 레이아웃을 가지면, Fragment로 처리하자
사실 `Feed` onClick 이벤트 핸들러에는 `event.stopPropagation()` 처리하는 것도 방법이겠지만, 저는 아예 wrapper로 Fragment 처리하는 것도 추천드립니다. 사실 서로가 속한, 상하관계가 아닌 컴포넌트들 인 것 같아서요.
```jsx
<>
    <FeedArticle onClick={...}>
    </FeedArticle>
    {.... && <FeedDetailModal />}
</>

```

2024-04-08 08:46 UTC, kimyoungyin requested changes

2024-04-08 08:46 UTC, kimyoungyin commented on src/components/Common/Feed/Feed.jsx
> +		<FeedArticle onClick={() => dispatch(openFeedDetailModal(post.postId))}>
여길 fragment로

2024-04-08 08:46 UTC, kimyoungyin commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +	const [commentId, setCommentId] = useState(0);
일단 수정할 때만 필요한 거니, 제가 다른 코멘트에 달아두었던 디자인, 레이아웃을 어떻게 할 지 결정 된 다음에 변경하면 될 것 같습니다. 제 생각에는 `FeedComment` 자체에 edit 전환이 가능하도록 해서 해당 댓글 위치 그대로 form으로 전환되는 방식이 괜찮아보여요. 지수님하고 어제 회의 때 상의 해보셨나요?

2024-04-08 13:36 UTC, sikkzz commented on src/constants/uiConstants.js
> +	FEED_DETAIL_MODAL: (feedId) => `FEED_DETAIL_MODAL${feedId}`,
아뇨 메서드긴해도 다른 타입들은 해당 모달 네임을 지칭하고 있으니 통일성 생각하면 open 붙이는게 아닌 그냥 모달 타입 네임으로 두는게 좋지 않겠냐는 얘기였어요

당연히 함수 네이밍은 동사형이 좋긴하지만요

2024-04-08 14:17 UTC, sikkzz commented on src/components/Common/Feed/FeedDetailModal/FeedDetailModal.jsx
> +							{author === leaderName && <CrownIcon />}
포스트 작성자의 id, 해당 그룹의 leader Id 이렇게 두개 있으면 비교 가능할 거 같아요

2024-04-09 06:30 UTC, kimyoungyin commented on src/constants/uiConstants.js
> +	FEED_DETAIL_MODAL: (feedId) => `FEED_DETAIL_MODAL${feedId}`,
지금 보니 FEED_DETAIL_MODAL의 집어넣는 feedId를 가져와서 모달 내부에서 사용하는 것도 아니고, 상위 컴포넌트인 `Feed` 컴포넌트에서 prop으로 피드의 모든 정보(postId 포함)를 prop으로 넘겨주고 있는데

굳이 FEED_DETAIL_MODAL 키에 해당하는 값을 저렇게 해야 할까요? 그냥 `FEED_DETAIL_MODAL: "FEED_DETAIL_MODAL`로만 작성하기만 하면 될 것 같은데요

2024-04-09 06:36 UTC, kimyoungyin requested changes

2024-04-09 06:36 UTC, kimyoungyin commented on src/components/Common/Feed/FeedComment/FeedComment.jsx
> +							</button>
intial value와 다를 때만 수정 가능하고 그게 아닌 경우 disabled 처리

2024-04-09 06:36 UTC, kimyoungyin commented on src/components/Common/Feed/FeedComment/FeedComment.jsx
> +						setIsEdit(true);
[scrollIntoView()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) 설정하여, 설정하려는 댓글의 위치를 스크롤의 천장에 딱 이동하도록 하는 게 좋아보입니다.
댓글 수정 form이 잘 보이도록이요

2024-04-09 06:36 UTC, kimyoungyin commented on src/components/Common/Feed/FeedComment/FeedComment.style.js
> +	/* width: calc(100% - 100px); */
주석은 일부러 남겨둔 게 아니면 삭제 부탁드립니다!

2024-04-09 09:53 UTC, sikkzz commented on src/constants/uiConstants.js
> +	FEED_DETAIL_MODAL: (feedId) => `FEED_DETAIL_MODAL${feedId}`,
각 피드 id를 구분 안해주면 모든 피드의 detail 모달이 뜨게 됩니다

2024-04-09 09:53 UTC, sikkzz commented on src/constants/uiConstants.js
> +	FEED_DETAIL_MODAL: (feedId) => `FEED_DETAIL_MODAL${feedId}`,
1번 피드를 눌러도 1번 2번 3번 모달이 다 뜨더라구요

2024-06-13 22:06 UTC, merged