192 front task 공유 일정 페이지 일정 후보 모달 및 후보 등록
Selody-project/Frontend pull request #208
Opened 2024-04-26 07:12 UTC by kimyoungyin

# 설명

- #192 
- 공유 일정 페이지 aside에 리스트는 투표 기능과 함께 구현할 예정이여서 간단한 `div`로만 대체함

# 테스트

- 구현 중

2024-05-06 13:26 UTC, sikkzz requested changes

2024-05-06 13:26 UTC, sikkzz commented on src/components/Common/SchedulePage/CalendarContainer/CustomCalendar/GroupMenu/GroupMenu.jsx
>  	);
구조분해할당 형식으로 수정할 수 있지 않을까요?

2024-05-06 13:26 UTC, sikkzz commented on src/components/Common/ScheduleProposalModal/ScheduleProposalModal.jsx
> +				/>
placeholder 필요해보입니다

2024-05-06 13:26 UTC, sikkzz commented on src/components/Common/ScheduleProposalModal/ScheduleProposalModal.jsx
<img width="224" alt="스크린샷 2024-05-06 오후 10 21 28" src="https://github.com/Selody-project/Frontend/assets/100590110/d44d7259-c31e-453f-bea5-5c323594095c">

추천받기 버튼 width가 어색한데 아래 등록하기 버튼이랑 맞추는건 어떠세요?

2024-05-06 13:28 UTC, sikkzz commented
개인일정쪽 schedulModal이랑 EditedProposalForm, ScheduleProposalModal 각각 기능이 비슷한 함수들이 있지 않나요? 이걸 좀 모듈화 시켜서 사용하는게 좋아 보이는데 어떠신가요

2024-05-06 13:29 UTC, sikkzz commented
다른 계정에서 공유 일정 작동 안하는거도 확인 다시 부탁드려요

2024-05-08 02:35 UTC, kimyoungyin commented
> 다른 계정에서 공유 일정 작동 안하는거도 확인 다시 부탁드려요

해결: [관련 노션 링크](https://www.notion.so/2024-05-07-63777d7b425a45f8ac41ccefa9001532?pvs=4#584a394a16fd4e9f86d12d307b7ca4a4)

2024-05-08 04:48 UTC, kimyoungyin commented on src/components/Common/ScheduleProposalModal/ScheduleProposalModal.jsx
저는 이 폼 자체를 제출하는 거랑 버튼을 같은 디자인으로 가면 안 될 것 같아서 저렇게 했었는데 이런 측면에서 생각해봐도 변경하는게 나을까요? 일단 지수님한테도 여쭤볼게요

2024-05-08 04:55 UTC, kimyoungyin commented
> 개인일정쪽 schedulModal이랑 EditedProposalForm, ScheduleProposalModal 각각 기능이 비슷한 함수들이 있지 않나요? 이걸 좀 모듈화 시켜서 사용하는게 좋아 보이는데 어떠신가요

저도 이 생각으로 시도를 조금 해봤었는데, 각자 다루는 form value들이 약간씩 달라서 조금 힘들더군요.. 다시 보고 분리하면 좋겠다 싶은 부분은 진행해볼게요

2024-05-08 05:21 UTC, kimyoungyin commented on src/components/Common/ScheduleProposalModal/ScheduleProposalModal.jsx
지수님하고 얘기 나눠보니까 너비만 수정하기로 했습니다. disabled 상태에서도 높이 차이가 있으니 색 구분이 되지 않을까 싶어 그대로 가려고 합니다.

2024-06-17 02:41 UTC, merged